/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * 至轻云
 * 超轻量级智能化大数据中心
 * OpenAPI spec version: 0.0.1
 */
import type {
  AddTenantReq,
  CheckTenantReq,
  ChooseTenantReq,
  ChooseTenantRes,
  DeleteTenantReq,
  DisableTenantReq,
  EnableTenantReq,
  GetTenantReq,
  GetTenantRes,
  PageTenantReq,
  PagedModelPageTenantRes,
  QueryUserTenantRes,
  ReplaceTenantAdminReq,
  UpdateTenantForSystemAdminReq,
  UpdateTenantForTenantAdminReq
} from '../models';

import { appRequest } from '../../api/orval-mutator';
import type { BodyType } from '../../api/orval-mutator';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  export const getTenant = () => {
/**
 * @summary 租户管理员更新租户接口
 */
const updateTenantForTenantAdmin = (
    updateTenantForTenantAdminReq: BodyType<UpdateTenantForTenantAdminReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/tenant/updateTenantForTenantAdmin`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: updateTenantForTenantAdminReq
    },
      options);
    }
  /**
 * @summary 租户管理员更新租户接口
 */
const updateTenantForTenantAdmin1 = (
    updateTenantForTenantAdminReq: BodyType<UpdateTenantForTenantAdminReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/api/platform/tenants/updateTenantForTenantAdmin`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: updateTenantForTenantAdminReq
    },
      options);
    }
  /**
 * @summary 系统管理员更新租户接口
 */
const updateTenantForSystemAdmin = (
    updateTenantForSystemAdminReq: BodyType<UpdateTenantForSystemAdminReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/tenant/updateTenantForSystemAdmin`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: updateTenantForSystemAdminReq
    },
      options);
    }
  /**
 * @summary 系统管理员更新租户接口
 */
const updateTenantForSystemAdmin1 = (
    updateTenantForSystemAdminReq: BodyType<UpdateTenantForSystemAdminReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/api/platform/tenants/updateTenantForSystemAdmin`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: updateTenantForSystemAdminReq
    },
      options);
    }
  /**
 * @summary 替换租户管理员接口
 */
const replaceTenantAdmin = (
    replaceTenantAdminReq: BodyType<ReplaceTenantAdminReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/api/platform/tenants/replaceAdmin`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: replaceTenantAdminReq
    },
      options);
    }
  /**
 * @summary 替换租户管理员接口
 */
const replaceTenantAdmin1 = (
    replaceTenantAdminReq: BodyType<ReplaceTenantAdminReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/tenant/replaceAdmin`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: replaceTenantAdminReq
    },
      options);
    }
  /**
 * @summary 查询用户租户列表接口
 */
const queryUserTenant = (

 options?: SecondParameter<typeof appRequest<QueryUserTenantRes[]>>,) => {
      return appRequest<QueryUserTenantRes[]>(
      {url: `/api/platform/tenants/queryUserTenant`, method: 'POST'
    },
      options);
    }
  /**
 * @summary 查询用户租户列表接口
 */
const queryUserTenant1 = (

 options?: SecondParameter<typeof appRequest<QueryUserTenantRes[]>>,) => {
      return appRequest<QueryUserTenantRes[]>(
      {url: `/tenant/queryUserTenant`, method: 'POST'
    },
      options);
    }
  /**
 * @summary 查询租户列表接口
 */
const pageTenant = (
    pageTenantReq: BodyType<PageTenantReq>,
 options?: SecondParameter<typeof appRequest<PagedModelPageTenantRes>>,) => {
      return appRequest<PagedModelPageTenantRes>(
      {url: `/tenant/pageTenant`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: pageTenantReq
    },
      options);
    }
  /**
 * @summary 查询租户列表接口
 */
const pageTenant1 = (
    pageTenantReq: BodyType<PageTenantReq>,
 options?: SecondParameter<typeof appRequest<PagedModelPageTenantRes>>,) => {
      return appRequest<PagedModelPageTenantRes>(
      {url: `/api/platform/tenants/pageTenant`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: pageTenantReq
    },
      options);
    }
  /**
 * @summary 获取租户信息接口
 */
const getTenant = (
    getTenantReq: BodyType<GetTenantReq>,
 options?: SecondParameter<typeof appRequest<GetTenantRes>>,) => {
      return appRequest<GetTenantRes>(
      {url: `/tenant/getTenant`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: getTenantReq
    },
      options);
    }
  /**
 * @summary 获取租户信息接口
 */
const getTenant1 = (
    getTenantReq: BodyType<GetTenantReq>,
 options?: SecondParameter<typeof appRequest<GetTenantRes>>,) => {
      return appRequest<GetTenantRes>(
      {url: `/api/platform/tenants/getTenant`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: getTenantReq
    },
      options);
    }
  /**
 * @summary 启动租户接口
 */
const enableTenant = (
    enableTenantReq: BodyType<EnableTenantReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/api/platform/tenants/enableTenant`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: enableTenantReq
    },
      options);
    }
  /**
 * @summary 启动租户接口
 */
const enableTenant1 = (
    enableTenantReq: BodyType<EnableTenantReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/tenant/enableTenant`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: enableTenantReq
    },
      options);
    }
  /**
 * @summary 禁用租户接口
 */
const disableTenant = (
    disableTenantReq: BodyType<DisableTenantReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/tenant/disableTenant`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: disableTenantReq
    },
      options);
    }
  /**
 * @summary 禁用租户接口
 */
const disableTenant1 = (
    disableTenantReq: BodyType<DisableTenantReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/api/platform/tenants/disableTenant`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: disableTenantReq
    },
      options);
    }
  /**
 * @summary 删除租户接口
 */
const deleteTenant = (
    deleteTenantReq: BodyType<DeleteTenantReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/tenant/deleteTenant`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: deleteTenantReq
    },
      options);
    }
  /**
 * @summary 删除租户接口
 */
const deleteTenant1 = (
    deleteTenantReq: BodyType<DeleteTenantReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/api/platform/tenants/deleteTenant`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: deleteTenantReq
    },
      options);
    }
  /**
 * @summary 选择租户接口
 */
const chooseTenant = (
    chooseTenantReq: BodyType<ChooseTenantReq>,
 options?: SecondParameter<typeof appRequest<ChooseTenantRes>>,) => {
      return appRequest<ChooseTenantRes>(
      {url: `/tenant/chooseTenant`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: chooseTenantReq
    },
      options);
    }
  /**
 * @summary 选择租户接口
 */
const chooseTenant1 = (
    chooseTenantReq: BodyType<ChooseTenantReq>,
 options?: SecondParameter<typeof appRequest<ChooseTenantRes>>,) => {
      return appRequest<ChooseTenantRes>(
      {url: `/api/platform/tenants/chooseTenant`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: chooseTenantReq
    },
      options);
    }
  /**
 * @summary 检测租户信息接口
 */
const checkTenant = (
    checkTenantReq: BodyType<CheckTenantReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/api/platform/tenants/checkTenant`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: checkTenantReq
    },
      options);
    }
  /**
 * @summary 检测租户信息接口
 */
const checkTenant1 = (
    checkTenantReq: BodyType<CheckTenantReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/tenant/checkTenant`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: checkTenantReq
    },
      options);
    }
  /**
 * @summary 创建租户接口
 */
const addTenant = (
    addTenantReq: BodyType<AddTenantReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/api/platform/tenants/addTenant`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: addTenantReq
    },
      options);
    }
  /**
 * @summary 创建租户接口
 */
const addTenant1 = (
    addTenantReq: BodyType<AddTenantReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/tenant/addTenant`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: addTenantReq
    },
      options);
    }
  return {updateTenantForTenantAdmin,updateTenantForTenantAdmin1,updateTenantForSystemAdmin,updateTenantForSystemAdmin1,replaceTenantAdmin,replaceTenantAdmin1,queryUserTenant,queryUserTenant1,pageTenant,pageTenant1,getTenant,getTenant1,enableTenant,enableTenant1,disableTenant,disableTenant1,deleteTenant,deleteTenant1,chooseTenant,chooseTenant1,checkTenant,checkTenant1,addTenant,addTenant1}};
export type UpdateTenantForTenantAdminResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getTenant>['updateTenantForTenantAdmin']>>>
export type UpdateTenantForTenantAdmin1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getTenant>['updateTenantForTenantAdmin1']>>>
export type UpdateTenantForSystemAdminResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getTenant>['updateTenantForSystemAdmin']>>>
export type UpdateTenantForSystemAdmin1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getTenant>['updateTenantForSystemAdmin1']>>>
export type ReplaceTenantAdminResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getTenant>['replaceTenantAdmin']>>>
export type ReplaceTenantAdmin1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getTenant>['replaceTenantAdmin1']>>>
export type QueryUserTenantResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getTenant>['queryUserTenant']>>>
export type QueryUserTenant1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getTenant>['queryUserTenant1']>>>
export type PageTenantResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getTenant>['pageTenant']>>>
export type PageTenant1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getTenant>['pageTenant1']>>>
export type GetTenantResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getTenant>['getTenant']>>>
export type GetTenant1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getTenant>['getTenant1']>>>
export type EnableTenantResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getTenant>['enableTenant']>>>
export type EnableTenant1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getTenant>['enableTenant1']>>>
export type DisableTenantResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getTenant>['disableTenant']>>>
export type DisableTenant1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getTenant>['disableTenant1']>>>
export type DeleteTenantResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getTenant>['deleteTenant']>>>
export type DeleteTenant1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getTenant>['deleteTenant1']>>>
export type ChooseTenantResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getTenant>['chooseTenant']>>>
export type ChooseTenant1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getTenant>['chooseTenant1']>>>
export type CheckTenantResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getTenant>['checkTenant']>>>
export type CheckTenant1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getTenant>['checkTenant1']>>>
export type AddTenantResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getTenant>['addTenant']>>>
export type AddTenant1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getTenant>['addTenant1']>>>
