dependencies {

    api(project(':spark-yun-backend:spark-yun-modules'))
    api(project(':spark-yun-vip:spark-yun-backend'))

    implementation 'org.springframework.boot:spring-boot-starter-quartz'
    implementation libs.druid.spring.boot.starter
    implementation libs.spring.ai.openai

    implementation libs.flyway.core
    implementation libs.flyway.mysql
    implementation libs.flyway.postgresql

    runtimeOnly 'com.h2database:h2'
}

bootJar {

    enabled = true
    mainClass = 'com.isxcode.spark.SparkYunApplication'
    archiveFileName = 'zhiqingyun.jar'

    dependsOn(':spark-yun-frontend:make', ':spark-yun-dist:build_agent')

    from(rootProject.file('spark-yun-frontend/dist')) {
        into 'BOOT-INF/classes'
    }

}

processResources {

    dependsOn(':spark-yun-dist:build_agent')

    from(rootDir.getAbsolutePath() + '/VERSION') {
        into '.'
    }

    from(rootDir.getAbsolutePath() + '/resources/libs') {
        include 'libprql_*'
        into '.'
    }

    from(rootProject.file('spark-yun-dist/build/distributions/zhiqingyun-agent.tar.gz')) {
        into 'agent'
    }
}

bootRun {
    workingDir(rootDir.getAbsolutePath())
}
