/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * 至轻云
 * 超轻量级智能化大数据中心
 * OpenAPI spec version: 0.0.1
 */
import type {
  AbortFlowReq,
  AddWorkflowReq,
  BreakFlowReq,
  ConfigWorkflowReq,
  ConfigWorkflowSettingReq,
  DeleteWorkflowReq,
  ExportWorkflowReq,
  GetInvokeUrlReq,
  GetInvokeUrlRes,
  GetRunWorkInstancesReq,
  GetRunWorkInstancesRes,
  GetWorkflowDefaultClusterReq,
  GetWorkflowDefaultClusterRes,
  GetWorkflowReq,
  GetWorkflowRes,
  ImportWorkflow1Body,
  ImportWorkflow1Params,
  ImportWorkflowBody,
  ImportWorkflowParams,
  InvokeWorkflowReq,
  PageWorkflowReq,
  PagedModelPageWorkflowRes,
  PagedModelQueryWorkFlowInstancesRes,
  QueryWorkFlowInstancesReq,
  ReRunFlowReq,
  RunAfterFlowReq,
  RunCurrentNodeReq,
  RunWorkflowReq,
  UpdateWorkflowReq
} from '../models';

import { appRequest } from '../../api/orval-mutator';
import type { BodyType } from '../../api/orval-mutator';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  export const getWorkflow = () => {
/**
 * @summary 更新作业流接口
 */
const updateWorkflow = (
    updateWorkflowReq: BodyType<UpdateWorkflowReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/workflow/updateWorkflow`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: updateWorkflowReq
    },
      options);
    }
  /**
 * @summary 更新作业流接口
 */
const updateWorkflow1 = (
    updateWorkflowReq: BodyType<UpdateWorkflowReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/api/workspace/workflow/updateWorkflow`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: updateWorkflowReq
    },
      options);
    }
  /**
 * @summary 运行工作流接口
 */
const runWorkflow = (
    runWorkflowReq: BodyType<RunWorkflowReq>,
 options?: SecondParameter<typeof appRequest<string>>,) => {
      return appRequest<string>(
      {url: `/workflow/runWorkflow`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: runWorkflowReq
    },
      options);
    }
  /**
 * @summary 运行工作流接口
 */
const runWorkflow1 = (
    runWorkflowReq: BodyType<RunWorkflowReq>,
 options?: SecondParameter<typeof appRequest<string>>,) => {
      return appRequest<string>(
      {url: `/api/workspace/workflow/runWorkflow`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: runWorkflowReq
    },
      options);
    }
  /**
 * @summary 重跑当前节点接口
 */
const runCurrentNode = (
    runCurrentNodeReq: BodyType<RunCurrentNodeReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/api/workspace/workflow/runCurrentNode`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: runCurrentNodeReq
    },
      options);
    }
  /**
 * @summary 重跑当前节点接口
 */
const runCurrentNode1 = (
    runCurrentNodeReq: BodyType<RunCurrentNodeReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/workflow/runCurrentNode`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: runCurrentNodeReq
    },
      options);
    }
  /**
 * @summary 重跑下游接口
 */
const runAfterFlow = (
    runAfterFlowReq: BodyType<RunAfterFlowReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/api/workspace/workflow/runAfterFlow`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: runAfterFlowReq
    },
      options);
    }
  /**
 * @summary 重跑下游接口
 */
const runAfterFlow1 = (
    runAfterFlowReq: BodyType<RunAfterFlowReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/workflow/runAfterFlow`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: runAfterFlowReq
    },
      options);
    }
  /**
 * @summary 重跑工作流接口
 */
const reRunFlow = (
    reRunFlowReq: BodyType<ReRunFlowReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/workflow/reRunFlow`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: reRunFlowReq
    },
      options);
    }
  /**
 * @summary 重跑工作流接口
 */
const reRunFlow1 = (
    reRunFlowReq: BodyType<ReRunFlowReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/api/workspace/workflow/reRunFlow`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: reRunFlowReq
    },
      options);
    }
  /**
 * @summary 查询作业流实例列表接口
 */
const queryWorkFlowInstances = (
    queryWorkFlowInstancesReq: BodyType<QueryWorkFlowInstancesReq>,
 options?: SecondParameter<typeof appRequest<PagedModelQueryWorkFlowInstancesRes>>,) => {
      return appRequest<PagedModelQueryWorkFlowInstancesRes>(
      {url: `/api/workspace/workflow/queryWorkFlowInstances`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: queryWorkFlowInstancesReq
    },
      options);
    }
  /**
 * @summary 查询作业流实例列表接口
 */
const queryWorkFlowInstances1 = (
    queryWorkFlowInstancesReq: BodyType<QueryWorkFlowInstancesReq>,
 options?: SecondParameter<typeof appRequest<PagedModelQueryWorkFlowInstancesRes>>,) => {
      return appRequest<PagedModelQueryWorkFlowInstancesRes>(
      {url: `/workflow/queryWorkFlowInstances`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: queryWorkFlowInstancesReq
    },
      options);
    }
  /**
 * @summary 分页查询作业流接口
 */
const pageWorkflow = (
    pageWorkflowReq: BodyType<PageWorkflowReq>,
 options?: SecondParameter<typeof appRequest<PagedModelPageWorkflowRes>>,) => {
      return appRequest<PagedModelPageWorkflowRes>(
      {url: `/api/workspace/workflow/pageWorkflow`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: pageWorkflowReq
    },
      options);
    }
  /**
 * @summary 分页查询作业流接口
 */
const pageWorkflow1 = (
    pageWorkflowReq: BodyType<PageWorkflowReq>,
 options?: SecondParameter<typeof appRequest<PagedModelPageWorkflowRes>>,) => {
      return appRequest<PagedModelPageWorkflowRes>(
      {url: `/workflow/pageWorkflow`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: pageWorkflowReq
    },
      options);
    }
  /**
 * @summary 外部调用作业流接口
 */
const invokeWorkflow = (
    invokeWorkflowReq: BodyType<InvokeWorkflowReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/workflow/open/invokeWorkflow`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: invokeWorkflowReq
    },
      options);
    }
  /**
 * @summary 外部调用作业流接口
 */
const invokeWorkflow1 = (
    invokeWorkflowReq: BodyType<InvokeWorkflowReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/api/workspace/workflow/open/invokeWorkflow`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: invokeWorkflowReq
    },
      options);
    }
  /**
 * @summary 作业流导入接口(Swagger有Bug不能使用)
 */
const importWorkflow = (
    importWorkflowBody?: BodyType<ImportWorkflowBody>,
    params?: ImportWorkflowParams,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/workflow/importWorkflow`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: importWorkflowBody,
        params
    },
      options);
    }
  /**
 * @summary 作业流导入接口(Swagger有Bug不能使用)
 */
const importWorkflow1 = (
    importWorkflow1Body?: BodyType<ImportWorkflow1Body>,
    params?: ImportWorkflow1Params,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/api/workspace/workflow/importWorkflow`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: importWorkflow1Body,
        params
    },
      options);
    }
  /**
 * @summary 获取作业流默认计算引擎接口
 */
const getWorkflowDefaultCluster = (
    getWorkflowDefaultClusterReq: BodyType<GetWorkflowDefaultClusterReq>,
 options?: SecondParameter<typeof appRequest<GetWorkflowDefaultClusterRes>>,) => {
      return appRequest<GetWorkflowDefaultClusterRes>(
      {url: `/api/workspace/workflow/getWorkflowDefaultCluster`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: getWorkflowDefaultClusterReq
    },
      options);
    }
  /**
 * @summary 获取作业流默认计算引擎接口
 */
const getWorkflowDefaultCluster1 = (
    getWorkflowDefaultClusterReq: BodyType<GetWorkflowDefaultClusterReq>,
 options?: SecondParameter<typeof appRequest<GetWorkflowDefaultClusterRes>>,) => {
      return appRequest<GetWorkflowDefaultClusterRes>(
      {url: `/workflow/getWorkflowDefaultCluster`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: getWorkflowDefaultClusterReq
    },
      options);
    }
  /**
 * @summary 查询作业流接口
 */
const getWorkflow = (
    getWorkflowReq: BodyType<GetWorkflowReq>,
 options?: SecondParameter<typeof appRequest<GetWorkflowRes>>,) => {
      return appRequest<GetWorkflowRes>(
      {url: `/api/workspace/workflow/getWorkflow`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: getWorkflowReq
    },
      options);
    }
  /**
 * @summary 查询作业流接口
 */
const getWorkflow1 = (
    getWorkflowReq: BodyType<GetWorkflowReq>,
 options?: SecondParameter<typeof appRequest<GetWorkflowRes>>,) => {
      return appRequest<GetWorkflowRes>(
      {url: `/workflow/getWorkflow`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: getWorkflowReq
    },
      options);
    }
  /**
 * @summary 查询作业流运行实例接口
 */
const getRunWorkInstances = (
    getRunWorkInstancesReq: BodyType<GetRunWorkInstancesReq>,
 options?: SecondParameter<typeof appRequest<GetRunWorkInstancesRes>>,) => {
      return appRequest<GetRunWorkInstancesRes>(
      {url: `/api/workspace/workflow/getRunWorkInstances`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: getRunWorkInstancesReq
    },
      options);
    }
  /**
 * @summary 查询作业流运行实例接口
 */
const getRunWorkInstances1 = (
    getRunWorkInstancesReq: BodyType<GetRunWorkInstancesReq>,
 options?: SecondParameter<typeof appRequest<GetRunWorkInstancesRes>>,) => {
      return appRequest<GetRunWorkInstancesRes>(
      {url: `/workflow/getRunWorkInstances`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: getRunWorkInstancesReq
    },
      options);
    }
  /**
 * @summary 获取作业流外部调用url接口
 */
const getInvokeUrl = (
    getInvokeUrlReq: BodyType<GetInvokeUrlReq>,
 options?: SecondParameter<typeof appRequest<GetInvokeUrlRes>>,) => {
      return appRequest<GetInvokeUrlRes>(
      {url: `/api/workspace/workflow/getInvokeUrl`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: getInvokeUrlReq
    },
      options);
    }
  /**
 * @summary 获取作业流外部调用url接口
 */
const getInvokeUrl1 = (
    getInvokeUrlReq: BodyType<GetInvokeUrlReq>,
 options?: SecondParameter<typeof appRequest<GetInvokeUrlRes>>,) => {
      return appRequest<GetInvokeUrlRes>(
      {url: `/workflow/getInvokeUrl`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: getInvokeUrlReq
    },
      options);
    }
  /**
 * @summary 作业流导出接口
 */
const exportWorkflow = (
    exportWorkflowReq: BodyType<ExportWorkflowReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/api/workspace/workflow/exportWorkflow`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: exportWorkflowReq
    },
      options);
    }
  /**
 * @summary 作业流导出接口
 */
const exportWorkflow1 = (
    exportWorkflowReq: BodyType<ExportWorkflowReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/workflow/exportWorkflow`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: exportWorkflowReq
    },
      options);
    }
  /**
 * @summary 删除作业流接口
 */
const deleteWorkflow = (
    deleteWorkflowReq: BodyType<DeleteWorkflowReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/workflow/deleteWorkflow`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: deleteWorkflowReq
    },
      options);
    }
  /**
 * @summary 删除作业流接口
 */
const deleteWorkflow1 = (
    deleteWorkflowReq: BodyType<DeleteWorkflowReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/api/workspace/workflow/deleteWorkflow`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: deleteWorkflowReq
    },
      options);
    }
  /**
 * @summary 配置作业流接口（非dag图保存的内容）
 */
const configWorkflowSetting = (
    configWorkflowSettingReq: BodyType<ConfigWorkflowSettingReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/workflow/configWorkflowSetting`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: configWorkflowSettingReq
    },
      options);
    }
  /**
 * @summary 配置作业流接口（非dag图保存的内容）
 */
const configWorkflowSetting1 = (
    configWorkflowSettingReq: BodyType<ConfigWorkflowSettingReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/api/workspace/workflow/configWorkflowSetting`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: configWorkflowSettingReq
    },
      options);
    }
  /**
 * @summary 配置作业流接口
 */
const configWorkflow = (
    configWorkflowReq: BodyType<ConfigWorkflowReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/workflow/configWorkflow`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: configWorkflowReq
    },
      options);
    }
  /**
 * @summary 配置作业流接口
 */
const configWorkflow1 = (
    configWorkflowReq: BodyType<ConfigWorkflowReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/api/workspace/workflow/configWorkflow`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: configWorkflowReq
    },
      options);
    }
  /**
 * @summary 中断工作流接口
 */
const breakFlow = (
    breakFlowReq: BodyType<BreakFlowReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/workflow/breakFlow`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: breakFlowReq
    },
      options);
    }
  /**
 * @summary 中断工作流接口
 */
const breakFlow1 = (
    breakFlowReq: BodyType<BreakFlowReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/api/workspace/workflow/breakFlow`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: breakFlowReq
    },
      options);
    }
  /**
 * @summary 新建作业流接口
 */
const addWorkflow = (
    addWorkflowReq: BodyType<AddWorkflowReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/workflow/addWorkflow`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: addWorkflowReq
    },
      options);
    }
  /**
 * @summary 新建作业流接口
 */
const addWorkflow1 = (
    addWorkflowReq: BodyType<AddWorkflowReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/api/workspace/workflow/addWorkflow`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: addWorkflowReq
    },
      options);
    }
  /**
 * @summary 中止工作流接口
 */
const abortFlow = (
    abortFlowReq: BodyType<AbortFlowReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/api/workspace/workflow/abortFlow`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: abortFlowReq
    },
      options);
    }
  /**
 * @summary 中止工作流接口
 */
const abortFlow1 = (
    abortFlowReq: BodyType<AbortFlowReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/workflow/abortFlow`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: abortFlowReq
    },
      options);
    }
  return {updateWorkflow,updateWorkflow1,runWorkflow,runWorkflow1,runCurrentNode,runCurrentNode1,runAfterFlow,runAfterFlow1,reRunFlow,reRunFlow1,queryWorkFlowInstances,queryWorkFlowInstances1,pageWorkflow,pageWorkflow1,invokeWorkflow,invokeWorkflow1,importWorkflow,importWorkflow1,getWorkflowDefaultCluster,getWorkflowDefaultCluster1,getWorkflow,getWorkflow1,getRunWorkInstances,getRunWorkInstances1,getInvokeUrl,getInvokeUrl1,exportWorkflow,exportWorkflow1,deleteWorkflow,deleteWorkflow1,configWorkflowSetting,configWorkflowSetting1,configWorkflow,configWorkflow1,breakFlow,breakFlow1,addWorkflow,addWorkflow1,abortFlow,abortFlow1}};
export type UpdateWorkflowResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getWorkflow>['updateWorkflow']>>>
export type UpdateWorkflow1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getWorkflow>['updateWorkflow1']>>>
export type RunWorkflowResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getWorkflow>['runWorkflow']>>>
export type RunWorkflow1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getWorkflow>['runWorkflow1']>>>
export type RunCurrentNodeResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getWorkflow>['runCurrentNode']>>>
export type RunCurrentNode1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getWorkflow>['runCurrentNode1']>>>
export type RunAfterFlowResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getWorkflow>['runAfterFlow']>>>
export type RunAfterFlow1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getWorkflow>['runAfterFlow1']>>>
export type ReRunFlowResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getWorkflow>['reRunFlow']>>>
export type ReRunFlow1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getWorkflow>['reRunFlow1']>>>
export type QueryWorkFlowInstancesResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getWorkflow>['queryWorkFlowInstances']>>>
export type QueryWorkFlowInstances1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getWorkflow>['queryWorkFlowInstances1']>>>
export type PageWorkflowResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getWorkflow>['pageWorkflow']>>>
export type PageWorkflow1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getWorkflow>['pageWorkflow1']>>>
export type InvokeWorkflowResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getWorkflow>['invokeWorkflow']>>>
export type InvokeWorkflow1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getWorkflow>['invokeWorkflow1']>>>
export type ImportWorkflowResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getWorkflow>['importWorkflow']>>>
export type ImportWorkflow1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getWorkflow>['importWorkflow1']>>>
export type GetWorkflowDefaultClusterResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getWorkflow>['getWorkflowDefaultCluster']>>>
export type GetWorkflowDefaultCluster1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getWorkflow>['getWorkflowDefaultCluster1']>>>
export type GetWorkflowResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getWorkflow>['getWorkflow']>>>
export type GetWorkflow1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getWorkflow>['getWorkflow1']>>>
export type GetRunWorkInstancesResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getWorkflow>['getRunWorkInstances']>>>
export type GetRunWorkInstances1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getWorkflow>['getRunWorkInstances1']>>>
export type GetInvokeUrlResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getWorkflow>['getInvokeUrl']>>>
export type GetInvokeUrl1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getWorkflow>['getInvokeUrl1']>>>
export type ExportWorkflowResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getWorkflow>['exportWorkflow']>>>
export type ExportWorkflow1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getWorkflow>['exportWorkflow1']>>>
export type DeleteWorkflowResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getWorkflow>['deleteWorkflow']>>>
export type DeleteWorkflow1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getWorkflow>['deleteWorkflow1']>>>
export type ConfigWorkflowSettingResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getWorkflow>['configWorkflowSetting']>>>
export type ConfigWorkflowSetting1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getWorkflow>['configWorkflowSetting1']>>>
export type ConfigWorkflowResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getWorkflow>['configWorkflow']>>>
export type ConfigWorkflow1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getWorkflow>['configWorkflow1']>>>
export type BreakFlowResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getWorkflow>['breakFlow']>>>
export type BreakFlow1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getWorkflow>['breakFlow1']>>>
export type AddWorkflowResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getWorkflow>['addWorkflow']>>>
export type AddWorkflow1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getWorkflow>['addWorkflow1']>>>
export type AbortFlowResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getWorkflow>['abortFlow']>>>
export type AbortFlow1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getWorkflow>['abortFlow1']>>>
