/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * 至轻云
 * 超轻量级智能化大数据中心
 * OpenAPI spec version: 0.0.1
 */
import type {
  AddSecretReq,
  DeleteSecretReq,
  GetSecretExpressionReq,
  GetSecretExpressionRes,
  PageSecretReq,
  PagedModelPageSecretRes,
  UpdateSecretReq
} from '../models';

import { appRequest } from '../../api/orval-mutator';
import type { BodyType } from '../../api/orval-mutator';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  export const getGlobalVariable = () => {
/**
 * @summary 编辑变量接口
 */
const updateSecret = (
    updateSecretReq: BodyType<UpdateSecretReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/api/workspace/vip/secret/updateSecret`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: updateSecretReq
    },
      options);
    }
  /**
 * @summary 编辑变量接口
 */
const updateSecret1 = (
    updateSecretReq: BodyType<UpdateSecretReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/vip/secret/updateSecret`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: updateSecretReq
    },
      options);
    }
  /**
 * @summary 查询变量接口
 */
const pageSecret = (
    pageSecretReq: BodyType<PageSecretReq>,
 options?: SecondParameter<typeof appRequest<PagedModelPageSecretRes>>,) => {
      return appRequest<PagedModelPageSecretRes>(
      {url: `/api/workspace/vip/secret/pageSecret`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: pageSecretReq
    },
      options);
    }
  /**
 * @summary 查询变量接口
 */
const pageSecret1 = (
    pageSecretReq: BodyType<PageSecretReq>,
 options?: SecondParameter<typeof appRequest<PagedModelPageSecretRes>>,) => {
      return appRequest<PagedModelPageSecretRes>(
      {url: `/vip/secret/pageSecret`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: pageSecretReq
    },
      options);
    }
  /**
 * @summary 一键复制变量表达式接口
 */
const getSecretExpression = (
    getSecretExpressionReq: BodyType<GetSecretExpressionReq>,
 options?: SecondParameter<typeof appRequest<GetSecretExpressionRes>>,) => {
      return appRequest<GetSecretExpressionRes>(
      {url: `/api/workspace/vip/secret/getSecretExpression`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: getSecretExpressionReq
    },
      options);
    }
  /**
 * @summary 一键复制变量表达式接口
 */
const getSecretExpression1 = (
    getSecretExpressionReq: BodyType<GetSecretExpressionReq>,
 options?: SecondParameter<typeof appRequest<GetSecretExpressionRes>>,) => {
      return appRequest<GetSecretExpressionRes>(
      {url: `/vip/secret/getSecretExpression`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: getSecretExpressionReq
    },
      options);
    }
  /**
 * @summary 删除变量接口
 */
const deleteSecret = (
    deleteSecretReq: BodyType<DeleteSecretReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/api/workspace/vip/secret/deleteSecret`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: deleteSecretReq
    },
      options);
    }
  /**
 * @summary 删除变量接口
 */
const deleteSecret1 = (
    deleteSecretReq: BodyType<DeleteSecretReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/vip/secret/deleteSecret`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: deleteSecretReq
    },
      options);
    }
  /**
 * @summary 新建变量接口
 */
const addSecret = (
    addSecretReq: BodyType<AddSecretReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/api/workspace/vip/secret/addSecret`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: addSecretReq
    },
      options);
    }
  /**
 * @summary 新建变量接口
 */
const addSecret1 = (
    addSecretReq: BodyType<AddSecretReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/vip/secret/addSecret`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: addSecretReq
    },
      options);
    }
  return {updateSecret,updateSecret1,pageSecret,pageSecret1,getSecretExpression,getSecretExpression1,deleteSecret,deleteSecret1,addSecret,addSecret1}};
export type UpdateSecretResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getGlobalVariable>['updateSecret']>>>
export type UpdateSecret1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getGlobalVariable>['updateSecret1']>>>
export type PageSecretResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getGlobalVariable>['pageSecret']>>>
export type PageSecret1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getGlobalVariable>['pageSecret1']>>>
export type GetSecretExpressionResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getGlobalVariable>['getSecretExpression']>>>
export type GetSecretExpression1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getGlobalVariable>['getSecretExpression1']>>>
export type DeleteSecretResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getGlobalVariable>['deleteSecret']>>>
export type DeleteSecret1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getGlobalVariable>['deleteSecret1']>>>
export type AddSecretResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getGlobalVariable>['addSecret']>>>
export type AddSecret1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getGlobalVariable>['addSecret1']>>>
