/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * 至轻云
 * 超轻量级智能化大数据中心
 * OpenAPI spec version: 0.0.1
 */
import type {
  AddTenantUserReq,
  PageTenantUserReq,
  PagedModelPageTenantUserRes,
  RemoveTenantAdminReq,
  RemoveTenantUserReq,
  SetMemberRolesReq,
  SetTenantAdminReq,
  SetTenantMemberStatusReq
} from '../models';

import { appRequest } from '../../api/orval-mutator';
import type { BodyType } from '../../api/orval-mutator';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  export const getTenantUser = () => {
/**
 * @summary 设置为普通管理员接口
 */
const setTenantAdmin = (
    setTenantAdminReq: BodyType<SetTenantAdminReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/tenant-user/setTenantAdmin`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: setTenantAdminReq
    },
      options);
    }
  /**
 * @summary 设置为普通管理员接口
 */
const setTenantAdmin1 = (
    setTenantAdminReq: BodyType<SetTenantAdminReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/api/admin/members/setTenantAdmin`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: setTenantAdminReq
    },
      options);
    }
  /**
 * @summary 修改成员状态接口
 */
const setTenantMemberStatus = (
    setTenantMemberStatusReq: BodyType<SetTenantMemberStatusReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/tenant-user/setStatus`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: setTenantMemberStatusReq
    },
      options);
    }
  /**
 * @summary 修改成员状态接口
 */
const setTenantMemberStatus1 = (
    setTenantMemberStatusReq: BodyType<SetTenantMemberStatusReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/api/admin/members/setStatus`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: setTenantMemberStatusReq
    },
      options);
    }
  /**
 * @summary 设置成员角色接口
 */
const setMemberRoles = (
    setMemberRolesReq: BodyType<SetMemberRolesReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/api/admin/members/setRoles`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: setMemberRolesReq
    },
      options);
    }
  /**
 * @summary 设置成员角色接口
 */
const setMemberRoles1 = (
    setMemberRolesReq: BodyType<SetMemberRolesReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/tenant-user/setRoles`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: setMemberRolesReq
    },
      options);
    }
  /**
 * @summary 移除用户接口
 */
const removeTenantUser = (
    removeTenantUserReq: BodyType<RemoveTenantUserReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/api/admin/members/removeTenantUser`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: removeTenantUserReq
    },
      options);
    }
  /**
 * @summary 移除用户接口
 */
const removeTenantUser1 = (
    removeTenantUserReq: BodyType<RemoveTenantUserReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/tenant-user/removeTenantUser`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: removeTenantUserReq
    },
      options);
    }
  /**
 * @summary 取消普通管理员接口
 */
const removeTenantAdmin = (
    removeTenantAdminReq: BodyType<RemoveTenantAdminReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/tenant-user/removeTenantAdmin`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: removeTenantAdminReq
    },
      options);
    }
  /**
 * @summary 取消普通管理员接口
 */
const removeTenantAdmin1 = (
    removeTenantAdminReq: BodyType<RemoveTenantAdminReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/api/admin/members/removeTenantAdmin`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: removeTenantAdminReq
    },
      options);
    }
  /**
 * @summary 查询租户用户列表接口
 */
const pageTenantUser = (
    pageTenantUserReq: BodyType<PageTenantUserReq>,
 options?: SecondParameter<typeof appRequest<PagedModelPageTenantUserRes>>,) => {
      return appRequest<PagedModelPageTenantUserRes>(
      {url: `/api/admin/members/pageTenantUser`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: pageTenantUserReq
    },
      options);
    }
  /**
 * @summary 查询租户用户列表接口
 */
const pageTenantUser1 = (
    pageTenantUserReq: BodyType<PageTenantUserReq>,
 options?: SecondParameter<typeof appRequest<PagedModelPageTenantUserRes>>,) => {
      return appRequest<PagedModelPageTenantUserRes>(
      {url: `/tenant-user/pageTenantUser`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: pageTenantUserReq
    },
      options);
    }
  /**
 * @summary 添加用户接口
 */
const addTenantUser = (
    addTenantUserReq: BodyType<AddTenantUserReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/api/admin/members/addTenantUser`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: addTenantUserReq
    },
      options);
    }
  /**
 * @summary 添加用户接口
 */
const addTenantUser1 = (
    addTenantUserReq: BodyType<AddTenantUserReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/tenant-user/addTenantUser`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: addTenantUserReq
    },
      options);
    }
  return {setTenantAdmin,setTenantAdmin1,setTenantMemberStatus,setTenantMemberStatus1,setMemberRoles,setMemberRoles1,removeTenantUser,removeTenantUser1,removeTenantAdmin,removeTenantAdmin1,pageTenantUser,pageTenantUser1,addTenantUser,addTenantUser1}};
export type SetTenantAdminResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getTenantUser>['setTenantAdmin']>>>
export type SetTenantAdmin1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getTenantUser>['setTenantAdmin1']>>>
export type SetTenantMemberStatusResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getTenantUser>['setTenantMemberStatus']>>>
export type SetTenantMemberStatus1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getTenantUser>['setTenantMemberStatus1']>>>
export type SetMemberRolesResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getTenantUser>['setMemberRoles']>>>
export type SetMemberRoles1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getTenantUser>['setMemberRoles1']>>>
export type RemoveTenantUserResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getTenantUser>['removeTenantUser']>>>
export type RemoveTenantUser1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getTenantUser>['removeTenantUser1']>>>
export type RemoveTenantAdminResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getTenantUser>['removeTenantAdmin']>>>
export type RemoveTenantAdmin1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getTenantUser>['removeTenantAdmin1']>>>
export type PageTenantUserResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getTenantUser>['pageTenantUser']>>>
export type PageTenantUser1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getTenantUser>['pageTenantUser1']>>>
export type AddTenantUserResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getTenantUser>['addTenantUser']>>>
export type AddTenantUser1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getTenantUser>['addTenantUser1']>>>
