/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * 至轻云
 * 超轻量级智能化大数据中心
 * OpenAPI spec version: 0.0.1
 */
import { appRequest } from '../../api/orval-mutator';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  export const getTestController = () => {
/**
 * @summary 本地调试
 */
const test = (

 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/test/open/test`, method: 'GET'
    },
      options);
    }
  return {test}};
export type TestResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getTestController>['test']>>>
