/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * 至轻云
 * 超轻量级智能化大数据中心
 * OpenAPI spec version: 0.0.1
 */
import type {
  DeleteInstance1Params,
  DeleteInstanceParams
} from '../models';

import { appRequest } from '../../api/orval-mutator';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  export const getVipWorkInstance = () => {
/**
 * @summary 删除作业实例接口
 */
const deleteInstance = (
    params: DeleteInstanceParams,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/vip/work-instance/deleteInstance`, method: 'GET',
        params
    },
      options);
    }
  /**
 * @summary 删除作业实例接口
 */
const deleteInstance1 = (
    params: DeleteInstance1Params,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/api/workspace/vip/work-instance/deleteInstance`, method: 'GET',
        params
    },
      options);
    }
  return {deleteInstance,deleteInstance1}};
export type DeleteInstanceResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getVipWorkInstance>['deleteInstance']>>>
export type DeleteInstance1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getVipWorkInstance>['deleteInstance1']>>>
