/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * 至轻云
 * 超轻量级智能化大数据中心
 * OpenAPI spec version: 0.0.1
 */
import type { HeaderTokenDto } from './headerTokenDto.ts';

export interface AddApiReq {
  /** @minLength 1 */
  name: string;
  /** @minLength 1 */
  apiType: string;
  /** @minLength 1 */
  path: string;
  /** @minLength 1 */
  datasourceId: string;
  /** @minLength 1 */
  tokenType: string;
  pageType: boolean;
  reqHeader?: HeaderTokenDto[];
  reqBody?: string;
  apiSql?: string;
  resBody?: string;
  remark?: string;
  accessRuleId?: string;
}
