/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * 至轻云
 * 超轻量级智能化大数据中心
 * OpenAPI spec version: 0.0.1
 */

export interface AddDataModelReq {
  /** @minLength 1 */
  name: string;
  /** @minLength 1 */
  layerId: string;
  /** @minLength 1 */
  dbType: string;
  /** @minLength 1 */
  datasourceId: string;
  /** @minLength 1 */
  tableName: string;
  /**
     * @minLength 1
     * @pattern ^(ORIGIN_MODEL|LINK_MODEL)$
     */
  modelType: string;
  tableConfig?: string;
  remark?: string;
}
