/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * 至轻云
 * 超轻量级智能化大数据中心
 * OpenAPI spec version: 0.0.1
 */

export interface AddSsoAuthReq {
  /** @minLength 1 */
  name: string;
  /** @minLength 1 */
  ssoType: string;
  /** @minLength 1 */
  clientId: string;
  /** @minLength 1 */
  clientSecret: string;
  scope?: string;
  /** @minLength 1 */
  authUrl: string;
  /** @minLength 1 */
  accessTokenUrl: string;
  /** @minLength 1 */
  redirectUrl: string;
  /** @minLength 1 */
  userUrl: string;
  /** @minLength 1 */
  authJsonPath: string;
  remark?: string;
}
