/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * 至轻云
 * 超轻量级智能化大数据中心
 * OpenAPI spec version: 0.0.1
 */

export interface AddUserReq {
  /**
     * @minLength 1
     * @maxLength 100
     */
  username: string;
  /**
     * @minLength 1
     * @maxLength 100
     */
  account: string;
  /**
     * @minLength 1
     * @maxLength 100
     */
  passwd: string;
  email?: string;
  phone?: string;
  remark?: string;
  validDateTime?: string[];
}
