/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * 至轻云
 * 超轻量级智能化大数据中心
 * OpenAPI spec version: 0.0.1
 */

export interface AddWorkReq {
  /** @minLength 1 */
  name: string;
  /**
     * @minLength 1
     * @pattern ^(SPARK_SQL|EXE_JDBC|QUERY_JDBC|DATA_SYNC_JDBC|DATA_SYNC_FLINK|BASH|PYTHON|SPARK_JAR|SPARK_CONTAINER_SQL|API|API_SYNC_JDBC|PRQL|CURL|EXCEL_SYNC_JDBC|PY_SPARK|DB_MIGRATE|FLINK_SQL|FLINK_JAR|SPARK_ETL)$
     */
  workType: string;
  /** @minLength 1 */
  workflowId: string;
  remark?: string;
  datasourceId?: string;
  clusterId?: string;
  clusterNodeId?: string;
  containerId?: string;
  enableHive?: boolean;
}
