/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * 至轻云
 * 超轻量级智能化大数据中心
 * OpenAPI spec version: 0.0.1
 */
import type { ApiSyncConfigSourceRequestHeader } from './apiSyncConfigSourceRequestHeader.ts';
import type { ApiSyncConfigTargetRequestHeader } from './apiSyncConfigTargetRequestHeader.ts';
import type { DatasourceConfig } from './datasourceConfig.ts';
import type { SyncColumnInfo } from './syncColumnInfo.ts';
import type { SyncColumnMap } from './syncColumnMap.ts';

export interface ApiSyncConfig {
  workId?: string;
  sourceType?: string;
  targetType?: string;
  sourceDBId?: string;
  sourceTable?: string;
  partitionColumn?: string;
  queryCondition?: string;
  sourceRequestType?: string;
  overMode?: string;
  sourceRequestHttp?: string;
  sourceRequestHeader?: ApiSyncConfigSourceRequestHeader;
  sourceRequestBody?: string;
  sourceResponseBody?: string;
  sourcePageSize?: number;
  sourceStartPage?: number;
  sourceEndPage?: number;
  syncAll?: boolean;
  targetDBId?: string;
  targetTable?: string;
  targetRequestType?: string;
  targetRequestHttp?: string;
  targetRequestHeader?: ApiSyncConfigTargetRequestHeader;
  targetRequestBody?: string;
  sourceTableColumn?: SyncColumnInfo[];
  targetTableColumn?: SyncColumnInfo[];
  columnMap?: SyncColumnMap[];
  jsonDataType?: string;
  nodeRootJsonPath?: string;
  targetDatabase?: DatasourceConfig;
}
