/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * 至轻云
 * 超轻量级智能化大数据中心
 * OpenAPI spec version: 0.0.1
 */
import type { DataSql } from './dataSql.ts';
import type { EchartOption } from './echartOption.ts';

export interface CardInfo {
  id?: string;
  name?: string;
  type?: string;
  datasourceId?: string;
  dataSql?: DataSql;
  webConfig?: unknown;
  exampleData?: EchartOption;
}
