/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * 至轻云
 * 超轻量级智能化大数据中心
 * OpenAPI spec version: 0.0.1
 */
import type { CheckConnectReqConnectConfig } from './checkConnectReqConnectConfig.ts';
import type { KafkaConfig } from './kafkaConfig.ts';

export interface CheckConnectReq {
  /** @minLength 1 */
  jdbcUrl: string;
  username?: string;
  passwd?: string;
  /** @minLength 1 */
  dbType: string;
  /** @minLength 1 */
  driverId: string;
  kafkaConfig?: KafkaConfig;
  connectConfig?: CheckConnectReqConnectConfig;
}
