/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * 至轻云
 * 超轻量级智能化大数据中心
 * OpenAPI spec version: 0.0.1
 */

export interface ChooseTenantRes {
  token?: string;
  refreshToken?: string;
  tenantId?: string;
  role?: string;
  systemAdmin?: boolean;
  platformAdmin?: boolean;
  tenantAdmin?: boolean;
  normalAdmin?: boolean;
  workspaceAllPermissions?: boolean;
  permissions?: string[];
  frontendPermissionCodes?: string[];
  defaultArea?: string;
}
