/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * 至轻云
 * 超轻量级智能化大数据中心
 * OpenAPI spec version: 0.0.1
 */
import type { ClusterConfigFlinkConfig } from './clusterConfigFlinkConfig.ts';
import type { ClusterConfigSparkConfig } from './clusterConfigSparkConfig.ts';

export interface ClusterConfig {
  setMode?: string;
  resourceLevel?: string;
  clusterId?: string;
  clusterNodeId?: string;
  sparkConfig?: ClusterConfigSparkConfig;
  flinkConfig?: ClusterConfigFlinkConfig;
  flinkConfigJson?: string;
  sparkConfigJson?: string;
  enableHive?: boolean;
}
