/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * 至轻云
 * 超轻量级智能化大数据中心
 * OpenAPI spec version: 0.0.1
 */

export interface ColumnFormatPageRes {
  id?: string;
  name?: string;
  columnTypeCode?: string;
  columnType?: string;
  columnRule?: string;
  remark?: string;
  status?: string;
  defaultValue?: string;
  isNull?: string;
  isDuplicate?: string;
  isPartition?: string;
  isPrimary?: string;
  createBy?: string;
  createUsername?: string;
  createDateTime?: string;
  lastModifiedDateTime?: string;
}
