/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * 至轻云
 * 超轻量级智能化大数据中心
 * OpenAPI spec version: 0.0.1
 */
import type { CronConfig } from './cronConfig.ts';

export interface ConfigWorkflowSettingReq {
  /** @minLength 1 */
  workflowId: string;
  cronConfig?: CronConfig;
  alarmList?: string[];
  /** @minLength 1 */
  invokeStatus: string;
  invokeUrl?: string;
}
