/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * 至轻云
 * 超轻量级智能化大数据中心
 * OpenAPI spec version: 0.0.1
 */

export interface CronConfig {
  setMode?: string;
  enable?: boolean;
  startDate?: string;
  hourNum?: number;
  endDate?: string;
  cron?: string;
  workDate?: string[];
  range?: string;
  startDateMin?: string;
  minNum?: number;
  endDateMin?: string;
  scheduleDate?: string;
  weekDate?: string;
  monthDay?: string;
  type?: string;
}
