/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * 至轻云
 * 超轻量级智能化大数据中心
 * OpenAPI spec version: 0.0.1
 */
import type { DatasourceConfigConnectConfig } from './datasourceConfigConnectConfig.ts';

export interface DatasourceConfig {
  driver?: string;
  url?: string;
  dbTable?: string;
  user?: string;
  password?: string;
  connectConfig?: DatasourceConfigConnectConfig;
}
