/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * 至轻云
 * 超轻量级智能化大数据中心
 * OpenAPI spec version: 0.0.1
 */
import type { DatasourceConfig } from './datasourceConfig.ts';

export interface DbMigrateConfig {
  includeTargetRule?: string;
  workId?: string;
  sourceDBType?: string;
  sourceDBId?: string;
  targetDBType?: string;
  targetDBId?: string;
  sourceDatabase?: DatasourceConfig;
  targetDatabase?: DatasourceConfig;
  syncTables?: string[];
}
