/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * 至轻云
 * 超轻量级智能化大数据中心
 * OpenAPI spec version: 0.0.1
 */
import type { EchartTextStyle } from './echartTextStyle.ts';

export interface EchartTitle {
  text?: string;
  left?: string;
  top?: string;
  textStyle?: EchartTextStyle;
  subText?: string;
}
