/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * 至轻云
 * 超轻量级智能化大数据中心
 * OpenAPI spec version: 0.0.1
 */
import type { EchartLegend } from './echartLegend.ts';
import type { EchartSeries } from './echartSeries.ts';
import type { EchartTitle } from './echartTitle.ts';
import type { EchartToolbox } from './echartToolbox.ts';
import type { EchartTooltip } from './echartTooltip.ts';
import type { EchartXAxis } from './echartXAxis.ts';
import type { EchartYAxis } from './echartYAxis.ts';

export interface EchartOption {
  title?: EchartTitle;
  tooltip?: EchartTooltip;
  toolbox?: EchartToolbox;
  legend?: EchartLegend;
  series?: EchartSeries[];
  xAxis?: EchartXAxis;
  yAxis?: EchartYAxis;
}
