/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * 至轻云
 * 超轻量级智能化大数据中心
 * OpenAPI spec version: 0.0.1
 */
import type { AddColEtl } from './addColEtl.ts';
import type { CustomSqlEtl } from './customSqlEtl.ts';
import type { EtlColumn } from './etlColumn.ts';
import type { FilterEtl } from './filterEtl.ts';
import type { InputEtl } from './inputEtl.ts';
import type { JoinEtl } from './joinEtl.ts';
import type { OutputEtl } from './outputEtl.ts';
import type { TransformEtl } from './transformEtl.ts';
import type { UnionEtl } from './unionEtl.ts';

export interface EtlNode {
  id?: string;
  name?: string;
  type?: string;
  aliaCode?: string;
  mainAliaCode?: string;
  remark?: string;
  outColumnList?: EtlColumn[];
  addColEtl?: AddColEtl[];
  customSqlEtl?: CustomSqlEtl;
  filterEtl?: FilterEtl[];
  inputEtl?: InputEtl;
  joinEtl?: JoinEtl[];
  outputEtl?: OutputEtl;
  transformEtl?: TransformEtl[];
  unionEtl?: UnionEtl[];
}
