/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * 至轻云
 * 超轻量级智能化大数据中心
 * OpenAPI spec version: 0.0.1
 */
import type { DatasourceConfig } from './datasourceConfig.ts';
import type { SyncColumnInfo } from './syncColumnInfo.ts';
import type { SyncColumnMap } from './syncColumnMap.ts';

export interface ExcelSyncConfig {
  workId?: string;
  sourceFileId?: string;
  hasHeader?: boolean;
  fileReplace?: boolean;
  filePattern?: string;
  queryCondition?: string;
  targetDBType?: string;
  targetDBId?: string;
  targetTable?: string;
  overMode?: string;
  sourceTableColumn?: SyncColumnInfo[];
  targetTableColumn?: SyncColumnInfo[];
  columnMap?: SyncColumnMap[];
  targetDatabase?: DatasourceConfig;
}
