/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * 至轻云
 * 超轻量级智能化大数据中心
 * OpenAPI spec version: 0.0.1
 */
import type { ComponentOptionDto } from './componentOptionDto.ts';
import type { SwitchOptionDto } from './switchOptionDto.ts';

export interface FormComponentDto {
  uuid?: string;
  type?: string;
  /** @minLength 1 */
  formValueCode: string;
  codeType?: string;
  label?: string;
  placeholder?: string;
  disabled?: boolean;
  fillable?: boolean;
  required?: boolean;
  isColumn?: boolean;
  width?: number;
  componentType?: string;
  valid?: boolean;
  icon?: string;
  name?: string;
  isPrimaryColumn?: boolean;
  options?: ComponentOptionDto[];
  switchInfo?: SwitchOptionDto;
  colorPicker?: string;
  dateType?: string;
}
