/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * 至轻云
 * 超轻量级智能化大数据中心
 * OpenAPI spec version: 0.0.1
 */
import type { ColumnMetaDto } from './columnMetaDto.ts';

export interface GenerateCreateTableSqlReq {
  /**
     * 来源数据源类型
     * @minLength 1
     */
  fromDbType: string;
  /**
     * 来源数据表名
     * @minLength 1
     */
  fromTableName: string;
  /** 来源数据表列表信息 */
  fromColumnList?: ColumnMetaDto[];
  /**
     * 去向数据源类型
     * @minLength 1
     */
  toDbType: string;
}
