/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * 至轻云
 * 超轻量级智能化大数据中心
 * OpenAPI spec version: 0.0.1
 */
import type { GetApiDataReqRequestHeader } from './getApiDataReqRequestHeader.ts';
import type { SyncColumnInfo } from './syncColumnInfo.ts';

export interface GetApiDataReq {
  requestType?: string;
  requestHttp?: string;
  requestHeader?: GetApiDataReqRequestHeader;
  requestBody?: string;
  responseBody?: string;
  pageSize?: number;
  startPage?: number;
  endPage?: number;
  syncAll?: boolean;
  jsonDataType?: string;
  nodeRootJsonPath?: string;
  tableColumn?: SyncColumnInfo[];
}
