/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * 至轻云
 * 超轻量级智能化大数据中心
 * OpenAPI spec version: 0.0.1
 */
import type { GetReqParamDto } from './getReqParamDto.ts';
import type { HeaderTokenDto } from './headerTokenDto.ts';

export interface GetApiRes {
  id?: string;
  name?: string;
  path?: string;
  remark?: string;
  apiType?: string;
  tokenType?: string;
  reqHeader?: HeaderTokenDto[];
  reqBody?: string;
  apiSql?: string;
  resBody?: string;
  datasourceId?: string;
  pageType?: boolean;
  reqJsonTemp?: string;
  reqGetTemp?: GetReqParamDto[];
  accessRuleId?: string;
}
