/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * 至轻云
 * 超轻量级智能化大数据中心
 * OpenAPI spec version: 0.0.1
 */

export interface GetClusterMonitorReq {
  /** @minLength 1 */
  clusterId: string;
  /**
     * @minLength 1
     * @pattern ^(THIRTY_MIN|ONE_HOUR|TWO_HOUR|SIX_HOUR|TWELVE_HOUR|ONE_DAY|SEVEN_DAY|THIRTY_DAY)$
     */
  timeType: string;
}
