/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * 至轻云
 * 超轻量级智能化大数据中心
 * OpenAPI spec version: 0.0.1
 */

export interface GetColumnLinageRes {
  lineageId?: string;
  dbId?: string;
  dbName?: string;
  dbType?: string;
  dbRemark?: string;
  tableName?: string;
  columnName?: string;
  workId?: string;
  workVersionId?: string;
  workName?: string;
  workType?: string;
  remark?: string;
  workRemark?: string;
  workflowName?: string;
  workflowRemark?: string;
  children?: GetColumnLinageRes[];
  parent?: GetColumnLinageRes[];
}
