/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * 至轻云
 * 超轻量级智能化大数据中心
 * OpenAPI spec version: 0.0.1
 */

export interface GetDefaultDatabaseDriverReq {
  /**
     * 数据源类型
     * @minLength 1
     */
  dbType: string;
}
