/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * 至轻云
 * 超轻量级智能化大数据中心
 * OpenAPI spec version: 0.0.1
 */
import type { SyncWorkConfig } from './syncWorkConfig.ts';

export interface GetRealRes {
  id?: string;
  libConfig?: string[];
  funcConfig?: string[];
  sparkConfig?: string;
  clusterId?: string;
  syncConfig?: SyncWorkConfig;
}
