/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * 至轻云
 * 超轻量级智能化大数据中心
 * OpenAPI spec version: 0.0.1
 */
import type { ApiWorkConfig } from './apiWorkConfig.ts';
import type { ClusterConfig } from './clusterConfig.ts';
import type { CronConfig } from './cronConfig.ts';
import type { DbMigrateConfig } from './dbMigrateConfig.ts';
import type { ExcelSyncConfig } from './excelSyncConfig.ts';
import type { JarJobConfig } from './jarJobConfig.ts';
import type { QueryConfig } from './queryConfig.ts';
import type { SyncRule } from './syncRule.ts';
import type { SyncWorkConfig } from './syncWorkConfig.ts';

export interface GetWorkVersionInfoRes {
  /** @minLength 1 */
  workId: string;
  datasourceId?: string;
  script?: string;
  cronConfig?: CronConfig;
  syncWorkConfig?: SyncWorkConfig;
  syncFlinkConfig?: SyncWorkConfig;
  excelSyncConfig?: ExcelSyncConfig;
  apiWorkConfig?: ApiWorkConfig;
  clusterConfig?: ClusterConfig;
  syncRule?: SyncRule;
  queryConfig?: QueryConfig;
  workType?: string;
  workflowId?: string;
  name?: string;
  jarJobConfig?: JarJobConfig;
  funcList?: string[];
  libList?: string[];
  containerId?: string;
  alarmList?: string[];
  dbMigrateConfig?: DbMigrateConfig;
}
