/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * 至轻云
 * 超轻量级智能化大数据中心
 * OpenAPI spec version: 0.0.1
 */
import type { CronConfig } from './cronConfig.ts';

export interface GetWorkflowRes {
  webConfig?: unknown;
  cronConfig?: CronConfig;
  alarmList?: string[];
  invokeStatus?: string;
  invokeUrl?: string;
}
