/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * 至轻云
 * 超轻量级智能化大数据中心
 * OpenAPI spec version: 0.0.1
 */

export interface JoinCondition {
  joinType?: string;
  joinLeftColumn?: string;
  joinCondition?: string;
  joinRightColumn?: string;
  joinValue?: string;
  joinSql?: string;
  joinAliaCode?: string;
  joinColumn?: string;
}
