/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * 至轻云
 * 超轻量级智能化大数据中心
 * OpenAPI spec version: 0.0.1
 */

export interface LoginRes {
  username?: string;
  account?: string;
  phone?: string;
  email?: string;
  remark?: string;
  token?: string;
  refreshToken?: string;
  tenantId?: string;
  role?: string;
  platformSuperAdmin?: boolean;
  platformAdmin?: boolean;
  tenantSuperAdmin?: boolean;
  tenantAdmin?: boolean;
  tenantMember?: boolean;
  workspaceAllPermissions?: boolean;
  permissions?: string[];
  defaultArea?: string;
}
