/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * 至轻云
 * 超轻量级智能化大数据中心
 * OpenAPI spec version: 0.0.1
 */
import type { EtlColumn } from './etlColumn.ts';

export interface OutputEtl {
  dbType?: string;
  datasourceId?: string;
  tableName?: string;
  writeMode?: string;
  colMapping?: string[][];
  fromColumnList?: EtlColumn[];
  toColumnList?: EtlColumn[];
}
