/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * 至轻云
 * 超轻量级智能化大数据中心
 * OpenAPI spec version: 0.0.1
 */
import type { PageMetadata } from './pageMetadata.ts';
import type { PageMetaWorkRes } from './pageMetaWorkRes.ts';

export interface PagedModelPageMetaWorkRes {
  content?: PageMetaWorkRes[];
  page?: PageMetadata;
}
