/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * 至轻云
 * 超轻量级智能化大数据中心
 * OpenAPI spec version: 0.0.1
 */

export interface PageWorkRes {
  remark?: string;
  name?: string;
  id?: string;
  workType?: string;
  createDateTime?: string;
  status?: string;
  corn?: string;
  datasourceId?: string;
  clusterId?: string;
  clusterNodeId?: string;
  enableHive?: boolean;
  configId?: string;
}
