/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * 至轻云
 * 超轻量级智能化大数据中心
 * OpenAPI spec version: 0.0.1
 */
import type { PageMetadata } from './pageMetadata.ts';
import type { QueryNodeRes } from './queryNodeRes.ts';

export interface PagedModelQueryNodeRes {
  content?: QueryNodeRes[];
  page?: PageMetadata;
}
