/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * 至轻云
 * 超轻量级智能化大数据中心
 * OpenAPI spec version: 0.0.1
 */
import type { PageDatabaseDriverRes } from './pageDatabaseDriverRes.ts';
import type { PageMetadata } from './pageMetadata.ts';

export interface PagedModelPageDatabaseDriverRes {
  content?: PageDatabaseDriverRes[];
  page?: PageMetadata;
}
