/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * 至轻云
 * 超轻量级智能化大数据中心
 * OpenAPI spec version: 0.0.1
 */

export interface PageClusterRes {
  id?: string;
  name?: string;
  node?: string;
  storage?: string;
  memory?: string;
  checkDateTime?: string;
  status?: string;
  remark?: string;
  clusterType?: string;
  defaultCluster?: boolean;
}
