/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * 至轻云
 * 超轻量级智能化大数据中心
 * OpenAPI spec version: 0.0.1
 */
import type { KafkaConfig } from './kafkaConfig.ts';
import type { PageDatasourceResConnectConfig } from './pageDatasourceResConnectConfig.ts';

export interface PageDatasourceRes {
  name?: string;
  id?: string;
  jdbcUrl?: string;
  username?: string;
  remark?: string;
  status?: string;
  checkDateTime?: string;
  dbType?: string;
  connectLog?: string;
  driverId?: string;
  driverName?: string;
  metastoreUris?: string;
  feNodes?: string;
  kafkaConfigStr?: string;
  kafkaConfig?: KafkaConfig;
  connectConfig?: PageDatasourceResConnectConfig;
  connectConfigStr?: string;
}
