/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * 至轻云
 * 超轻量级智能化大数据中心
 * OpenAPI spec version: 0.0.1
 */

export interface PageMetaDatabaseRes {
  datasourceId?: string;
  name?: string;
  dbName?: string;
  dbType?: string;
  dbComment?: string;
  status?: string;
  createDateTime?: string;
  lastModifiedDateTime?: string;
}
