/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * 至轻云
 * 超轻量级智能化大数据中心
 * OpenAPI spec version: 0.0.1
 */

export interface PageWorkflowRes {
  id?: string;
  name?: string;
  remark?: string;
  status?: string;
  defaultClusterId?: string;
  clusterName?: string;
  nextDateTime?: string;
  createDateTime?: string;
  createBy?: string;
  createUsername?: string;
}
