/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * 至轻云
 * 超轻量级智能化大数据中心
 * OpenAPI spec version: 0.0.1
 */

export interface PageAlarmInstanceRes {
  id?: string;
  alarmId?: string;
  alarmName?: string;
  sendStatus?: string;
  alarmType?: string;
  alarmEvent?: string;
  msgId?: string;
  msgName?: string;
  content?: string;
  receiver?: string;
  receiverUsername?: string;
  sendDateTime?: string;
  instanceId?: string;
  response?: string;
}
