/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * 至轻云
 * 超轻量级智能化大数据中心
 * OpenAPI spec version: 0.0.1
 */

export interface PageFuncRes {
  id?: string;
  type?: string;
  fileId?: string;
  funcName?: string;
  className?: string;
  resultType?: string;
  remark?: string;
  fileName?: string;
  createDateTime?: string;
  lastModifiedDateTime?: string;
}
