/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * 至轻云
 * 超轻量级智能化大数据中心
 * OpenAPI spec version: 0.0.1
 */
import type { UserInfo } from './userInfo.ts';

export interface PageAlarmRes {
  id?: string;
  name?: string;
  remark?: string;
  msgId?: string;
  msgName?: string;
  alarmType?: string;
  alarmEvent?: string;
  status?: string;
  alarmTemplate?: string;
  createDateTime?: string;
  createBy?: string;
  createByUsername?: string;
  receiverList?: string;
  receiverUsers?: UserInfo[];
}
