/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * 至轻云
 * 超轻量级智能化大数据中心
 * OpenAPI spec version: 0.0.1
 */
import type { PageMessageRes } from './pageMessageRes.ts';
import type { PageMetadata } from './pageMetadata.ts';

export interface PagedModelPageMessageRes {
  content?: PageMessageRes[];
  page?: PageMetadata;
}
