/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * 至轻云
 * 超轻量级智能化大数据中心
 * OpenAPI spec version: 0.0.1
 */

export interface PageTenantRes {
  id?: string;
  name?: string;
  usedMemberNum?: string;
  maxMemberNum?: string;
  usedWorkflowNum?: string;
  maxWorkflowNum?: string;
  remark?: string;
  status?: string;
  adminUserId?: string;
  checkDateTime?: string;
  validStartDateTime?: string;
  validEndDateTime?: string;
}
