/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * 至轻云
 * 超轻量级智能化大数据中心
 * OpenAPI spec version: 0.0.1
 */
import type { CronConfig } from './cronConfig.ts';

export interface PageMetaWorkRes {
  id?: string;
  name?: string;
  datasourceName?: string;
  datasourceId?: string;
  status?: string;
  cronConfigStr?: string;
  tablePattern?: string;
  dbType?: string;
  collectType?: string;
  cronConfig?: CronConfig;
  nextStartTime?: string;
  createDateTime?: string;
}
