/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * 至轻云
 * 超轻量级智能化大数据中心
 * OpenAPI spec version: 0.0.1
 */

export interface PageDatabaseDriverRes {
  id?: string;
  name?: string;
  dbType?: string;
  fileName?: string;
  driverType?: string;
  remark?: string;
  isDefaultDriver?: boolean;
  createBy?: string;
  createUsername?: string;
  createDateTime?: string;
}
