/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * 至轻云
 * 超轻量级智能化大数据中心
 * OpenAPI spec version: 0.0.1
 */

export interface PageMetaColumnRes {
  datasourceName?: string;
  datasourceId?: string;
  dbName?: string;
  tableName?: string;
  columnType?: string;
  columnName?: string;
  columnComment?: string;
  customComment?: string;
  lastModifiedDateTime?: string;
}
