/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * 至轻云
 * 超轻量级智能化大数据中心
 * OpenAPI spec version: 0.0.1
 */
import type { MessageConfig } from './messageConfig.ts';

export interface PageMessageRes {
  id?: string;
  name?: string;
  remark?: string;
  msgType?: string;
  status?: string;
  response?: string;
  createDateTime?: string;
  createBy?: string;
  createByUsername?: string;
  msgConfig?: string;
  messageConfig?: MessageConfig;
}
