/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * 至轻云
 * 超轻量级智能化大数据中心
 * OpenAPI spec version: 0.0.1
 */

export interface PageContainerRes {
  id?: string;
  name?: string;
  status?: string;
  clusterId?: string;
  clusterName?: string;
  resourceLevel?: string;
  datasourceId?: string;
  datasourceName?: string;
  remark?: string;
  createDateTime?: string;
  sparkConfig?: string;
}
