/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * 至轻云
 * 超轻量级智能化大数据中心
 * OpenAPI spec version: 0.0.1
 */

export interface PageViewCardRes {
  id?: string;
  name?: string;
  type?: string;
  status?: string;
  remark?: string;
  datasourceId?: string;
  datasourceName?: string;
  createBy?: string;
  createUsername?: string;
  createDateTime?: string;
}
