/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * 至轻云
 * 超轻量级智能化大数据中心
 * OpenAPI spec version: 0.0.1
 */

export interface QueryNodeRes {
  id?: string;
  name?: string;
  remark?: string;
  host?: string;
  username?: string;
  memory?: string;
  cpu?: string;
  storage?: string;
  status?: string;
  checkDateTime?: string;
  agentHomePath?: string;
  agentPort?: string;
  hadoopHomePath?: string;
  port?: string;
  agentLog?: string;
  defaultClusterNode?: boolean;
  installSparkLocal?: boolean;
  installFlinkLocal?: boolean;
}
