/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * 至轻云
 * 超轻量级智能化大数据中心
 * OpenAPI spec version: 0.0.1
 */

export interface QueryWorkFlowInstancesRes {
  workflowInstanceId?: string;
  workflowName?: string;
  startDateTime?: string;
  endDateTime?: string;
  status?: string;
  type?: string;
  duration?: number;
  nextPlanDateTime?: string;
  planStartDateTime?: string;
}
