/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * 至轻云
 * 超轻量级智能化大数据中心
 * OpenAPI spec version: 0.0.1
 */
import type { SyncColumnInfo } from './syncColumnInfo.ts';
import type { SyncColumnMap } from './syncColumnMap.ts';
import type { SyncFlinkConfigSourceTableAdvanceConfig } from './syncFlinkConfigSourceTableAdvanceConfig.ts';
import type { SyncFlinkConfigTargetTableAdvanceConfig } from './syncFlinkConfigTargetTableAdvanceConfig.ts';

export interface SyncFlinkConfig {
  workId?: string;
  sourceDBType?: string;
  sourceDBId?: string;
  sourceTable?: string;
  sourceTableAdvanceConfig?: SyncFlinkConfigSourceTableAdvanceConfig;
  queryCondition?: string;
  targetDBType?: string;
  targetDBId?: string;
  targetTable?: string;
  targetTableAdvanceConfig?: SyncFlinkConfigTargetTableAdvanceConfig;
  overMode?: string;
  sourceTableColumn?: SyncColumnInfo[];
  targetTableColumn?: SyncColumnInfo[];
  columnMap?: SyncColumnMap[];
}
