/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * 至轻云
 * 超轻量级智能化大数据中心
 * OpenAPI spec version: 0.0.1
 */
import type { TestApiReqHeaderParams } from './testApiReqHeaderParams.ts';

export interface TestApiReq {
  /** @minLength 1 */
  id: string;
  requestBody?: unknown;
  headerParams?: TestApiReqHeaderParams;
}
