/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * 至轻云
 * 超轻量级智能化大数据中心
 * OpenAPI spec version: 0.0.1
 */

export interface UpdateDatabaseDriverRemarkReq {
  /**
     * 驱动id
     * @minLength 1
     */
  id: string;
  /** 备注 */
  remark?: string;
}
