/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * 至轻云
 * 超轻量级智能化大数据中心
 * OpenAPI spec version: 0.0.1
 */

export interface UpdateColumnFormatReq {
  /** @minLength 1 */
  id: string;
  /** @minLength 1 */
  name: string;
  /** @minLength 1 */
  columnTypeCode: string;
  columnType?: string;
  columnRule?: string;
  remark?: string;
  defaultValue?: string;
  /**
     * @minLength 1
     * @pattern ^(ENABLE|DISABLE)$
     */
  isNull: string;
  /**
     * @minLength 1
     * @pattern ^(ENABLE|DISABLE)$
     */
  isDuplicate: string;
  /**
     * @minLength 1
     * @pattern ^(ENABLE|DISABLE)$
     */
  isPartition: string;
  /**
     * @minLength 1
     * @pattern ^(ENABLE|DISABLE)$
     */
  isPrimary: string;
}
