/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * 至轻云
 * 超轻量级智能化大数据中心
 * OpenAPI spec version: 0.0.1
 */

export interface UpdateUserPasswordReq {
  /** @minLength 1 */
  userId: string;
  /**
     * @minLength 1
     * @maxLength 100
     */
  newPassword: string;
  /**
     * @minLength 1
     * @maxLength 100
     */
  confirmPassword: string;
}
