/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * 至轻云
 * 超轻量级智能化大数据中心
 * OpenAPI spec version: 0.0.1
 */

export interface UpdateFuncReq {
  /** @minLength 1 */
  id: string;
  /**
     * @minLength 1
     * @pattern ^(UDF|UDAF)$
     */
  type: string;
  /** @minLength 1 */
  funcName: string;
  /** @minLength 1 */
  className: string;
  /** @minLength 1 */
  fileId: string;
  /**
     * @minLength 1
     * @pattern ^(string|int|long|double|boolean|date|timestamp)$
     */
  resultType: string;
  remark?: string;
}
