/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * 至轻云
 * 超轻量级智能化大数据中心
 * OpenAPI spec version: 0.0.1
 */

export interface UpdateClusterNodeReq {
  /** @minLength 1 */
  id: string;
  /** @minLength 1 */
  clusterId: string;
  /** @minLength 1 */
  host: string;
  /** @minLength 1 */
  port: string;
  /** @minLength 1 */
  username: string;
  /** @minLength 1 */
  passwd: string;
  remark?: string;
  /** @minLength 1 */
  name: string;
  agentHomePath?: string;
  agentPort?: string;
  hadoopHomePath?: string;
  installSparkLocal?: boolean;
  installFlinkLocal?: boolean;
  sparkHomePath?: string;
  flinkHomePath?: string;
}
