/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * 至轻云
 * 超轻量级智能化大数据中心
 * OpenAPI spec version: 0.0.1
 */
import type { UpdateDataReqNewData } from './updateDataReqNewData.ts';
import type { UpdateDataReqOldData } from './updateDataReqOldData.ts';

export interface UpdateDataReq {
  /** @minLength 1 */
  formId: string;
  oldData: UpdateDataReqOldData;
  /** @minLength 1 */
  formVersion: string;
  newData: UpdateDataReqNewData;
}
