/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * 至轻云
 * 超轻量级智能化大数据中心
 * OpenAPI spec version: 0.0.1
 */
import type { KafkaConfig } from './kafkaConfig.ts';
import type { UpdateDatasourceReqConnectConfig } from './updateDatasourceReqConnectConfig.ts';

export interface UpdateDatasourceReq {
  /** @minLength 1 */
  id: string;
  /** @minLength 1 */
  name: string;
  /** @minLength 1 */
  jdbcUrl: string;
  username?: string;
  passwd?: string;
  remark?: string;
  /** @minLength 1 */
  dbType: string;
  metastoreUris?: string;
  feNodes?: string;
  driverId?: string;
  kafkaConfig?: KafkaConfig;
  connectConfig?: UpdateDatasourceReqConnectConfig;
}
