server:
  port: 8080

spring:

  security:
    user:
      name: admin
      password: admin123

  jpa:
    database: mysql
    show-sql: false

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:30306/ispong_db
    username: root
    password: ispong123

  flyway:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:30306/ispong_db
    user: root
    password: ispong123
    locations: classpath:db/migration/mysql

logging:
  level:
    root: info
    com.isxcode.star: info
  logback:
    rollingpolicy:
      total-size-cap: 100MB
      max-history: 30
      max-file-size: 10MB

spark-yun:
  default-agent-port: 30177
  tmp-dir: /tmp
  resource-dir: /var/lib/zhiqingyun

isx-app:
  use-port: true
  use-ssl: false
  resources-path: classpath:resources