application:
  title: 至轻云
  website: https://zhiqingyun.isxcode.com
  describe: 超轻量级智能化大数据中心

server:
  tomcat:
    connection-timeout: 120s

spring:

  profiles:
    active: local

  security:
    user:
      roles: ADMIN

  main:
    banner-mode: log

  web:
    resources:
      chain:
        cache: true
        compressed: true
      cache:
        cachecontrol:
          max-age: 365d
          cache-public: true
          immutable: true

  servlet:
    multipart:
      max-file-size: 5GB
      max-request-size: 5GB
      enabled: true

  banner:
    location: classpath:logo.txt

  groovy:
    template:
      check-template-location: false

  datasource:
    druid:
      initial-size: 10
      max-active: 200
      min-idle: 10
      max-wait: 30000
      test-while-idle: true
      validation-query: select 1
      filters: stat,log4j2
      stat-view-servlet:
        enabled: true
        allow:

  jpa:
    show-sql: false
    open-in-view: false
    hibernate:
      ddl-auto: none

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: true

  quartz:
    scheduler-name: spark-yun-quartz-scheduler
    job-store-type: jdbc
    jdbc:
      initialize-schema: never
    properties:
      org.quartz.scheduler.instanceId: AUTO
      org.quartz.jobStore.isClustered: true
      org.quartz.jobStore.clusterCheckinInterval: 10000
      org.quartz.threadPool.threadCount: 50
      org.quartz.threadPool.threadPriority: 5
      org.quartz.threadPool.class: org.quartz.simpl.SimpleThreadPool
      org.quartz.jobStore.misfireThreshold: 300000 

  cache:
    type: none

  flyway:
    enabled: true

springdoc:
  api-docs:
    enabled: true
    path: /swagger-ui/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
  packages-to-scan: com.isxcode.spark

logging:
  level:
    root: info
    com.isxcode.spark: info
  exception-conversion-word: '%wEx'
  file:
    name: ./logs/spark-yun.log
  pattern:
    level: '%5p'
    dateformat: 'yyyy-MM-dd HH:mm:ss.SSS'
    console: '%clr(%d{${LOG_DATEFORMAT_PATTERN}}){faint} %clr(${LOG_LEVEL_PATTERN}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD}'
    file: '%d{${LOG_DATEFORMAT_PATTERN}} ${LOG_LEVEL_PATTERN} %-5(${PID:- }) --- [%15.15t] %-40.40logger{39} : %m%n${LOG_EXCEPTION_CONVERSION_WORD}}'
  register-shutdown-hook: false
  logback:
    rollingpolicy:
      clean-history-on-start: false
      file-name-pattern: '${LOG_FILE}.%d{yyyy-MM-dd}.%i.gz'
      total-size-cap: 100MB
      max-history: 30
      max-file-size: 10MB

jasypt:
  encryptor:
    property:
      suffix: )
      prefix: ENC(
    password: zhiqingyun

app:
  admin-role-url:
    - /swagger-ui.html
    - /swagger-ui/**
    - /v3/**
    - /h2-console/**
    - /druid/**
    - /*/developer/**
  anonymous-role-url:
    - /vip/form/getFormConfigForAnonymous
    - /vip/form/addData
  open-url:
    - /
    - /manifest.json
    - /favicon.ico
    - /robots.txt
    - /assets/**
    - /platform/**
    - /admin/**
    - /workspace/**
    - /personal-info/**
    - /403
    - /ssoauth
    - /auth
    - /share/**
    - /dashboard/**
    - /api/workspace/ai/mcp
    - /*/open/**
    - /vip/*/open/**
    - /*/api/**
  refresh-expiration-min: 10080
  app-name: app1
  nodes:
    app1 : localhost
