# 服务端口号
server:
  port: 8080

spring:

  # 配置后台服务,设置管理员账号密码
  # druid: http://localhost:8080/druid/index.html
  # h2: http://localhost:8080/h2-console
  # swagger: http://localhost:8080/swagger-ui/index.html
  security:
    user:
      name: admin
      password: admin123

  # 业务数据库的配置信息，默认使用h2数据库
  # h2驱动: org.h2.Driver
  # mysql驱动: com.mysql.cj.jdbc.Driver
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://121.89.247.94:30102/zhi_db
    username: zhi
    password: zhi123

# 应用配置
isx-app:
  resources-path: classpath:resources # 资源文件，例如许可证、驱动、头像等资源路径
  admin-passwd: admin123 # 配置至轻云后台admin账号的密码
  use-ssl: false # 是否开启ssl
  docker-mode: false # 是否采用docker部署模式