/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * 至轻云
 * 超轻量级智能化大数据中心
 * OpenAPI spec version: 0.0.1
 */
import type {
  DeleteWorkflowInstanceReq
} from '../models';

import { appRequest } from '../../api/orval-mutator';
import type { BodyType } from '../../api/orval-mutator';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  export const getVipWorkflowInstance = () => {
/**
 * @summary 删除作业流实例接口
 */
const deleteWorkflowInstance = (
    deleteWorkflowInstanceReq: BodyType<DeleteWorkflowInstanceReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/vip/workflow-instance/deleteWorkflowInstance`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: deleteWorkflowInstanceReq
    },
      options);
    }
  /**
 * @summary 删除作业流实例接口
 */
const deleteWorkflowInstance1 = (
    deleteWorkflowInstanceReq: BodyType<DeleteWorkflowInstanceReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/api/workspace/vip/workflow-instance/deleteWorkflowInstance`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: deleteWorkflowInstanceReq
    },
      options);
    }
  return {deleteWorkflowInstance,deleteWorkflowInstance1}};
export type DeleteWorkflowInstanceResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getVipWorkflowInstance>['deleteWorkflowInstance']>>>
export type DeleteWorkflowInstance1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getVipWorkflowInstance>['deleteWorkflowInstance1']>>>
