/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * 至轻云
 * 超轻量级智能化大数据中心
 * OpenAPI spec version: 0.0.1
 */
import type {
  AddDatasourceReq,
  CheckConnectReq,
  CheckConnectRes,
  DeleteDatabaseDriverReq,
  DeleteDatasourceReq,
  GenerateCreateTableSqlReq,
  GenerateCreateTableSqlRes,
  GetConnectLogReq,
  GetConnectLogRes,
  GetDefaultDatabaseDriverReq,
  GetDefaultDatabaseDriverRes,
  PageDatabaseDriverReq,
  PageDatasourceReq,
  PagedModelPageDatabaseDriverRes,
  PagedModelPageDatasourceRes,
  SettingDefaultDatabaseDriverReq,
  TestConnectRes,
  UpdateDatabaseDriverRemarkReq,
  UpdateDatasourceReq,
  UploadDatabaseDriver1Body,
  UploadDatabaseDriver1Params,
  UploadDatabaseDriverBody,
  UploadDatabaseDriverParams
} from '../models';

import { appRequest } from '../../api/orval-mutator';
import type { BodyType } from '../../api/orval-mutator';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  export const getDatasource = () => {
/**
 * @summary 上传数据源驱动接口(Swagger有Bug不能使用)
 */
const uploadDatabaseDriver = (
    params: UploadDatabaseDriverParams,
    uploadDatabaseDriverBody?: BodyType<UploadDatabaseDriverBody>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/datasource/uploadDatabaseDriver`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: uploadDatabaseDriverBody,
        params
    },
      options);
    }
  /**
 * @summary 上传数据源驱动接口(Swagger有Bug不能使用)
 */
const uploadDatabaseDriver1 = (
    params: UploadDatabaseDriver1Params,
    uploadDatabaseDriver1Body?: BodyType<UploadDatabaseDriver1Body>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/api/workspace/datasource/uploadDatabaseDriver`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: uploadDatabaseDriver1Body,
        params
    },
      options);
    }
  /**
 * @summary 更新数据源接口
 */
const updateDatasource = (
    updateDatasourceReq: BodyType<UpdateDatasourceReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/api/workspace/datasource/updateDatasource`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: updateDatasourceReq
    },
      options);
    }
  /**
 * @summary 更新数据源接口
 */
const updateDatasource1 = (
    updateDatasourceReq: BodyType<UpdateDatasourceReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/datasource/updateDatasource`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: updateDatasourceReq
    },
      options);
    }
  /**
 * @summary 修改驱动备注接口
 */
const updateDatabaseDriverRemark = (
    updateDatabaseDriverRemarkReq: BodyType<UpdateDatabaseDriverRemarkReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/datasource/updateDatabaseDriverRemark`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: updateDatabaseDriverRemarkReq
    },
      options);
    }
  /**
 * @summary 修改驱动备注接口
 */
const updateDatabaseDriverRemark1 = (
    updateDatabaseDriverRemarkReq: BodyType<UpdateDatabaseDriverRemarkReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/api/workspace/datasource/updateDatabaseDriverRemark`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: updateDatabaseDriverRemarkReq
    },
      options);
    }
  /**
 * @summary 测试数据源连接接口(列表中测试)
 */
const testConnect = (
    getConnectLogReq: BodyType<GetConnectLogReq>,
 options?: SecondParameter<typeof appRequest<TestConnectRes>>,) => {
      return appRequest<TestConnectRes>(
      {url: `/api/workspace/datasource/testConnect`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: getConnectLogReq
    },
      options);
    }
  /**
 * @summary 测试数据源连接接口(列表中测试)
 */
const testConnect1 = (
    getConnectLogReq: BodyType<GetConnectLogReq>,
 options?: SecondParameter<typeof appRequest<TestConnectRes>>,) => {
      return appRequest<TestConnectRes>(
      {url: `/datasource/testConnect`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: getConnectLogReq
    },
      options);
    }
  /**
 * @summary 设置默认驱动接口
 */
const settingDefaultDatabaseDriver = (
    settingDefaultDatabaseDriverReq: BodyType<SettingDefaultDatabaseDriverReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/api/workspace/datasource/settingDefaultDatabaseDriver`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: settingDefaultDatabaseDriverReq
    },
      options);
    }
  /**
 * @summary 设置默认驱动接口
 */
const settingDefaultDatabaseDriver1 = (
    settingDefaultDatabaseDriverReq: BodyType<SettingDefaultDatabaseDriverReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/datasource/settingDefaultDatabaseDriver`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: settingDefaultDatabaseDriverReq
    },
      options);
    }
  /**
 * @summary 查询数据源列表接口
 */
const pageDatasource = (
    pageDatasourceReq: BodyType<PageDatasourceReq>,
 options?: SecondParameter<typeof appRequest<PagedModelPageDatasourceRes>>,) => {
      return appRequest<PagedModelPageDatasourceRes>(
      {url: `/datasource/pageDatasource`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: pageDatasourceReq
    },
      options);
    }
  /**
 * @summary 查询数据源列表接口
 */
const pageDatasource1 = (
    pageDatasourceReq: BodyType<PageDatasourceReq>,
 options?: SecondParameter<typeof appRequest<PagedModelPageDatasourceRes>>,) => {
      return appRequest<PagedModelPageDatasourceRes>(
      {url: `/api/workspace/datasource/pageDatasource`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: pageDatasourceReq
    },
      options);
    }
  /**
 * @summary 查询数据库驱动接口
 */
const pageDatabaseDriver = (
    pageDatabaseDriverReq: BodyType<PageDatabaseDriverReq>,
 options?: SecondParameter<typeof appRequest<PagedModelPageDatabaseDriverRes>>,) => {
      return appRequest<PagedModelPageDatabaseDriverRes>(
      {url: `/api/workspace/datasource/pageDatabaseDriver`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: pageDatabaseDriverReq
    },
      options);
    }
  /**
 * @summary 查询数据库驱动接口
 */
const pageDatabaseDriver1 = (
    pageDatabaseDriverReq: BodyType<PageDatabaseDriverReq>,
 options?: SecondParameter<typeof appRequest<PagedModelPageDatabaseDriverRes>>,) => {
      return appRequest<PagedModelPageDatabaseDriverRes>(
      {url: `/datasource/pageDatabaseDriver`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: pageDatabaseDriverReq
    },
      options);
    }
  /**
 * @summary 获取默认驱动接口
 */
const getDefaultDatabaseDriver = (
    getDefaultDatabaseDriverReq: BodyType<GetDefaultDatabaseDriverReq>,
 options?: SecondParameter<typeof appRequest<GetDefaultDatabaseDriverRes>>,) => {
      return appRequest<GetDefaultDatabaseDriverRes>(
      {url: `/api/workspace/datasource/getDefaultDatabaseDriver`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: getDefaultDatabaseDriverReq
    },
      options);
    }
  /**
 * @summary 获取默认驱动接口
 */
const getDefaultDatabaseDriver1 = (
    getDefaultDatabaseDriverReq: BodyType<GetDefaultDatabaseDriverReq>,
 options?: SecondParameter<typeof appRequest<GetDefaultDatabaseDriverRes>>,) => {
      return appRequest<GetDefaultDatabaseDriverRes>(
      {url: `/datasource/getDefaultDatabaseDriver`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: getDefaultDatabaseDriverReq
    },
      options);
    }
  /**
 * @summary 查询连接日志接口
 */
const getConnectLog = (
    getConnectLogReq: BodyType<GetConnectLogReq>,
 options?: SecondParameter<typeof appRequest<GetConnectLogRes>>,) => {
      return appRequest<GetConnectLogRes>(
      {url: `/api/workspace/datasource/getConnectLog`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: getConnectLogReq
    },
      options);
    }
  /**
 * @summary 查询连接日志接口
 */
const getConnectLog1 = (
    getConnectLogReq: BodyType<GetConnectLogReq>,
 options?: SecondParameter<typeof appRequest<GetConnectLogRes>>,) => {
      return appRequest<GetConnectLogRes>(
      {url: `/datasource/getConnectLog`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: getConnectLogReq
    },
      options);
    }
  /**
 * @summary 一键生成目标表
 */
const generateCreateTableSql = (
    generateCreateTableSqlReq: BodyType<GenerateCreateTableSqlReq>,
 options?: SecondParameter<typeof appRequest<GenerateCreateTableSqlRes>>,) => {
      return appRequest<GenerateCreateTableSqlRes>(
      {url: `/api/workspace/datasource/generateCreateTableSql`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: generateCreateTableSqlReq
    },
      options);
    }
  /**
 * @summary 一键生成目标表
 */
const generateCreateTableSql1 = (
    generateCreateTableSqlReq: BodyType<GenerateCreateTableSqlReq>,
 options?: SecondParameter<typeof appRequest<GenerateCreateTableSqlRes>>,) => {
      return appRequest<GenerateCreateTableSqlRes>(
      {url: `/datasource/generateCreateTableSql`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: generateCreateTableSqlReq
    },
      options);
    }
  /**
 * @summary 删除数据源接口
 */
const deleteDatasource = (
    deleteDatasourceReq: BodyType<DeleteDatasourceReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/datasource/deleteDatasource`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: deleteDatasourceReq
    },
      options);
    }
  /**
 * @summary 删除数据源接口
 */
const deleteDatasource1 = (
    deleteDatasourceReq: BodyType<DeleteDatasourceReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/api/workspace/datasource/deleteDatasource`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: deleteDatasourceReq
    },
      options);
    }
  /**
 * @summary 删除数据库驱动接口
 */
const deleteDatabaseDriver = (
    deleteDatabaseDriverReq: BodyType<DeleteDatabaseDriverReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/datasource/deleteDatabaseDriver`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: deleteDatabaseDriverReq
    },
      options);
    }
  /**
 * @summary 删除数据库驱动接口
 */
const deleteDatabaseDriver1 = (
    deleteDatabaseDriverReq: BodyType<DeleteDatabaseDriverReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/api/workspace/datasource/deleteDatabaseDriver`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: deleteDatabaseDriverReq
    },
      options);
    }
  /**
 * @summary 测试数据源连接接口(弹窗中测试)
 */
const checkConnect = (
    checkConnectReq: BodyType<CheckConnectReq>,
 options?: SecondParameter<typeof appRequest<CheckConnectRes>>,) => {
      return appRequest<CheckConnectRes>(
      {url: `/api/workspace/datasource/checkConnect`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: checkConnectReq
    },
      options);
    }
  /**
 * @summary 测试数据源连接接口(弹窗中测试)
 */
const checkConnect1 = (
    checkConnectReq: BodyType<CheckConnectReq>,
 options?: SecondParameter<typeof appRequest<CheckConnectRes>>,) => {
      return appRequest<CheckConnectRes>(
      {url: `/datasource/checkConnect`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: checkConnectReq
    },
      options);
    }
  /**
 * @summary 添加数据源接口
 */
const addDatasource = (
    addDatasourceReq: BodyType<AddDatasourceReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/datasource/addDatasource`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: addDatasourceReq
    },
      options);
    }
  /**
 * @summary 添加数据源接口
 */
const addDatasource1 = (
    addDatasourceReq: BodyType<AddDatasourceReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/api/workspace/datasource/addDatasource`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: addDatasourceReq
    },
      options);
    }
  return {uploadDatabaseDriver,uploadDatabaseDriver1,updateDatasource,updateDatasource1,updateDatabaseDriverRemark,updateDatabaseDriverRemark1,testConnect,testConnect1,settingDefaultDatabaseDriver,settingDefaultDatabaseDriver1,pageDatasource,pageDatasource1,pageDatabaseDriver,pageDatabaseDriver1,getDefaultDatabaseDriver,getDefaultDatabaseDriver1,getConnectLog,getConnectLog1,generateCreateTableSql,generateCreateTableSql1,deleteDatasource,deleteDatasource1,deleteDatabaseDriver,deleteDatabaseDriver1,checkConnect,checkConnect1,addDatasource,addDatasource1}};
export type UploadDatabaseDriverResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getDatasource>['uploadDatabaseDriver']>>>
export type UploadDatabaseDriver1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getDatasource>['uploadDatabaseDriver1']>>>
export type UpdateDatasourceResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getDatasource>['updateDatasource']>>>
export type UpdateDatasource1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getDatasource>['updateDatasource1']>>>
export type UpdateDatabaseDriverRemarkResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getDatasource>['updateDatabaseDriverRemark']>>>
export type UpdateDatabaseDriverRemark1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getDatasource>['updateDatabaseDriverRemark1']>>>
export type TestConnectResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getDatasource>['testConnect']>>>
export type TestConnect1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getDatasource>['testConnect1']>>>
export type SettingDefaultDatabaseDriverResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getDatasource>['settingDefaultDatabaseDriver']>>>
export type SettingDefaultDatabaseDriver1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getDatasource>['settingDefaultDatabaseDriver1']>>>
export type PageDatasourceResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getDatasource>['pageDatasource']>>>
export type PageDatasource1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getDatasource>['pageDatasource1']>>>
export type PageDatabaseDriverResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getDatasource>['pageDatabaseDriver']>>>
export type PageDatabaseDriver1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getDatasource>['pageDatabaseDriver1']>>>
export type GetDefaultDatabaseDriverResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getDatasource>['getDefaultDatabaseDriver']>>>
export type GetDefaultDatabaseDriver1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getDatasource>['getDefaultDatabaseDriver1']>>>
export type GetConnectLogResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getDatasource>['getConnectLog']>>>
export type GetConnectLog1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getDatasource>['getConnectLog1']>>>
export type GenerateCreateTableSqlResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getDatasource>['generateCreateTableSql']>>>
export type GenerateCreateTableSql1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getDatasource>['generateCreateTableSql1']>>>
export type DeleteDatasourceResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getDatasource>['deleteDatasource']>>>
export type DeleteDatasource1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getDatasource>['deleteDatasource1']>>>
export type DeleteDatabaseDriverResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getDatasource>['deleteDatabaseDriver']>>>
export type DeleteDatabaseDriver1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getDatasource>['deleteDatabaseDriver1']>>>
export type CheckConnectResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getDatasource>['checkConnect']>>>
export type CheckConnect1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getDatasource>['checkConnect1']>>>
export type AddDatasourceResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getDatasource>['addDatasource']>>>
export type AddDatasource1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getDatasource>['addDatasource1']>>>
