/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * 至轻云
 * 超轻量级智能化大数据中心
 * OpenAPI spec version: 0.0.1
 */
import type {
  AddDataReq,
  AddFormReq,
  AddFormRes,
  DeleteDataReq,
  DeleteFormReq,
  DeployFormReq,
  GetFormConfigForAnonymousReq,
  GetFormConfigForAnonymousRes,
  GetFormConfigReq,
  GetFormConfigRes,
  GetFormLinkInfoReq,
  GetFormLinkInfoRes,
  GetFormLinkReq,
  GetFormLinkRes,
  OfflineFormReq,
  PageDataRes,
  PageFormReq,
  PagedModelFormPageRes,
  QueryDataReq,
  SaveFormConfigReq,
  UpdateDataReq,
  UpdateFormReq
} from '../models';

import { appRequest } from '../../api/orval-mutator';
import type { BodyType } from '../../api/orval-mutator';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  export const getCustomForm = () => {
/**
 * @summary 更新表单接口
 */
const updateForm = (
    updateFormReq: BodyType<UpdateFormReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/vip/form/updateForm`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: updateFormReq
    },
      options);
    }
  /**
 * @summary 更新表单接口
 */
const updateForm1 = (
    updateFormReq: BodyType<UpdateFormReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/api/workspace/vip/form/updateForm`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: updateFormReq
    },
      options);
    }
  /**
 * @summary 更新数据接口
 */
const updateData = (
    updateDataReq: BodyType<UpdateDataReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/api/workspace/vip/form/updateData`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: updateDataReq
    },
      options);
    }
  /**
 * @summary 更新数据接口
 */
const updateData1 = (
    updateDataReq: BodyType<UpdateDataReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/vip/form/updateData`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: updateDataReq
    },
      options);
    }
  /**
 * @summary 保存表单组件接口
 */
const saveFormConfig = (
    saveFormConfigReq: BodyType<SaveFormConfigReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/api/workspace/vip/form/saveFormConfig`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: saveFormConfigReq
    },
      options);
    }
  /**
 * @summary 保存表单组件接口
 */
const saveFormConfig1 = (
    saveFormConfigReq: BodyType<SaveFormConfigReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/vip/form/saveFormConfig`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: saveFormConfigReq
    },
      options);
    }
  /**
 * @summary 查询表单列表接口
 */
const pageForm = (
    pageFormReq: BodyType<PageFormReq>,
 options?: SecondParameter<typeof appRequest<PagedModelFormPageRes>>,) => {
      return appRequest<PagedModelFormPageRes>(
      {url: `/api/workspace/vip/form/pageForm`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: pageFormReq
    },
      options);
    }
  /**
 * @summary 查询表单列表接口
 */
const pageForm1 = (
    pageFormReq: BodyType<PageFormReq>,
 options?: SecondParameter<typeof appRequest<PagedModelFormPageRes>>,) => {
      return appRequest<PagedModelFormPageRes>(
      {url: `/vip/form/pageForm`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: pageFormReq
    },
      options);
    }
  /**
 * @summary 分页查询表单接口
 */
const pageData = (
    queryDataReq: BodyType<QueryDataReq>,
 options?: SecondParameter<typeof appRequest<PageDataRes>>,) => {
      return appRequest<PageDataRes>(
      {url: `/vip/form/pageData`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: queryDataReq
    },
      options);
    }
  /**
 * @summary 分页查询表单接口
 */
const pageData1 = (
    queryDataReq: BodyType<QueryDataReq>,
 options?: SecondParameter<typeof appRequest<PageDataRes>>,) => {
      return appRequest<PageDataRes>(
      {url: `/api/workspace/vip/form/pageData`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: queryDataReq
    },
      options);
    }
  /**
 * @summary 获取分享表单链接的id接口
 */
const getFormLinkInfo = (
    getFormLinkInfoReq: BodyType<GetFormLinkInfoReq>,
 options?: SecondParameter<typeof appRequest<GetFormLinkInfoRes>>,) => {
      return appRequest<GetFormLinkInfoRes>(
      {url: `/api/workspace/vip/form/open/getFormLinkInfo`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: getFormLinkInfoReq
    },
      options);
    }
  /**
 * @summary 获取分享表单链接的id接口
 */
const getFormLinkInfo1 = (
    getFormLinkInfoReq: BodyType<GetFormLinkInfoReq>,
 options?: SecondParameter<typeof appRequest<GetFormLinkInfoRes>>,) => {
      return appRequest<GetFormLinkInfoRes>(
      {url: `/vip/form/open/getFormLinkInfo`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: getFormLinkInfoReq
    },
      options);
    }
  /**
 * @summary 下线表单接口
 */
const offlineForm = (
    offlineFormReq: BodyType<OfflineFormReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/api/workspace/vip/form/offlineForm`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: offlineFormReq
    },
      options);
    }
  /**
 * @summary 下线表单接口
 */
const offlineForm1 = (
    offlineFormReq: BodyType<OfflineFormReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/vip/form/offlineForm`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: offlineFormReq
    },
      options);
    }
  /**
 * @summary 获取分享表单链接的id接口
 */
const getFormLink = (
    getFormLinkReq: BodyType<GetFormLinkReq>,
 options?: SecondParameter<typeof appRequest<GetFormLinkRes>>,) => {
      return appRequest<GetFormLinkRes>(
      {url: `/api/workspace/vip/form/getFormLink`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: getFormLinkReq
    },
      options);
    }
  /**
 * @summary 获取分享表单链接的id接口
 */
const getFormLink1 = (
    getFormLinkReq: BodyType<GetFormLinkReq>,
 options?: SecondParameter<typeof appRequest<GetFormLinkRes>>,) => {
      return appRequest<GetFormLinkRes>(
      {url: `/vip/form/getFormLink`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: getFormLinkReq
    },
      options);
    }
  /**
 * @summary 匿名者权限查询表单配置接口
 */
const getFormConfigForAnonymous = (
    getFormConfigForAnonymousReq: BodyType<GetFormConfigForAnonymousReq>,
 options?: SecondParameter<typeof appRequest<GetFormConfigForAnonymousRes>>,) => {
      return appRequest<GetFormConfigForAnonymousRes>(
      {url: `/api/workspace/vip/form/getFormConfigForAnonymous`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: getFormConfigForAnonymousReq
    },
      options);
    }
  /**
 * @summary 匿名者权限查询表单配置接口
 */
const getFormConfigForAnonymous1 = (
    getFormConfigForAnonymousReq: BodyType<GetFormConfigForAnonymousReq>,
 options?: SecondParameter<typeof appRequest<GetFormConfigForAnonymousRes>>,) => {
      return appRequest<GetFormConfigForAnonymousRes>(
      {url: `/vip/form/getFormConfigForAnonymous`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: getFormConfigForAnonymousReq
    },
      options);
    }
  /**
 * @summary 查询表单配置接口
 */
const getFormConfig = (
    getFormConfigReq: BodyType<GetFormConfigReq>,
 options?: SecondParameter<typeof appRequest<GetFormConfigRes>>,) => {
      return appRequest<GetFormConfigRes>(
      {url: `/vip/form/getFormConfig`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: getFormConfigReq
    },
      options);
    }
  /**
 * @summary 查询表单配置接口
 */
const getFormConfig1 = (
    getFormConfigReq: BodyType<GetFormConfigReq>,
 options?: SecondParameter<typeof appRequest<GetFormConfigRes>>,) => {
      return appRequest<GetFormConfigRes>(
      {url: `/api/workspace/vip/form/getFormConfig`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: getFormConfigReq
    },
      options);
    }
  /**
 * @summary 发布表单接口
 */
const deployForm = (
    deployFormReq: BodyType<DeployFormReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/api/workspace/vip/form/deployForm`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: deployFormReq
    },
      options);
    }
  /**
 * @summary 发布表单接口
 */
const deployForm1 = (
    deployFormReq: BodyType<DeployFormReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/vip/form/deployForm`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: deployFormReq
    },
      options);
    }
  /**
 * @summary 下线表单接口
 */
const deleteForm = (
    deleteFormReq: BodyType<DeleteFormReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/api/workspace/vip/form/deleteForm`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: deleteFormReq
    },
      options);
    }
  /**
 * @summary 下线表单接口
 */
const deleteForm1 = (
    deleteFormReq: BodyType<DeleteFormReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/vip/form/deleteForm`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: deleteFormReq
    },
      options);
    }
  /**
 * @summary 删除数据接口
 */
const deleteData = (
    deleteDataReq: BodyType<DeleteDataReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/api/workspace/vip/form/deleteData`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: deleteDataReq
    },
      options);
    }
  /**
 * @summary 删除数据接口
 */
const deleteData1 = (
    deleteDataReq: BodyType<DeleteDataReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/vip/form/deleteData`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: deleteDataReq
    },
      options);
    }
  /**
 * @summary 创建表单接口
 */
const addForm2 = (
    addFormReq: BodyType<AddFormReq>,
 options?: SecondParameter<typeof appRequest<AddFormRes>>,) => {
      return appRequest<AddFormRes>(
      {url: `/api/workspace/vip/form/addForm`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: addFormReq
    },
      options);
    }
  /**
 * @summary 创建表单接口
 */
const addForm3 = (
    addFormReq: BodyType<AddFormReq>,
 options?: SecondParameter<typeof appRequest<AddFormRes>>,) => {
      return appRequest<AddFormRes>(
      {url: `/vip/form/addForm`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: addFormReq
    },
      options);
    }
  /**
 * @summary 添加数据接口
 */
const addData = (
    addDataReq: BodyType<AddDataReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/vip/form/addData`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: addDataReq
    },
      options);
    }
  /**
 * @summary 添加数据接口
 */
const addData1 = (
    addDataReq: BodyType<AddDataReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/api/workspace/vip/form/addData`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: addDataReq
    },
      options);
    }
  return {updateForm,updateForm1,updateData,updateData1,saveFormConfig,saveFormConfig1,pageForm,pageForm1,pageData,pageData1,getFormLinkInfo,getFormLinkInfo1,offlineForm,offlineForm1,getFormLink,getFormLink1,getFormConfigForAnonymous,getFormConfigForAnonymous1,getFormConfig,getFormConfig1,deployForm,deployForm1,deleteForm,deleteForm1,deleteData,deleteData1,addForm2,addForm3,addData,addData1}};
export type UpdateFormResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getCustomForm>['updateForm']>>>
export type UpdateForm1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getCustomForm>['updateForm1']>>>
export type UpdateDataResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getCustomForm>['updateData']>>>
export type UpdateData1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getCustomForm>['updateData1']>>>
export type SaveFormConfigResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getCustomForm>['saveFormConfig']>>>
export type SaveFormConfig1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getCustomForm>['saveFormConfig1']>>>
export type PageFormResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getCustomForm>['pageForm']>>>
export type PageForm1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getCustomForm>['pageForm1']>>>
export type PageDataResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getCustomForm>['pageData']>>>
export type PageData1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getCustomForm>['pageData1']>>>
export type GetFormLinkInfoResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getCustomForm>['getFormLinkInfo']>>>
export type GetFormLinkInfo1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getCustomForm>['getFormLinkInfo1']>>>
export type OfflineFormResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getCustomForm>['offlineForm']>>>
export type OfflineForm1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getCustomForm>['offlineForm1']>>>
export type GetFormLinkResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getCustomForm>['getFormLink']>>>
export type GetFormLink1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getCustomForm>['getFormLink1']>>>
export type GetFormConfigForAnonymousResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getCustomForm>['getFormConfigForAnonymous']>>>
export type GetFormConfigForAnonymous1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getCustomForm>['getFormConfigForAnonymous1']>>>
export type GetFormConfigResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getCustomForm>['getFormConfig']>>>
export type GetFormConfig1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getCustomForm>['getFormConfig1']>>>
export type DeployFormResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getCustomForm>['deployForm']>>>
export type DeployForm1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getCustomForm>['deployForm1']>>>
export type DeleteFormResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getCustomForm>['deleteForm']>>>
export type DeleteForm1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getCustomForm>['deleteForm1']>>>
export type DeleteDataResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getCustomForm>['deleteData']>>>
export type DeleteData1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getCustomForm>['deleteData1']>>>
export type AddForm2Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getCustomForm>['addForm2']>>>
export type AddForm3Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getCustomForm>['addForm3']>>>
export type AddDataResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getCustomForm>['addData']>>>
export type AddData1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getCustomForm>['addData1']>>>
