/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * 至轻云
 * 超轻量级智能化大数据中心
 * OpenAPI spec version: 0.0.1
 */
import type {
  CheckLicenseRes,
  DeleteLicense1Params,
  DeleteLicenseParams,
  DisableLicense1Params,
  DisableLicenseParams,
  EnableLicense1Params,
  EnableLicenseParams,
  PagedModelQueryLicenseRes,
  QueryLicenseReq,
  UploadLicense1Body,
  UploadLicenseBody
} from '../models';

import { appRequest } from '../../api/orval-mutator';
import type { BodyType } from '../../api/orval-mutator';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  export const getLicense = () => {
/**
 * @summary 证书上传接口(Swagger有Bug不能使用)
 */
const uploadLicense = (
    uploadLicenseBody?: BodyType<UploadLicenseBody>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/api/platform/license/uploadLicense`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: uploadLicenseBody
    },
      options);
    }
  /**
 * @summary 证书上传接口(Swagger有Bug不能使用)
 */
const uploadLicense1 = (
    uploadLicense1Body?: BodyType<UploadLicense1Body>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/vip/license/uploadLicense`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: uploadLicense1Body
    },
      options);
    }
  /**
 * @summary 查询证书列表接口
 */
const queryLicense = (
    queryLicenseReq: BodyType<QueryLicenseReq>,
 options?: SecondParameter<typeof appRequest<PagedModelQueryLicenseRes>>,) => {
      return appRequest<PagedModelQueryLicenseRes>(
      {url: `/api/platform/license/queryLicense`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: queryLicenseReq
    },
      options);
    }
  /**
 * @summary 查询证书列表接口
 */
const queryLicense1 = (
    queryLicenseReq: BodyType<QueryLicenseReq>,
 options?: SecondParameter<typeof appRequest<PagedModelQueryLicenseRes>>,) => {
      return appRequest<PagedModelQueryLicenseRes>(
      {url: `/vip/license/queryLicense`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: queryLicenseReq
    },
      options);
    }
  /**
 * @summary 查询证书列表接口
 */
const checkLicense = (

 options?: SecondParameter<typeof appRequest<CheckLicenseRes>>,) => {
      return appRequest<CheckLicenseRes>(
      {url: `/vip/license/open/checkLicense`, method: 'GET'
    },
      options);
    }
  /**
 * @summary 查询证书列表接口
 */
const checkLicense1 = (

 options?: SecondParameter<typeof appRequest<CheckLicenseRes>>,) => {
      return appRequest<CheckLicenseRes>(
      {url: `/api/platform/license/open/checkLicense`, method: 'GET'
    },
      options);
    }
  /**
 * @summary 启用证书接口
 */
const enableLicense = (
    params: EnableLicenseParams,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/vip/license/enableLicense`, method: 'GET',
        params
    },
      options);
    }
  /**
 * @summary 启用证书接口
 */
const enableLicense1 = (
    params: EnableLicense1Params,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/api/platform/license/enableLicense`, method: 'GET',
        params
    },
      options);
    }
  /**
 * @summary 禁用证书接口
 */
const disableLicense = (
    params: DisableLicenseParams,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/api/platform/license/disableLicense`, method: 'GET',
        params
    },
      options);
    }
  /**
 * @summary 禁用证书接口
 */
const disableLicense1 = (
    params: DisableLicense1Params,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/vip/license/disableLicense`, method: 'GET',
        params
    },
      options);
    }
  /**
 * @summary 删除证书接口
 */
const deleteLicense = (
    params: DeleteLicenseParams,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/api/platform/license/deleteLicense`, method: 'GET',
        params
    },
      options);
    }
  /**
 * @summary 删除证书接口
 */
const deleteLicense1 = (
    params: DeleteLicense1Params,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/vip/license/deleteLicense`, method: 'GET',
        params
    },
      options);
    }
  return {uploadLicense,uploadLicense1,queryLicense,queryLicense1,checkLicense,checkLicense1,enableLicense,enableLicense1,disableLicense,disableLicense1,deleteLicense,deleteLicense1}};
export type UploadLicenseResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getLicense>['uploadLicense']>>>
export type UploadLicense1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getLicense>['uploadLicense1']>>>
export type QueryLicenseResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getLicense>['queryLicense']>>>
export type QueryLicense1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getLicense>['queryLicense1']>>>
export type CheckLicenseResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getLicense>['checkLicense']>>>
export type CheckLicense1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getLicense>['checkLicense1']>>>
export type EnableLicenseResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getLicense>['enableLicense']>>>
export type EnableLicense1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getLicense>['enableLicense1']>>>
export type DisableLicenseResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getLicense>['disableLicense']>>>
export type DisableLicense1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getLicense>['disableLicense1']>>>
export type DeleteLicenseResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getLicense>['deleteLicense']>>>
export type DeleteLicense1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getLicense>['deleteLicense1']>>>
