/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * 至轻云
 * 超轻量级智能化大数据中心
 * OpenAPI spec version: 0.0.1
 */
import type {
  DeleteRoleReq,
  PageRoleReq,
  PagedModelRoleRes,
  PermissionCatalogRes,
  RoleRes,
  SaveRoleReq
} from '../models';

import { appRequest } from '../../api/orval-mutator';
import type { BodyType } from '../../api/orval-mutator';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  export const getRolePermission = () => {
/**
 * @summary 保存角色
 */
const saveRole = (
    saveRoleReq: BodyType<SaveRoleReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/api/admin/roles/save`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: saveRoleReq
    },
      options);
    }
  /**
 * @summary 查询权限目录
 */
const permissionCatalog = (

 options?: SecondParameter<typeof appRequest<PermissionCatalogRes>>,) => {
      return appRequest<PermissionCatalogRes>(
      {url: `/api/admin/roles/permissions`, method: 'POST'
    },
      options);
    }
  /**
 * @summary 分页查询角色
 */
const pageRole = (
    pageRoleReq: BodyType<PageRoleReq>,
 options?: SecondParameter<typeof appRequest<PagedModelRoleRes>>,) => {
      return appRequest<PagedModelRoleRes>(
      {url: `/api/admin/roles/page`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: pageRoleReq
    },
      options);
    }
  /**
 * @summary 查询可用角色
 */
const listRole = (

 options?: SecondParameter<typeof appRequest<RoleRes[]>>,) => {
      return appRequest<RoleRes[]>(
      {url: `/api/admin/roles/list`, method: 'POST'
    },
      options);
    }
  /**
 * @summary 删除角色
 */
const deleteRole = (
    deleteRoleReq: BodyType<DeleteRoleReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/api/admin/roles/delete`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: deleteRoleReq
    },
      options);
    }
  return {saveRole,permissionCatalog,pageRole,listRole,deleteRole}};
export type SaveRoleResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getRolePermission>['saveRole']>>>
export type PermissionCatalogResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getRolePermission>['permissionCatalog']>>>
export type PageRoleResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getRolePermission>['pageRole']>>>
export type ListRoleResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getRolePermission>['listRole']>>>
export type DeleteRoleResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getRolePermission>['deleteRole']>>>
