/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * 至轻云
 * 超轻量级智能化大数据中心
 * OpenAPI spec version: 0.0.1
 */
import type {
  KillParams
} from '../models';

import { appRequest } from '../../api/orval-mutator';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  export const getHaController = () => {
/**
 * @summary 中止作业进程
 */
const kill = (
    params: KillParams,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/ha/kill`, method: 'GET',
        params
    },
      options);
    }
  return {kill}};
export type KillResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getHaController>['kill']>>>
