/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * 至轻云
 * 超轻量级智能化大数据中心
 * OpenAPI spec version: 0.0.1
 */
import type {
  GetClusterMonitorReq,
  GetClusterMonitorRes,
  GetInstanceMonitorReq,
  GetInstanceMonitorRes,
  GetSystemMonitorRes,
  PageInstancesReq,
  PagedModelPageInstancesRes
} from '../models';

import { appRequest } from '../../api/orval-mutator';
import type { BodyType } from '../../api/orval-mutator';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  export const getMonitor = () => {
/**
 * @summary 查询实例列表接口
 */
const pageInstances = (
    pageInstancesReq: BodyType<PageInstancesReq>,
 options?: SecondParameter<typeof appRequest<PagedModelPageInstancesRes>>,) => {
      return appRequest<PagedModelPageInstancesRes>(
      {url: `/api/workspace/monitor/pageInstances`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: pageInstancesReq
    },
      options);
    }
  /**
 * @summary 查询实例列表接口
 */
const pageInstances1 = (
    pageInstancesReq: BodyType<PageInstancesReq>,
 options?: SecondParameter<typeof appRequest<PagedModelPageInstancesRes>>,) => {
      return appRequest<PagedModelPageInstancesRes>(
      {url: `/monitor/pageInstances`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: pageInstancesReq
    },
      options);
    }
  /**
 * @summary 获取系统基础信息接口
 */
const getSystemMonitor = (

 options?: SecondParameter<typeof appRequest<GetSystemMonitorRes>>,) => {
      return appRequest<GetSystemMonitorRes>(
      {url: `/api/workspace/monitor/getSystemBaseInfo`, method: 'POST'
    },
      options);
    }
  /**
 * @summary 获取系统基础信息接口
 */
const getSystemMonitor1 = (

 options?: SecondParameter<typeof appRequest<GetSystemMonitorRes>>,) => {
      return appRequest<GetSystemMonitorRes>(
      {url: `/monitor/getSystemBaseInfo`, method: 'POST'
    },
      options);
    }
  /**
 * @summary 添加实例图接口
 */
const getInstanceMonitor = (
    getInstanceMonitorReq: BodyType<GetInstanceMonitorReq>,
 options?: SecondParameter<typeof appRequest<GetInstanceMonitorRes>>,) => {
      return appRequest<GetInstanceMonitorRes>(
      {url: `/api/workspace/monitor/getInstanceMonitor`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: getInstanceMonitorReq
    },
      options);
    }
  /**
 * @summary 添加实例图接口
 */
const getInstanceMonitor1 = (
    getInstanceMonitorReq: BodyType<GetInstanceMonitorReq>,
 options?: SecondParameter<typeof appRequest<GetInstanceMonitorRes>>,) => {
      return appRequest<GetInstanceMonitorRes>(
      {url: `/monitor/getInstanceMonitor`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: getInstanceMonitorReq
    },
      options);
    }
  /**
 * @summary 获取集群监控数据接口
 */
const getClusterMonitor = (
    getClusterMonitorReq: BodyType<GetClusterMonitorReq>,
 options?: SecondParameter<typeof appRequest<GetClusterMonitorRes>>,) => {
      return appRequest<GetClusterMonitorRes>(
      {url: `/api/workspace/monitor/getClusterMonitor`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: getClusterMonitorReq
    },
      options);
    }
  /**
 * @summary 获取集群监控数据接口
 */
const getClusterMonitor1 = (
    getClusterMonitorReq: BodyType<GetClusterMonitorReq>,
 options?: SecondParameter<typeof appRequest<GetClusterMonitorRes>>,) => {
      return appRequest<GetClusterMonitorRes>(
      {url: `/monitor/getClusterMonitor`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: getClusterMonitorReq
    },
      options);
    }
  return {pageInstances,pageInstances1,getSystemMonitor,getSystemMonitor1,getInstanceMonitor,getInstanceMonitor1,getClusterMonitor,getClusterMonitor1}};
export type PageInstancesResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getMonitor>['pageInstances']>>>
export type PageInstances1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getMonitor>['pageInstances1']>>>
export type GetSystemMonitorResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getMonitor>['getSystemMonitor']>>>
export type GetSystemMonitor1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getMonitor>['getSystemMonitor1']>>>
export type GetInstanceMonitorResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getMonitor>['getInstanceMonitor']>>>
export type GetInstanceMonitor1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getMonitor>['getInstanceMonitor1']>>>
export type GetClusterMonitorResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getMonitor>['getClusterMonitor']>>>
export type GetClusterMonitor1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getMonitor>['getClusterMonitor1']>>>
