/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * 至轻云
 * 超轻量级智能化大数据中心
 * OpenAPI spec version: 0.0.1
 */
import type {
  DeployWorkflowReq,
  GetWorkVersionInfoReq,
  GetWorkVersionInfoRes,
  KillWork1Params,
  KillWorkParams,
  KillWorkflowReq,
  ListEtlFilterCondition1200,
  ListEtlFilterCondition200,
  ListEtlTransformFunction1200,
  ListEtlTransformFunction200,
  ParseEtlCustomDataSqlReq,
  ParseEtlCustomDataSqlRes,
  PauseWork1Params,
  PauseWorkParams,
  ResumeWork1Params,
  ResumeWorkParams
} from '../models';

import { appRequest } from '../../api/orval-mutator';
import type { BodyType } from '../../api/orval-mutator';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  export const getVipWork = () => {
/**
 * @summary 解析etl中自定义节点字段
 */
const parseEtlCustomDataSql = (
    parseEtlCustomDataSqlReq: BodyType<ParseEtlCustomDataSqlReq>,
 options?: SecondParameter<typeof appRequest<ParseEtlCustomDataSqlRes>>,) => {
      return appRequest<ParseEtlCustomDataSqlRes>(
      {url: `/api/workspace/vip/work/parseEtlCustomDataSql`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: parseEtlCustomDataSqlReq
    },
      options);
    }
  /**
 * @summary 解析etl中自定义节点字段
 */
const parseEtlCustomDataSql1 = (
    parseEtlCustomDataSqlReq: BodyType<ParseEtlCustomDataSqlReq>,
 options?: SecondParameter<typeof appRequest<ParseEtlCustomDataSqlRes>>,) => {
      return appRequest<ParseEtlCustomDataSqlRes>(
      {url: `/vip/work/parseEtlCustomDataSql`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: parseEtlCustomDataSqlReq
    },
      options);
    }
  /**
 * @summary 查询etl中转换函数
 */
const listEtlTransformFunction = (

 options?: SecondParameter<typeof appRequest<ListEtlTransformFunction200>>,) => {
      return appRequest<ListEtlTransformFunction200>(
      {url: `/api/workspace/vip/work/listEtlTransformFunction`, method: 'POST'
    },
      options);
    }
  /**
 * @summary 查询etl中转换函数
 */
const listEtlTransformFunction1 = (

 options?: SecondParameter<typeof appRequest<ListEtlTransformFunction1200>>,) => {
      return appRequest<ListEtlTransformFunction1200>(
      {url: `/vip/work/listEtlTransformFunction`, method: 'POST'
    },
      options);
    }
  /**
 * @summary 查询etl中过滤条件
 */
const listEtlFilterCondition = (

 options?: SecondParameter<typeof appRequest<ListEtlFilterCondition200>>,) => {
      return appRequest<ListEtlFilterCondition200>(
      {url: `/api/workspace/vip/work/listEtlFilterCondition`, method: 'POST'
    },
      options);
    }
  /**
 * @summary 查询etl中过滤条件
 */
const listEtlFilterCondition1 = (

 options?: SecondParameter<typeof appRequest<ListEtlFilterCondition1200>>,) => {
      return appRequest<ListEtlFilterCondition1200>(
      {url: `/vip/work/listEtlFilterCondition`, method: 'POST'
    },
      options);
    }
  /**
 * @summary 下线作业流接口
 */
const killWorkflow = (
    killWorkflowReq: BodyType<KillWorkflowReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/vip/work/killWorkflow`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: killWorkflowReq
    },
      options);
    }
  /**
 * @summary 下线作业流接口
 */
const killWorkflow1 = (
    killWorkflowReq: BodyType<KillWorkflowReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/api/workspace/vip/work/killWorkflow`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: killWorkflowReq
    },
      options);
    }
  /**
 * @summary 查询作业版本信息
 */
const getWorkVersionInfo = (
    getWorkVersionInfoReq: BodyType<GetWorkVersionInfoReq>,
 options?: SecondParameter<typeof appRequest<GetWorkVersionInfoRes>>,) => {
      return appRequest<GetWorkVersionInfoRes>(
      {url: `/vip/work/getWorkVersionInfo`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: getWorkVersionInfoReq
    },
      options);
    }
  /**
 * @summary 查询作业版本信息
 */
const getWorkVersionInfo1 = (
    getWorkVersionInfoReq: BodyType<GetWorkVersionInfoReq>,
 options?: SecondParameter<typeof appRequest<GetWorkVersionInfoRes>>,) => {
      return appRequest<GetWorkVersionInfoRes>(
      {url: `/api/workspace/vip/work/getWorkVersionInfo`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: getWorkVersionInfoReq
    },
      options);
    }
  /**
 * @summary 发布作业流接口
 */
const deployWorkflow = (
    deployWorkflowReq: BodyType<DeployWorkflowReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/api/workspace/vip/work/deployWorkflow`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: deployWorkflowReq
    },
      options);
    }
  /**
 * @summary 发布作业流接口
 */
const deployWorkflow1 = (
    deployWorkflowReq: BodyType<DeployWorkflowReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/vip/work/deployWorkflow`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: deployWorkflowReq
    },
      options);
    }
  /**
 * @summary 启动作业接口
 */
const resumeWork = (
    params: ResumeWorkParams,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/vip/work/resumeWork`, method: 'GET',
        params
    },
      options);
    }
  /**
 * @summary 启动作业接口
 */
const resumeWork1 = (
    params: ResumeWork1Params,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/api/workspace/vip/work/resumeWork`, method: 'GET',
        params
    },
      options);
    }
  /**
 * @summary 暂停作业接口
 */
const pauseWork = (
    params: PauseWorkParams,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/vip/work/pauseWork`, method: 'GET',
        params
    },
      options);
    }
  /**
 * @summary 暂停作业接口
 */
const pauseWork1 = (
    params: PauseWork1Params,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/api/workspace/vip/work/pauseWork`, method: 'GET',
        params
    },
      options);
    }
  /**
 * @summary 下线作业接口
 */
const killWork = (
    params: KillWorkParams,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/vip/work/deleteWork`, method: 'GET',
        params
    },
      options);
    }
  /**
 * @summary 下线作业接口
 */
const killWork1 = (
    params: KillWork1Params,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/api/workspace/vip/work/deleteWork`, method: 'GET',
        params
    },
      options);
    }
  return {parseEtlCustomDataSql,parseEtlCustomDataSql1,listEtlTransformFunction,listEtlTransformFunction1,listEtlFilterCondition,listEtlFilterCondition1,killWorkflow,killWorkflow1,getWorkVersionInfo,getWorkVersionInfo1,deployWorkflow,deployWorkflow1,resumeWork,resumeWork1,pauseWork,pauseWork1,killWork,killWork1}};
export type ParseEtlCustomDataSqlResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getVipWork>['parseEtlCustomDataSql']>>>
export type ParseEtlCustomDataSql1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getVipWork>['parseEtlCustomDataSql1']>>>
export type ListEtlTransformFunctionResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getVipWork>['listEtlTransformFunction']>>>
export type ListEtlTransformFunction1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getVipWork>['listEtlTransformFunction1']>>>
export type ListEtlFilterConditionResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getVipWork>['listEtlFilterCondition']>>>
export type ListEtlFilterCondition1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getVipWork>['listEtlFilterCondition1']>>>
export type KillWorkflowResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getVipWork>['killWorkflow']>>>
export type KillWorkflow1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getVipWork>['killWorkflow1']>>>
export type GetWorkVersionInfoResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getVipWork>['getWorkVersionInfo']>>>
export type GetWorkVersionInfo1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getVipWork>['getWorkVersionInfo1']>>>
export type DeployWorkflowResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getVipWork>['deployWorkflow']>>>
export type DeployWorkflow1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getVipWork>['deployWorkflow1']>>>
export type ResumeWorkResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getVipWork>['resumeWork']>>>
export type ResumeWork1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getVipWork>['resumeWork1']>>>
export type PauseWorkResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getVipWork>['pauseWork']>>>
export type PauseWork1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getVipWork>['pauseWork1']>>>
export type KillWorkResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getVipWork>['killWork']>>>
export type KillWork1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getVipWork>['killWork1']>>>
