/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * 至轻云
 * 超轻量级智能化大数据中心
 * OpenAPI spec version: 0.0.1
 */
import type {
  AddAlarmReq,
  AddMessageReq,
  CheckMessageReq,
  CheckMessageRes,
  DeleteAlarmInstanceReq,
  DeleteAlarmReq,
  DeleteMessageReq,
  DisableAlarmReq,
  DisableMessageReq,
  EnableAlarmReq,
  EnableMessageReq,
  PageAlarmInstanceReq,
  PageAlarmReq,
  PageMessageReq,
  PagedModelPageAlarmInstanceRes,
  PagedModelPageAlarmRes,
  PagedModelPageMessageRes,
  UpdateAlarmReq,
  UpdateMessageReq
} from '../models';

import { appRequest } from '../../api/orval-mutator';
import type { BodyType } from '../../api/orval-mutator';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  export const getAlarm = () => {
/**
 * @summary 更新消息体接口
 */
const updateMessage = (
    updateMessageReq: BodyType<UpdateMessageReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/alarm/updateMessage`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: updateMessageReq
    },
      options);
    }
  /**
 * @summary 更新消息体接口
 */
const updateMessage1 = (
    updateMessageReq: BodyType<UpdateMessageReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/api/workspace/alarm/updateMessage`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: updateMessageReq
    },
      options);
    }
  /**
 * @summary 更新告警接口
 */
const updateAlarm = (
    updateAlarmReq: BodyType<UpdateAlarmReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/api/workspace/alarm/updateAlarm`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: updateAlarmReq
    },
      options);
    }
  /**
 * @summary 更新告警接口
 */
const updateAlarm1 = (
    updateAlarmReq: BodyType<UpdateAlarmReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/alarm/updateAlarm`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: updateAlarmReq
    },
      options);
    }
  /**
 * @summary 分页查询消息体接口
 */
const pageMessage = (
    pageMessageReq: BodyType<PageMessageReq>,
 options?: SecondParameter<typeof appRequest<PagedModelPageMessageRes>>,) => {
      return appRequest<PagedModelPageMessageRes>(
      {url: `/alarm/pageMessage`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: pageMessageReq
    },
      options);
    }
  /**
 * @summary 分页查询消息体接口
 */
const pageMessage1 = (
    pageMessageReq: BodyType<PageMessageReq>,
 options?: SecondParameter<typeof appRequest<PagedModelPageMessageRes>>,) => {
      return appRequest<PagedModelPageMessageRes>(
      {url: `/api/workspace/alarm/pageMessage`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: pageMessageReq
    },
      options);
    }
  /**
 * @summary 分页查询告警实例接口
 */
const pageAlarmInstance = (
    pageAlarmInstanceReq: BodyType<PageAlarmInstanceReq>,
 options?: SecondParameter<typeof appRequest<PagedModelPageAlarmInstanceRes>>,) => {
      return appRequest<PagedModelPageAlarmInstanceRes>(
      {url: `/alarm/pageAlarmInstance`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: pageAlarmInstanceReq
    },
      options);
    }
  /**
 * @summary 分页查询告警实例接口
 */
const pageAlarmInstance1 = (
    pageAlarmInstanceReq: BodyType<PageAlarmInstanceReq>,
 options?: SecondParameter<typeof appRequest<PagedModelPageAlarmInstanceRes>>,) => {
      return appRequest<PagedModelPageAlarmInstanceRes>(
      {url: `/api/workspace/alarm/pageAlarmInstance`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: pageAlarmInstanceReq
    },
      options);
    }
  /**
 * @summary 分页查询告警接口
 */
const pageAlarm = (
    pageAlarmReq: BodyType<PageAlarmReq>,
 options?: SecondParameter<typeof appRequest<PagedModelPageAlarmRes>>,) => {
      return appRequest<PagedModelPageAlarmRes>(
      {url: `/api/workspace/alarm/pageAlarm`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: pageAlarmReq
    },
      options);
    }
  /**
 * @summary 分页查询告警接口
 */
const pageAlarm1 = (
    pageAlarmReq: BodyType<PageAlarmReq>,
 options?: SecondParameter<typeof appRequest<PagedModelPageAlarmRes>>,) => {
      return appRequest<PagedModelPageAlarmRes>(
      {url: `/alarm/pageAlarm`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: pageAlarmReq
    },
      options);
    }
  /**
 * @summary 启动消息体接口
 */
const enableMessage = (
    enableMessageReq: BodyType<EnableMessageReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/api/workspace/alarm/enableMessage`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: enableMessageReq
    },
      options);
    }
  /**
 * @summary 启动消息体接口
 */
const enableMessage1 = (
    enableMessageReq: BodyType<EnableMessageReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/alarm/enableMessage`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: enableMessageReq
    },
      options);
    }
  /**
 * @summary 启动告警接口
 */
const enableAlarm = (
    enableAlarmReq: BodyType<EnableAlarmReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/alarm/enableAlarm`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: enableAlarmReq
    },
      options);
    }
  /**
 * @summary 启动告警接口
 */
const enableAlarm1 = (
    enableAlarmReq: BodyType<EnableAlarmReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/api/workspace/alarm/enableAlarm`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: enableAlarmReq
    },
      options);
    }
  /**
 * @summary 禁用消息体接口
 */
const disableMessage = (
    disableMessageReq: BodyType<DisableMessageReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/api/workspace/alarm/disableMessage`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: disableMessageReq
    },
      options);
    }
  /**
 * @summary 禁用消息体接口
 */
const disableMessage1 = (
    disableMessageReq: BodyType<DisableMessageReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/alarm/disableMessage`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: disableMessageReq
    },
      options);
    }
  /**
 * @summary 禁用告警接口
 */
const disableAlarm = (
    disableAlarmReq: BodyType<DisableAlarmReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/api/workspace/alarm/disableAlarm`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: disableAlarmReq
    },
      options);
    }
  /**
 * @summary 禁用告警接口
 */
const disableAlarm1 = (
    disableAlarmReq: BodyType<DisableAlarmReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/alarm/disableAlarm`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: disableAlarmReq
    },
      options);
    }
  /**
 * @summary 删除消息体接口
 */
const deleteMessage = (
    deleteMessageReq: BodyType<DeleteMessageReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/alarm/deleteMessage`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: deleteMessageReq
    },
      options);
    }
  /**
 * @summary 删除消息体接口
 */
const deleteMessage1 = (
    deleteMessageReq: BodyType<DeleteMessageReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/api/workspace/alarm/deleteMessage`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: deleteMessageReq
    },
      options);
    }
  /**
 * @summary 删除告警实例接口
 */
const deleteAlarmInstance = (
    deleteAlarmInstanceReq: BodyType<DeleteAlarmInstanceReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/api/workspace/alarm/deleteAlarmInstance`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: deleteAlarmInstanceReq
    },
      options);
    }
  /**
 * @summary 删除告警实例接口
 */
const deleteAlarmInstance1 = (
    deleteAlarmInstanceReq: BodyType<DeleteAlarmInstanceReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/alarm/deleteAlarmInstance`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: deleteAlarmInstanceReq
    },
      options);
    }
  /**
 * @summary 删除告警接口
 */
const deleteAlarm = (
    deleteAlarmReq: BodyType<DeleteAlarmReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/alarm/deleteAlarm`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: deleteAlarmReq
    },
      options);
    }
  /**
 * @summary 删除告警接口
 */
const deleteAlarm1 = (
    deleteAlarmReq: BodyType<DeleteAlarmReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/api/workspace/alarm/deleteAlarm`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: deleteAlarmReq
    },
      options);
    }
  /**
 * @summary 检测消息体接口
 */
const checkMessage = (
    checkMessageReq: BodyType<CheckMessageReq>,
 options?: SecondParameter<typeof appRequest<CheckMessageRes>>,) => {
      return appRequest<CheckMessageRes>(
      {url: `/alarm/checkMessage`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: checkMessageReq
    },
      options);
    }
  /**
 * @summary 检测消息体接口
 */
const checkMessage1 = (
    checkMessageReq: BodyType<CheckMessageReq>,
 options?: SecondParameter<typeof appRequest<CheckMessageRes>>,) => {
      return appRequest<CheckMessageRes>(
      {url: `/api/workspace/alarm/checkMessage`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: checkMessageReq
    },
      options);
    }
  /**
 * @summary 添加消息体接口
 */
const addMessage = (
    addMessageReq: BodyType<AddMessageReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/api/workspace/alarm/addMessage`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: addMessageReq
    },
      options);
    }
  /**
 * @summary 添加消息体接口
 */
const addMessage1 = (
    addMessageReq: BodyType<AddMessageReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/alarm/addMessage`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: addMessageReq
    },
      options);
    }
  /**
 * @summary 添加告警接口
 */
const addAlarm = (
    addAlarmReq: BodyType<AddAlarmReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/alarm/addAlarm`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: addAlarmReq
    },
      options);
    }
  /**
 * @summary 添加告警接口
 */
const addAlarm1 = (
    addAlarmReq: BodyType<AddAlarmReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/api/workspace/alarm/addAlarm`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: addAlarmReq
    },
      options);
    }
  return {updateMessage,updateMessage1,updateAlarm,updateAlarm1,pageMessage,pageMessage1,pageAlarmInstance,pageAlarmInstance1,pageAlarm,pageAlarm1,enableMessage,enableMessage1,enableAlarm,enableAlarm1,disableMessage,disableMessage1,disableAlarm,disableAlarm1,deleteMessage,deleteMessage1,deleteAlarmInstance,deleteAlarmInstance1,deleteAlarm,deleteAlarm1,checkMessage,checkMessage1,addMessage,addMessage1,addAlarm,addAlarm1}};
export type UpdateMessageResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAlarm>['updateMessage']>>>
export type UpdateMessage1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getAlarm>['updateMessage1']>>>
export type UpdateAlarmResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAlarm>['updateAlarm']>>>
export type UpdateAlarm1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getAlarm>['updateAlarm1']>>>
export type PageMessageResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAlarm>['pageMessage']>>>
export type PageMessage1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getAlarm>['pageMessage1']>>>
export type PageAlarmInstanceResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAlarm>['pageAlarmInstance']>>>
export type PageAlarmInstance1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getAlarm>['pageAlarmInstance1']>>>
export type PageAlarmResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAlarm>['pageAlarm']>>>
export type PageAlarm1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getAlarm>['pageAlarm1']>>>
export type EnableMessageResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAlarm>['enableMessage']>>>
export type EnableMessage1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getAlarm>['enableMessage1']>>>
export type EnableAlarmResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAlarm>['enableAlarm']>>>
export type EnableAlarm1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getAlarm>['enableAlarm1']>>>
export type DisableMessageResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAlarm>['disableMessage']>>>
export type DisableMessage1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getAlarm>['disableMessage1']>>>
export type DisableAlarmResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAlarm>['disableAlarm']>>>
export type DisableAlarm1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getAlarm>['disableAlarm1']>>>
export type DeleteMessageResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAlarm>['deleteMessage']>>>
export type DeleteMessage1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getAlarm>['deleteMessage1']>>>
export type DeleteAlarmInstanceResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAlarm>['deleteAlarmInstance']>>>
export type DeleteAlarmInstance1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getAlarm>['deleteAlarmInstance1']>>>
export type DeleteAlarmResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAlarm>['deleteAlarm']>>>
export type DeleteAlarm1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getAlarm>['deleteAlarm1']>>>
export type CheckMessageResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAlarm>['checkMessage']>>>
export type CheckMessage1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getAlarm>['checkMessage1']>>>
export type AddMessageResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAlarm>['addMessage']>>>
export type AddMessage1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getAlarm>['addMessage1']>>>
export type AddAlarmResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAlarm>['addAlarm']>>>
export type AddAlarm1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getAlarm>['addAlarm1']>>>
