/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * 至轻云
 * 超轻量级智能化大数据中心
 * OpenAPI spec version: 0.0.1
 */
import type {
  AddSsoAuthReq,
  DeleteSsoAuthReq,
  DisableSsoAuthReq,
  EnableSsoAuthReq,
  GetSsoInvokeUrlReq,
  GetSsoInvokeUrlRes,
  LoginRes,
  PageSsoAuthReq,
  PagedModelPageSsoAuthRes,
  QuerySsoAuthRes,
  SsoLoginReq,
  UpdateSsoAuthReq
} from '../models';

import { appRequest } from '../../api/orval-mutator';
import type { BodyType } from '../../api/orval-mutator';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  export const getSsoAuth = () => {
/**
 * @summary 更新单点登录配置
 */
const updateSsoAuth = (
    updateSsoAuthReq: BodyType<UpdateSsoAuthReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/vip/auth/updateSsoAuth`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: updateSsoAuthReq
    },
      options);
    }
  /**
 * @summary 更新单点登录配置
 */
const updateSsoAuth1 = (
    updateSsoAuthReq: BodyType<UpdateSsoAuthReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/api/platform/auth/updateSsoAuth`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: updateSsoAuthReq
    },
      options);
    }
  /**
 * @summary 分页查询单点登录配置接口
 */
const pageSsoAuth = (
    pageSsoAuthReq: BodyType<PageSsoAuthReq>,
 options?: SecondParameter<typeof appRequest<PagedModelPageSsoAuthRes>>,) => {
      return appRequest<PagedModelPageSsoAuthRes>(
      {url: `/api/platform/auth/pageSsoAuth`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: pageSsoAuthReq
    },
      options);
    }
  /**
 * @summary 分页查询单点登录配置接口
 */
const pageSsoAuth1 = (
    pageSsoAuthReq: BodyType<PageSsoAuthReq>,
 options?: SecondParameter<typeof appRequest<PagedModelPageSsoAuthRes>>,) => {
      return appRequest<PagedModelPageSsoAuthRes>(
      {url: `/vip/auth/pageSsoAuth`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: pageSsoAuthReq
    },
      options);
    }
  /**
 * @summary 单点认证
 */
const ssoLogin = (
    ssoLoginReq: BodyType<SsoLoginReq>,
 options?: SecondParameter<typeof appRequest<LoginRes>>,) => {
      return appRequest<LoginRes>(
      {url: `/api/platform/auth/open/ssoLogin`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: ssoLoginReq
    },
      options);
    }
  /**
 * @summary 单点认证
 */
const ssoLogin1 = (
    ssoLoginReq: BodyType<SsoLoginReq>,
 options?: SecondParameter<typeof appRequest<LoginRes>>,) => {
      return appRequest<LoginRes>(
      {url: `/vip/auth/open/ssoLogin`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: ssoLoginReq
    },
      options);
    }
  /**
 * @summary 获取单点登录列表
 */
const querySsoAuth = (

 options?: SecondParameter<typeof appRequest<QuerySsoAuthRes[]>>,) => {
      return appRequest<QuerySsoAuthRes[]>(
      {url: `/api/platform/auth/open/querySsoAuth`, method: 'POST'
    },
      options);
    }
  /**
 * @summary 获取单点登录列表
 */
const querySsoAuth1 = (

 options?: SecondParameter<typeof appRequest<QuerySsoAuthRes[]>>,) => {
      return appRequest<QuerySsoAuthRes[]>(
      {url: `/vip/auth/open/querySsoAuth`, method: 'POST'
    },
      options);
    }
  /**
 * @summary 一键复制调用接口
 */
const getSsoInvokeUrl = (
    getSsoInvokeUrlReq: BodyType<GetSsoInvokeUrlReq>,
 options?: SecondParameter<typeof appRequest<GetSsoInvokeUrlRes>>,) => {
      return appRequest<GetSsoInvokeUrlRes>(
      {url: `/vip/auth/getSsoInvokeUrl`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: getSsoInvokeUrlReq
    },
      options);
    }
  /**
 * @summary 一键复制调用接口
 */
const getSsoInvokeUrl1 = (
    getSsoInvokeUrlReq: BodyType<GetSsoInvokeUrlReq>,
 options?: SecondParameter<typeof appRequest<GetSsoInvokeUrlRes>>,) => {
      return appRequest<GetSsoInvokeUrlRes>(
      {url: `/api/platform/auth/getSsoInvokeUrl`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: getSsoInvokeUrlReq
    },
      options);
    }
  /**
 * @summary 启用单点登录接口
 */
const enableSsoAuth = (
    enableSsoAuthReq: BodyType<EnableSsoAuthReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/vip/auth/enableSsoAuth`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: enableSsoAuthReq
    },
      options);
    }
  /**
 * @summary 启用单点登录接口
 */
const enableSsoAuth1 = (
    enableSsoAuthReq: BodyType<EnableSsoAuthReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/api/platform/auth/enableSsoAuth`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: enableSsoAuthReq
    },
      options);
    }
  /**
 * @summary 禁用单点登录接口
 */
const disableSsoAuth = (
    disableSsoAuthReq: BodyType<DisableSsoAuthReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/vip/auth/disableSsoAuth`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: disableSsoAuthReq
    },
      options);
    }
  /**
 * @summary 禁用单点登录接口
 */
const disableSsoAuth1 = (
    disableSsoAuthReq: BodyType<DisableSsoAuthReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/api/platform/auth/disableSsoAuth`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: disableSsoAuthReq
    },
      options);
    }
  /**
 * @summary 删除单点登录接口
 */
const deleteSsoAuth = (
    deleteSsoAuthReq: BodyType<DeleteSsoAuthReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/vip/auth/deleteSsoAuth`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: deleteSsoAuthReq
    },
      options);
    }
  /**
 * @summary 删除单点登录接口
 */
const deleteSsoAuth1 = (
    deleteSsoAuthReq: BodyType<DeleteSsoAuthReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/api/platform/auth/deleteSsoAuth`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: deleteSsoAuthReq
    },
      options);
    }
  /**
 * @summary 创建单点登录配置
 */
const addSsoAuth = (
    addSsoAuthReq: BodyType<AddSsoAuthReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/api/platform/auth/addSsoAuth`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: addSsoAuthReq
    },
      options);
    }
  /**
 * @summary 创建单点登录配置
 */
const addSsoAuth1 = (
    addSsoAuthReq: BodyType<AddSsoAuthReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/vip/auth/addSsoAuth`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: addSsoAuthReq
    },
      options);
    }
  /**
 * @summary 单点认证
 */
const getSsoAuthCode = (

 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/api/platform/auth/open/getSsoAuthCode`, method: 'GET'
    },
      options);
    }
  /**
 * @summary 单点认证
 */
const getSsoAuthCode1 = (

 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/vip/auth/open/getSsoAuthCode`, method: 'GET'
    },
      options);
    }
  return {updateSsoAuth,updateSsoAuth1,pageSsoAuth,pageSsoAuth1,ssoLogin,ssoLogin1,querySsoAuth,querySsoAuth1,getSsoInvokeUrl,getSsoInvokeUrl1,enableSsoAuth,enableSsoAuth1,disableSsoAuth,disableSsoAuth1,deleteSsoAuth,deleteSsoAuth1,addSsoAuth,addSsoAuth1,getSsoAuthCode,getSsoAuthCode1}};
export type UpdateSsoAuthResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSsoAuth>['updateSsoAuth']>>>
export type UpdateSsoAuth1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getSsoAuth>['updateSsoAuth1']>>>
export type PageSsoAuthResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSsoAuth>['pageSsoAuth']>>>
export type PageSsoAuth1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getSsoAuth>['pageSsoAuth1']>>>
export type SsoLoginResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSsoAuth>['ssoLogin']>>>
export type SsoLogin1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getSsoAuth>['ssoLogin1']>>>
export type QuerySsoAuthResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSsoAuth>['querySsoAuth']>>>
export type QuerySsoAuth1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getSsoAuth>['querySsoAuth1']>>>
export type GetSsoInvokeUrlResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSsoAuth>['getSsoInvokeUrl']>>>
export type GetSsoInvokeUrl1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getSsoAuth>['getSsoInvokeUrl1']>>>
export type EnableSsoAuthResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSsoAuth>['enableSsoAuth']>>>
export type EnableSsoAuth1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getSsoAuth>['enableSsoAuth1']>>>
export type DisableSsoAuthResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSsoAuth>['disableSsoAuth']>>>
export type DisableSsoAuth1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getSsoAuth>['disableSsoAuth1']>>>
export type DeleteSsoAuthResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSsoAuth>['deleteSsoAuth']>>>
export type DeleteSsoAuth1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getSsoAuth>['deleteSsoAuth1']>>>
export type AddSsoAuthResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSsoAuth>['addSsoAuth']>>>
export type AddSsoAuth1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getSsoAuth>['addSsoAuth1']>>>
export type GetSsoAuthCodeResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSsoAuth>['getSsoAuthCode']>>>
export type GetSsoAuthCode1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getSsoAuth>['getSsoAuthCode1']>>>
