/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * 至轻云
 * 超轻量级智能化大数据中心
 * OpenAPI spec version: 0.0.1
 */
import type {
  DeleteOrgReq,
  OrgRes,
  SaveOrgReq
} from '../models';

import { appRequest } from '../../api/orval-mutator';
import type { BodyType } from '../../api/orval-mutator';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  export const getOrg = () => {
/**
 * @summary 保存组织
 */
const saveOrg = (
    saveOrgReq: BodyType<SaveOrgReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/api/admin/orgs/save`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: saveOrgReq
    },
      options);
    }
  /**
 * @summary 查询组织
 */
const listOrg = (

 options?: SecondParameter<typeof appRequest<OrgRes[]>>,) => {
      return appRequest<OrgRes[]>(
      {url: `/api/admin/orgs/list`, method: 'POST'
    },
      options);
    }
  /**
 * @summary 删除组织
 */
const deleteOrg = (
    deleteOrgReq: BodyType<DeleteOrgReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/api/admin/orgs/delete`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: deleteOrgReq
    },
      options);
    }
  return {saveOrg,listOrg,deleteOrg}};
export type SaveOrgResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getOrg>['saveOrg']>>>
export type ListOrgResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getOrg>['listOrg']>>>
export type DeleteOrgResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getOrg>['deleteOrg']>>>
