/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * 至轻云
 * 超轻量级智能化大数据中心
 * OpenAPI spec version: 0.0.1
 */
import type {
  AddUserReq,
  DeleteUserReq,
  DisableUserReq,
  EnableUserReq,
  GetAnonymousTokenReq,
  GetAnonymousTokenRes,
  GetUserRes,
  LoginReq,
  LoginRes,
  PageEnableUserReq,
  PageUserReq,
  PagedModelPageEnableUserRes,
  PagedModelPageUserRes,
  RefreshTokenReq,
  SetPlatformAdminReq,
  UpdateMyPasswordReq,
  UpdateUserInfoReq,
  UpdateUserPasswordReq,
  UpdateUserReq
} from '../models';

import { appRequest } from '../../api/orval-mutator';
import type { BodyType } from '../../api/orval-mutator';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  export const getUser = () => {
/**
 * @summary 修改用户密码接口
 */
const updateUserPassword = (
    updateUserPasswordReq: BodyType<UpdateUserPasswordReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/user/updateUserPassword`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: updateUserPasswordReq
    },
      options);
    }
  /**
 * @summary 修改用户密码接口
 */
const updateUserPassword1 = (
    updateUserPasswordReq: BodyType<UpdateUserPasswordReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/api/platform/users/updateUserPassword`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: updateUserPasswordReq
    },
      options);
    }
  /**
 * @summary 更新用户信息接口
 */
const updateUserInfo = (
    updateUserInfoReq: BodyType<UpdateUserInfoReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/user/updateUserInfo`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: updateUserInfoReq
    },
      options);
    }
  /**
 * @summary 更新用户信息接口
 */
const updateUserInfo1 = (
    updateUserInfoReq: BodyType<UpdateUserInfoReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/api/platform/users/updateUserInfo`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: updateUserInfoReq
    },
      options);
    }
  /**
 * @summary 更新用户接口
 */
const updateUser = (
    updateUserReq: BodyType<UpdateUserReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/api/platform/users/updateUser`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: updateUserReq
    },
      options);
    }
  /**
 * @summary 更新用户接口
 */
const updateUser1 = (
    updateUserReq: BodyType<UpdateUserReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/user/updateUser`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: updateUserReq
    },
      options);
    }
  /**
 * @summary 修改个人密码接口
 */
const updateMyPassword = (
    updateMyPasswordReq: BodyType<UpdateMyPasswordReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/user/updateMyPassword`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: updateMyPasswordReq
    },
      options);
    }
  /**
 * @summary 修改个人密码接口
 */
const updateMyPassword1 = (
    updateMyPasswordReq: BodyType<UpdateMyPasswordReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/api/platform/users/updateMyPassword`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: updateMyPasswordReq
    },
      options);
    }
  /**
 * @summary 设置平台管理员接口
 */
const setPlatformAdmin = (
    setPlatformAdminReq: BodyType<SetPlatformAdminReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/api/platform/users/setPlatformAdmin`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: setPlatformAdminReq
    },
      options);
    }
  /**
 * @summary 设置平台管理员接口
 */
const setPlatformAdmin1 = (
    setPlatformAdminReq: BodyType<SetPlatformAdminReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/user/setPlatformAdmin`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: setPlatformAdminReq
    },
      options);
    }
  /**
 * @summary 查询所有用户接口
 */
const pageUser = (
    pageUserReq: BodyType<PageUserReq>,
 options?: SecondParameter<typeof appRequest<PagedModelPageUserRes>>,) => {
      return appRequest<PagedModelPageUserRes>(
      {url: `/api/platform/users/pageUser`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: pageUserReq
    },
      options);
    }
  /**
 * @summary 查询所有用户接口
 */
const pageUser1 = (
    pageUserReq: BodyType<PageUserReq>,
 options?: SecondParameter<typeof appRequest<PagedModelPageUserRes>>,) => {
      return appRequest<PagedModelPageUserRes>(
      {url: `/user/pageUser`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: pageUserReq
    },
      options);
    }
  /**
 * @summary 查询所有启用用户接口
 */
const pageEnableUser = (
    pageEnableUserReq: BodyType<PageEnableUserReq>,
 options?: SecondParameter<typeof appRequest<PagedModelPageEnableUserRes>>,) => {
      return appRequest<PagedModelPageEnableUserRes>(
      {url: `/api/platform/users/pageEnableUser`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: pageEnableUserReq
    },
      options);
    }
  /**
 * @summary 查询所有启用用户接口
 */
const pageEnableUser1 = (
    pageEnableUserReq: BodyType<PageEnableUserReq>,
 options?: SecondParameter<typeof appRequest<PagedModelPageEnableUserRes>>,) => {
      return appRequest<PagedModelPageEnableUserRes>(
      {url: `/user/pageEnableUser`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: pageEnableUserReq
    },
      options);
    }
  /**
 * @summary 刷新token接口
 */
const refreshToken = (
    refreshTokenReq: BodyType<RefreshTokenReq>,
 options?: SecondParameter<typeof appRequest<LoginRes>>,) => {
      return appRequest<LoginRes>(
      {url: `/api/platform/users/open/refreshToken`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: refreshTokenReq
    },
      options);
    }
  /**
 * @summary 刷新token接口
 */
const refreshToken1 = (
    refreshTokenReq: BodyType<RefreshTokenReq>,
 options?: SecondParameter<typeof appRequest<LoginRes>>,) => {
      return appRequest<LoginRes>(
      {url: `/user/open/refreshToken`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: refreshTokenReq
    },
      options);
    }
  /**
 * @summary 用户登录接口
 */
const login = (
    loginReq: BodyType<LoginReq>,
 options?: SecondParameter<typeof appRequest<LoginRes>>,) => {
      return appRequest<LoginRes>(
      {url: `/user/open/login`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: loginReq
    },
      options);
    }
  /**
 * @summary 用户登录接口
 */
const login1 = (
    loginReq: BodyType<LoginReq>,
 options?: SecondParameter<typeof appRequest<LoginRes>>,) => {
      return appRequest<LoginRes>(
      {url: `/api/platform/users/open/login`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: loginReq
    },
      options);
    }
  /**
 * @summary 用户退出接口
 */
const logout = (

 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/user/logout`, method: 'POST'
    },
      options);
    }
  /**
 * @summary 用户退出接口
 */
const logout1 = (

 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/api/platform/users/logout`, method: 'POST'
    },
      options);
    }
  /**
 * @summary 获取用户信息接口
 */
const getUser = (

 options?: SecondParameter<typeof appRequest<GetUserRes>>,) => {
      return appRequest<GetUserRes>(
      {url: `/api/platform/users/getUser`, method: 'POST'
    },
      options);
    }
  /**
 * @summary 获取用户信息接口
 */
const getUser1 = (

 options?: SecondParameter<typeof appRequest<GetUserRes>>,) => {
      return appRequest<GetUserRes>(
      {url: `/user/getUser`, method: 'POST'
    },
      options);
    }
  /**
 * @summary 获取匿名者访问token接口
 */
const getAnonymousToken = (
    getAnonymousTokenReq: BodyType<GetAnonymousTokenReq>,
 options?: SecondParameter<typeof appRequest<GetAnonymousTokenRes>>,) => {
      return appRequest<GetAnonymousTokenRes>(
      {url: `/api/platform/users/getAnonymousToken`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: getAnonymousTokenReq
    },
      options);
    }
  /**
 * @summary 获取匿名者访问token接口
 */
const getAnonymousToken1 = (
    getAnonymousTokenReq: BodyType<GetAnonymousTokenReq>,
 options?: SecondParameter<typeof appRequest<GetAnonymousTokenRes>>,) => {
      return appRequest<GetAnonymousTokenRes>(
      {url: `/user/getAnonymousToken`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: getAnonymousTokenReq
    },
      options);
    }
  /**
 * @summary 启用用户接口
 */
const enableUser = (
    enableUserReq: BodyType<EnableUserReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/user/enableUser`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: enableUserReq
    },
      options);
    }
  /**
 * @summary 启用用户接口
 */
const enableUser1 = (
    enableUserReq: BodyType<EnableUserReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/api/platform/users/enableUser`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: enableUserReq
    },
      options);
    }
  /**
 * @summary 禁用用户接口
 */
const disableUser = (
    disableUserReq: BodyType<DisableUserReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/user/disableUser`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: disableUserReq
    },
      options);
    }
  /**
 * @summary 禁用用户接口
 */
const disableUser1 = (
    disableUserReq: BodyType<DisableUserReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/api/platform/users/disableUser`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: disableUserReq
    },
      options);
    }
  /**
 * @summary 删除用户接口
 */
const deleteUser = (
    deleteUserReq: BodyType<DeleteUserReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/api/platform/users/deleteUser`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: deleteUserReq
    },
      options);
    }
  /**
 * @summary 删除用户接口
 */
const deleteUser1 = (
    deleteUserReq: BodyType<DeleteUserReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/user/deleteUser`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: deleteUserReq
    },
      options);
    }
  /**
 * @summary 创建用户接口
 */
const addUser = (
    addUserReq: BodyType<AddUserReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/api/platform/users/addUser`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: addUserReq
    },
      options);
    }
  /**
 * @summary 创建用户接口
 */
const addUser1 = (
    addUserReq: BodyType<AddUserReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/user/addUser`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: addUserReq
    },
      options);
    }
  return {updateUserPassword,updateUserPassword1,updateUserInfo,updateUserInfo1,updateUser,updateUser1,updateMyPassword,updateMyPassword1,setPlatformAdmin,setPlatformAdmin1,pageUser,pageUser1,pageEnableUser,pageEnableUser1,refreshToken,refreshToken1,login,login1,logout,logout1,getUser,getUser1,getAnonymousToken,getAnonymousToken1,enableUser,enableUser1,disableUser,disableUser1,deleteUser,deleteUser1,addUser,addUser1}};
export type UpdateUserPasswordResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getUser>['updateUserPassword']>>>
export type UpdateUserPassword1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getUser>['updateUserPassword1']>>>
export type UpdateUserInfoResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getUser>['updateUserInfo']>>>
export type UpdateUserInfo1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getUser>['updateUserInfo1']>>>
export type UpdateUserResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getUser>['updateUser']>>>
export type UpdateUser1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getUser>['updateUser1']>>>
export type UpdateMyPasswordResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getUser>['updateMyPassword']>>>
export type UpdateMyPassword1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getUser>['updateMyPassword1']>>>
export type SetPlatformAdminResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getUser>['setPlatformAdmin']>>>
export type SetPlatformAdmin1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getUser>['setPlatformAdmin1']>>>
export type PageUserResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getUser>['pageUser']>>>
export type PageUser1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getUser>['pageUser1']>>>
export type PageEnableUserResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getUser>['pageEnableUser']>>>
export type PageEnableUser1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getUser>['pageEnableUser1']>>>
export type RefreshTokenResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getUser>['refreshToken']>>>
export type RefreshToken1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getUser>['refreshToken1']>>>
export type LoginResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getUser>['login']>>>
export type Login1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getUser>['login1']>>>
export type LogoutResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getUser>['logout']>>>
export type Logout1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getUser>['logout1']>>>
export type GetUserResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getUser>['getUser']>>>
export type GetUser1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getUser>['getUser1']>>>
export type GetAnonymousTokenResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getUser>['getAnonymousToken']>>>
export type GetAnonymousToken1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getUser>['getAnonymousToken1']>>>
export type EnableUserResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getUser>['enableUser']>>>
export type EnableUser1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getUser>['enableUser1']>>>
export type DisableUserResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getUser>['disableUser']>>>
export type DisableUser1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getUser>['disableUser1']>>>
export type DeleteUserResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getUser>['deleteUser']>>>
export type DeleteUser1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getUser>['deleteUser1']>>>
export type AddUserResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getUser>['addUser']>>>
export type AddUser1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getUser>['addUser1']>>>
