/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * 至轻云
 * 超轻量级智能化大数据中心
 * OpenAPI spec version: 0.0.1
 */
import type {
  GetCacheParams,
  JasyptParams,
  SetLogLevelParams
} from '../models';

import { appRequest } from '../../api/orval-mutator';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  export const getInternalTool = () => {
/**
 * @summary 获取当前版本信息接口
 */
const getLeoLastVersion = (

 options?: SecondParameter<typeof appRequest<string>>,) => {
      return appRequest<string>(
      {url: `/tools/open/version`, method: 'GET'
    },
      options);
    }
  /**
 * @summary 健康检查接口
 */
const health = (

 options?: SecondParameter<typeof appRequest<string>>,) => {
      return appRequest<string>(
      {url: `/tools/open/health`, method: 'GET'
    },
      options);
    }
  /**
 * @summary 健康检查接口
 */
const file = (
    fileName: string,
 options?: SecondParameter<typeof appRequest<Blob>>,) => {
      return appRequest<Blob>(
      {url: `/tools/open/file/${fileName}`, method: 'GET',
        responseType: 'blob'
    },
      options);
    }
  /**
 * @summary 切换系统日志等级接口
 */
const setLogLevel = (
    params: SetLogLevelParams,
 options?: SecondParameter<typeof appRequest<string>>,) => {
      return appRequest<string>(
      {url: `/tools/developer/setLogLevel`, method: 'GET',
        params
    },
      options);
    }
  /**
 * @summary jasypt加密工具接口
 */
const jasypt = (
    params: JasyptParams,
 options?: SecondParameter<typeof appRequest<string>>,) => {
      return appRequest<string>(
      {url: `/tools/developer/jasyptEncrypt`, method: 'GET',
        params
    },
      options);
    }
  /**
 * @summary 获取指定缓存信息接口
 */
const getCache = (
    params: GetCacheParams,
 options?: SecondParameter<typeof appRequest<string>>,) => {
      return appRequest<string>(
      {url: `/tools/developer/getCache`, method: 'GET',
        params
    },
      options);
    }
  /**
 * @summary 获取缓存列表接口
 */
const getCacheList = (

 options?: SecondParameter<typeof appRequest<string>>,) => {
      return appRequest<string>(
      {url: `/tools/developer/getCacheList`, method: 'GET'
    },
      options);
    }
  return {getLeoLastVersion,health,file,setLogLevel,jasypt,getCache,getCacheList}};
export type GetLeoLastVersionResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getInternalTool>['getLeoLastVersion']>>>
export type HealthResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getInternalTool>['health']>>>
export type FileResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getInternalTool>['file']>>>
export type SetLogLevelResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getInternalTool>['setLogLevel']>>>
export type JasyptResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getInternalTool>['jasypt']>>>
export type GetCacheResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getInternalTool>['getCache']>>>
export type GetCacheListResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getInternalTool>['getCacheList']>>>
