/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * 至轻云
 * 超轻量级智能化大数据中心
 * OpenAPI spec version: 0.0.1
 */
import type {
  AddRealReq,
  CheckRealReq,
  ConfigRealReq,
  DeleteRealReq,
  GetRealReq,
  GetRealRes,
  GetRealRunningLogReq,
  GetRealRunningLogRes,
  GetRealSubmitLogReq,
  GetRealSubmitLogRes,
  PageRealReq,
  PagedModelPageRealRes,
  QueryArrayPathReq,
  QueryColumnPathReq,
  QueryColumnPathRes,
  QueryTopicReq,
  StartRealReq,
  StopRealReq,
  UpdateRealReq
} from '../models';

import { appRequest } from '../../api/orval-mutator';
import type { BodyType } from '../../api/orval-mutator';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  export const getRealTimeJob = () => {
/**
 * @summary 更新实时作业接口
 */
const updateReal = (
    updateRealReq: BodyType<UpdateRealReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/vip/real/updateReal`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: updateRealReq
    },
      options);
    }
  /**
 * @summary 更新实时作业接口
 */
const updateReal1 = (
    updateRealReq: BodyType<UpdateRealReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/api/workspace/vip/real/updateReal`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: updateRealReq
    },
      options);
    }
  /**
 * @summary 停止实时作业接口
 */
const stopReal = (
    stopRealReq: BodyType<StopRealReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/api/workspace/vip/real/stopReal`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: stopRealReq
    },
      options);
    }
  /**
 * @summary 停止实时作业接口
 */
const stopReal1 = (
    stopRealReq: BodyType<StopRealReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/vip/real/stopReal`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: stopRealReq
    },
      options);
    }
  /**
 * @summary 运行实时作业接口
 */
const startReal = (
    startRealReq: BodyType<StartRealReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/api/workspace/vip/real/startReal`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: startRealReq
    },
      options);
    }
  /**
 * @summary 运行实时作业接口
 */
const startReal1 = (
    startRealReq: BodyType<StartRealReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/vip/real/startReal`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: startRealReq
    },
      options);
    }
  /**
 * @summary 查询topic列表接口
 */
const queryTopic = (
    queryTopicReq: BodyType<QueryTopicReq>,
 options?: SecondParameter<typeof appRequest<string[]>>,) => {
      return appRequest<string[]>(
      {url: `/vip/real/queryTopic`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: queryTopicReq
    },
      options);
    }
  /**
 * @summary 查询topic列表接口
 */
const queryTopic1 = (
    queryTopicReq: BodyType<QueryTopicReq>,
 options?: SecondParameter<typeof appRequest<string[]>>,) => {
      return appRequest<string[]>(
      {url: `/api/workspace/vip/real/queryTopic`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: queryTopicReq
    },
      options);
    }
  /**
 * @summary 查询json字段节点接口
 */
const queryColumnPath = (
    queryColumnPathReq: BodyType<QueryColumnPathReq>,
 options?: SecondParameter<typeof appRequest<QueryColumnPathRes[]>>,) => {
      return appRequest<QueryColumnPathRes[]>(
      {url: `/vip/real/queryColumnPath`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: queryColumnPathReq
    },
      options);
    }
  /**
 * @summary 查询json字段节点接口
 */
const queryColumnPath1 = (
    queryColumnPathReq: BodyType<QueryColumnPathReq>,
 options?: SecondParameter<typeof appRequest<QueryColumnPathRes[]>>,) => {
      return appRequest<QueryColumnPathRes[]>(
      {url: `/api/workspace/vip/real/queryColumnPath`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: queryColumnPathReq
    },
      options);
    }
  /**
 * @summary 查询json的数组节点接口
 */
const queryArrayPath = (
    queryArrayPathReq: BodyType<QueryArrayPathReq>,
 options?: SecondParameter<typeof appRequest<string[]>>,) => {
      return appRequest<string[]>(
      {url: `/api/workspace/vip/real/queryArrayPath`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: queryArrayPathReq
    },
      options);
    }
  /**
 * @summary 查询json的数组节点接口
 */
const queryArrayPath1 = (
    queryArrayPathReq: BodyType<QueryArrayPathReq>,
 options?: SecondParameter<typeof appRequest<string[]>>,) => {
      return appRequest<string[]>(
      {url: `/vip/real/queryArrayPath`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: queryArrayPathReq
    },
      options);
    }
  /**
 * @summary 分页实时作业列表接口
 */
const pageReal = (
    pageRealReq: BodyType<PageRealReq>,
 options?: SecondParameter<typeof appRequest<PagedModelPageRealRes>>,) => {
      return appRequest<PagedModelPageRealRes>(
      {url: `/api/workspace/vip/real/pageReal`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: pageRealReq
    },
      options);
    }
  /**
 * @summary 分页实时作业列表接口
 */
const pageReal1 = (
    pageRealReq: BodyType<PageRealReq>,
 options?: SecondParameter<typeof appRequest<PagedModelPageRealRes>>,) => {
      return appRequest<PagedModelPageRealRes>(
      {url: `/vip/real/pageReal`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: pageRealReq
    },
      options);
    }
  /**
 * @summary 获取实时作业提交日志接口
 */
const getRealSubmitLog = (
    getRealSubmitLogReq: BodyType<GetRealSubmitLogReq>,
 options?: SecondParameter<typeof appRequest<GetRealSubmitLogRes>>,) => {
      return appRequest<GetRealSubmitLogRes>(
      {url: `/vip/real/getRealSubmitLog`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: getRealSubmitLogReq
    },
      options);
    }
  /**
 * @summary 获取实时作业提交日志接口
 */
const getRealSubmitLog1 = (
    getRealSubmitLogReq: BodyType<GetRealSubmitLogReq>,
 options?: SecondParameter<typeof appRequest<GetRealSubmitLogRes>>,) => {
      return appRequest<GetRealSubmitLogRes>(
      {url: `/api/workspace/vip/real/getRealSubmitLog`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: getRealSubmitLogReq
    },
      options);
    }
  /**
 * @summary 获取实时作业运行日志接口
 */
const getRealRunningLog = (
    getRealRunningLogReq: BodyType<GetRealRunningLogReq>,
 options?: SecondParameter<typeof appRequest<GetRealRunningLogRes>>,) => {
      return appRequest<GetRealRunningLogRes>(
      {url: `/vip/real/getRealRunningLog`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: getRealRunningLogReq
    },
      options);
    }
  /**
 * @summary 获取实时作业运行日志接口
 */
const getRealRunningLog1 = (
    getRealRunningLogReq: BodyType<GetRealRunningLogReq>,
 options?: SecondParameter<typeof appRequest<GetRealRunningLogRes>>,) => {
      return appRequest<GetRealRunningLogRes>(
      {url: `/api/workspace/vip/real/getRealRunningLog`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: getRealRunningLogReq
    },
      options);
    }
  /**
 * @summary 获取实时作业详情接口
 */
const getReal = (
    getRealReq: BodyType<GetRealReq>,
 options?: SecondParameter<typeof appRequest<GetRealRes>>,) => {
      return appRequest<GetRealRes>(
      {url: `/vip/real/getReal`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: getRealReq
    },
      options);
    }
  /**
 * @summary 获取实时作业详情接口
 */
const getReal1 = (
    getRealReq: BodyType<GetRealReq>,
 options?: SecondParameter<typeof appRequest<GetRealRes>>,) => {
      return appRequest<GetRealRes>(
      {url: `/api/workspace/vip/real/getReal`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: getRealReq
    },
      options);
    }
  /**
 * @summary 删除实时作业接口
 */
const deleteReal = (
    deleteRealReq: BodyType<DeleteRealReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/api/workspace/vip/real/deleteReal`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: deleteRealReq
    },
      options);
    }
  /**
 * @summary 删除实时作业接口
 */
const deleteReal1 = (
    deleteRealReq: BodyType<DeleteRealReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/vip/real/deleteReal`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: deleteRealReq
    },
      options);
    }
  /**
 * @summary 配置实时作业接口
 */
const configReal = (
    configRealReq: BodyType<ConfigRealReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/api/workspace/vip/real/configReal`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: configRealReq
    },
      options);
    }
  /**
 * @summary 配置实时作业接口
 */
const configReal1 = (
    configRealReq: BodyType<ConfigRealReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/vip/real/configReal`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: configRealReq
    },
      options);
    }
  /**
 * @summary 检测实时作业接口
 */
const checkReal = (
    checkRealReq: BodyType<CheckRealReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/api/workspace/vip/real/checkReal`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: checkRealReq
    },
      options);
    }
  /**
 * @summary 检测实时作业接口
 */
const checkReal1 = (
    checkRealReq: BodyType<CheckRealReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/vip/real/checkReal`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: checkRealReq
    },
      options);
    }
  /**
 * @summary 创建实时作业接口
 */
const addReal = (
    addRealReq: BodyType<AddRealReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/api/workspace/vip/real/addReal`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: addRealReq
    },
      options);
    }
  /**
 * @summary 创建实时作业接口
 */
const addReal1 = (
    addRealReq: BodyType<AddRealReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/vip/real/addReal`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: addRealReq
    },
      options);
    }
  return {updateReal,updateReal1,stopReal,stopReal1,startReal,startReal1,queryTopic,queryTopic1,queryColumnPath,queryColumnPath1,queryArrayPath,queryArrayPath1,pageReal,pageReal1,getRealSubmitLog,getRealSubmitLog1,getRealRunningLog,getRealRunningLog1,getReal,getReal1,deleteReal,deleteReal1,configReal,configReal1,checkReal,checkReal1,addReal,addReal1}};
export type UpdateRealResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getRealTimeJob>['updateReal']>>>
export type UpdateReal1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getRealTimeJob>['updateReal1']>>>
export type StopRealResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getRealTimeJob>['stopReal']>>>
export type StopReal1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getRealTimeJob>['stopReal1']>>>
export type StartRealResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getRealTimeJob>['startReal']>>>
export type StartReal1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getRealTimeJob>['startReal1']>>>
export type QueryTopicResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getRealTimeJob>['queryTopic']>>>
export type QueryTopic1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getRealTimeJob>['queryTopic1']>>>
export type QueryColumnPathResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getRealTimeJob>['queryColumnPath']>>>
export type QueryColumnPath1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getRealTimeJob>['queryColumnPath1']>>>
export type QueryArrayPathResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getRealTimeJob>['queryArrayPath']>>>
export type QueryArrayPath1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getRealTimeJob>['queryArrayPath1']>>>
export type PageRealResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getRealTimeJob>['pageReal']>>>
export type PageReal1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getRealTimeJob>['pageReal1']>>>
export type GetRealSubmitLogResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getRealTimeJob>['getRealSubmitLog']>>>
export type GetRealSubmitLog1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getRealTimeJob>['getRealSubmitLog1']>>>
export type GetRealRunningLogResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getRealTimeJob>['getRealRunningLog']>>>
export type GetRealRunningLog1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getRealTimeJob>['getRealRunningLog1']>>>
export type GetRealResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getRealTimeJob>['getReal']>>>
export type GetReal1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getRealTimeJob>['getReal1']>>>
export type DeleteRealResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getRealTimeJob>['deleteReal']>>>
export type DeleteReal1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getRealTimeJob>['deleteReal1']>>>
export type ConfigRealResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getRealTimeJob>['configReal']>>>
export type ConfigReal1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getRealTimeJob>['configReal1']>>>
export type CheckRealResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getRealTimeJob>['checkReal']>>>
export type CheckReal1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getRealTimeJob>['checkReal1']>>>
export type AddRealResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getRealTimeJob>['addReal']>>>
export type AddReal1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getRealTimeJob>['addReal1']>>>
