/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * 至轻云
 * 超轻量级智能化大数据中心
 * OpenAPI spec version: 0.0.1
 */
import type {
  AddContainerReq,
  CheckContainerReq,
  DeleteContainerReq,
  GetContainerReq,
  GetContainerRes,
  GetContainerRunningLogReq,
  GetContainerRunningLogRes,
  PageContainerReq,
  PagedModelPageContainerRes,
  StartContainerReq,
  StopContainerReq,
  UpdateContainerReq
} from '../models';

import { appRequest } from '../../api/orval-mutator';
import type { BodyType } from '../../api/orval-mutator';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  export const getSparkContainer = () => {
/**
 * @summary 更新容器接口
 */
const updateContainer = (
    updateContainerReq: BodyType<UpdateContainerReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/api/workspace/vip/container/updateContainer`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: updateContainerReq
    },
      options);
    }
  /**
 * @summary 更新容器接口
 */
const updateContainer1 = (
    updateContainerReq: BodyType<UpdateContainerReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/vip/container/updateContainer`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: updateContainerReq
    },
      options);
    }
  /**
 * @summary 停止容器状态接口
 */
const stopContainer = (
    stopContainerReq: BodyType<StopContainerReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/api/workspace/vip/container/stopContainer`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: stopContainerReq
    },
      options);
    }
  /**
 * @summary 停止容器状态接口
 */
const stopContainer1 = (
    stopContainerReq: BodyType<StopContainerReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/vip/container/stopContainer`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: stopContainerReq
    },
      options);
    }
  /**
 * @summary 启动容器接口
 */
const startContainer = (
    startContainerReq: BodyType<StartContainerReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/vip/container/startContainer`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: startContainerReq
    },
      options);
    }
  /**
 * @summary 启动容器接口
 */
const startContainer1 = (
    startContainerReq: BodyType<StartContainerReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/api/workspace/vip/container/startContainer`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: startContainerReq
    },
      options);
    }
  /**
 * @summary 分页查询容器接口
 */
const pageContainer = (
    pageContainerReq: BodyType<PageContainerReq>,
 options?: SecondParameter<typeof appRequest<PagedModelPageContainerRes>>,) => {
      return appRequest<PagedModelPageContainerRes>(
      {url: `/api/workspace/vip/container/pageContainer`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: pageContainerReq
    },
      options);
    }
  /**
 * @summary 分页查询容器接口
 */
const pageContainer1 = (
    pageContainerReq: BodyType<PageContainerReq>,
 options?: SecondParameter<typeof appRequest<PagedModelPageContainerRes>>,) => {
      return appRequest<PagedModelPageContainerRes>(
      {url: `/vip/container/pageContainer`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: pageContainerReq
    },
      options);
    }
  /**
 * @summary 获取容器运行日志接口
 */
const getContainerRunningLog = (
    getContainerRunningLogReq: BodyType<GetContainerRunningLogReq>,
 options?: SecondParameter<typeof appRequest<GetContainerRunningLogRes>>,) => {
      return appRequest<GetContainerRunningLogRes>(
      {url: `/vip/container/getContainerRunningLog`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: getContainerRunningLogReq
    },
      options);
    }
  /**
 * @summary 获取容器运行日志接口
 */
const getContainerRunningLog1 = (
    getContainerRunningLogReq: BodyType<GetContainerRunningLogReq>,
 options?: SecondParameter<typeof appRequest<GetContainerRunningLogRes>>,) => {
      return appRequest<GetContainerRunningLogRes>(
      {url: `/api/workspace/vip/container/getContainerRunningLog`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: getContainerRunningLogReq
    },
      options);
    }
  /**
 * @summary 获取单个容器信息接口
 */
const getContainer = (
    getContainerReq: BodyType<GetContainerReq>,
 options?: SecondParameter<typeof appRequest<GetContainerRes>>,) => {
      return appRequest<GetContainerRes>(
      {url: `/api/workspace/vip/container/getContainer`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: getContainerReq
    },
      options);
    }
  /**
 * @summary 获取单个容器信息接口
 */
const getContainer1 = (
    getContainerReq: BodyType<GetContainerReq>,
 options?: SecondParameter<typeof appRequest<GetContainerRes>>,) => {
      return appRequest<GetContainerRes>(
      {url: `/vip/container/getContainer`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: getContainerReq
    },
      options);
    }
  /**
 * @summary 删除容器接口
 */
const deleteContainer = (
    deleteContainerReq: BodyType<DeleteContainerReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/vip/container/deleteContainer`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: deleteContainerReq
    },
      options);
    }
  /**
 * @summary 删除容器接口
 */
const deleteContainer1 = (
    deleteContainerReq: BodyType<DeleteContainerReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/api/workspace/vip/container/deleteContainer`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: deleteContainerReq
    },
      options);
    }
  /**
 * @summary 检测容器状态接口
 */
const checkContainer = (
    checkContainerReq: BodyType<CheckContainerReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/vip/container/checkContainer`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: checkContainerReq
    },
      options);
    }
  /**
 * @summary 检测容器状态接口
 */
const checkContainer1 = (
    checkContainerReq: BodyType<CheckContainerReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/api/workspace/vip/container/checkContainer`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: checkContainerReq
    },
      options);
    }
  /**
 * @summary 创建容器接口
 */
const addContainer = (
    addContainerReq: BodyType<AddContainerReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/vip/container/addContainer`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: addContainerReq
    },
      options);
    }
  /**
 * @summary 创建容器接口
 */
const addContainer1 = (
    addContainerReq: BodyType<AddContainerReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/api/workspace/vip/container/addContainer`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: addContainerReq
    },
      options);
    }
  return {updateContainer,updateContainer1,stopContainer,stopContainer1,startContainer,startContainer1,pageContainer,pageContainer1,getContainerRunningLog,getContainerRunningLog1,getContainer,getContainer1,deleteContainer,deleteContainer1,checkContainer,checkContainer1,addContainer,addContainer1}};
export type UpdateContainerResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSparkContainer>['updateContainer']>>>
export type UpdateContainer1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getSparkContainer>['updateContainer1']>>>
export type StopContainerResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSparkContainer>['stopContainer']>>>
export type StopContainer1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getSparkContainer>['stopContainer1']>>>
export type StartContainerResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSparkContainer>['startContainer']>>>
export type StartContainer1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getSparkContainer>['startContainer1']>>>
export type PageContainerResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSparkContainer>['pageContainer']>>>
export type PageContainer1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getSparkContainer>['pageContainer1']>>>
export type GetContainerRunningLogResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSparkContainer>['getContainerRunningLog']>>>
export type GetContainerRunningLog1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getSparkContainer>['getContainerRunningLog1']>>>
export type GetContainerResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSparkContainer>['getContainer']>>>
export type GetContainer1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getSparkContainer>['getContainer1']>>>
export type DeleteContainerResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSparkContainer>['deleteContainer']>>>
export type DeleteContainer1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getSparkContainer>['deleteContainer1']>>>
export type CheckContainerResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSparkContainer>['checkContainer']>>>
export type CheckContainer1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getSparkContainer>['checkContainer1']>>>
export type AddContainerResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSparkContainer>['addContainer']>>>
export type AddContainer1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getSparkContainer>['addContainer1']>>>
