/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * 至轻云
 * 超轻量级智能化大数据中心
 * OpenAPI spec version: 0.0.1
 */
import type {
  GetApi1200,
  GetApi200,
  GetApi2200,
  PostApi1200,
  PostApi1Body,
  PostApi200,
  PostApi2200,
  PostApi2Body,
  PostApiBody
} from '../models';

import { appRequest } from '../../api/orval-mutator';
import type { BodyType } from '../../api/orval-mutator';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  export const getCustomApi = () => {
/**
 * @summary 自定义GET接口
 */
const getApi = (
    tenantId: string,
    path1: string,
 options?: SecondParameter<typeof appRequest<GetApi200>>,) => {
      return appRequest<GetApi200>(
      {url: `/${tenantId}/api/${path1}`, method: 'GET'
    },
      options);
    }
  /**
 * @summary 自定义POST接口
 */
const postApi = (
    tenantId: string,
    path1: string,
    postApiBody?: BodyType<PostApiBody>,
 options?: SecondParameter<typeof appRequest<PostApi200>>,) => {
      return appRequest<PostApi200>(
      {url: `/${tenantId}/api/${path1}`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postApiBody
    },
      options);
    }
  /**
 * @summary 自定义GET接口
 */
const getApi1 = (
    tenantId: string,
    path1: string,
    path2: string,
 options?: SecondParameter<typeof appRequest<GetApi1200>>,) => {
      return appRequest<GetApi1200>(
      {url: `/${tenantId}/api/${path1}/${path2}`, method: 'GET'
    },
      options);
    }
  /**
 * @summary 自定义POST接口
 */
const postApi1 = (
    tenantId: string,
    path1: string,
    path2: string,
    postApi1Body?: BodyType<PostApi1Body>,
 options?: SecondParameter<typeof appRequest<PostApi1200>>,) => {
      return appRequest<PostApi1200>(
      {url: `/${tenantId}/api/${path1}/${path2}`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postApi1Body
    },
      options);
    }
  /**
 * @summary 自定义GET接口
 */
const getApi2 = (
    tenantId: string,
    path1: string,
    path2: string,
    path3: string,
 options?: SecondParameter<typeof appRequest<GetApi2200>>,) => {
      return appRequest<GetApi2200>(
      {url: `/${tenantId}/api/${path1}/${path2}/${path3}`, method: 'GET'
    },
      options);
    }
  /**
 * @summary 自定义POST接口
 */
const postApi2 = (
    tenantId: string,
    path1: string,
    path2: string,
    path3: string,
    postApi2Body?: BodyType<PostApi2Body>,
 options?: SecondParameter<typeof appRequest<PostApi2200>>,) => {
      return appRequest<PostApi2200>(
      {url: `/${tenantId}/api/${path1}/${path2}/${path3}`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postApi2Body
    },
      options);
    }
  return {getApi,postApi,getApi1,postApi1,getApi2,postApi2}};
export type GetApiResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getCustomApi>['getApi']>>>
export type PostApiResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getCustomApi>['postApi']>>>
export type GetApi1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getCustomApi>['getApi1']>>>
export type PostApi1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getCustomApi>['postApi1']>>>
export type GetApi2Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getCustomApi>['getApi2']>>>
export type PostApi2Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getCustomApi>['postApi2']>>>
