/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * 至轻云
 * 超轻量级智能化大数据中心
 * OpenAPI spec version: 0.0.1
 */
import type {
  AddColumnFormatReq,
  AddColumnFormatRes,
  AddDataModelColumnReq,
  AddDataModelReq,
  BuildDataModelReq,
  CopyDataModelReq,
  DeleteColumnFormatReq,
  DeleteDataModelReq,
  DisableColumnFormatReq,
  EnableColumnFormatReq,
  PageColumnFormatReq,
  PageDataModelByLayerReq,
  PageDataModelColumnReq,
  PageDataModelReq,
  PagedModelColumnFormatPageRes,
  PagedModelDataModelColumnPageRes,
  PagedModelDataModelPageRes,
  ResetDataModelReq,
  UpdateColumnFormatReq,
  UpdateDataModelColumnIndexReq,
  UpdateDataModelColumnReq,
  UpdateDataModelReq
} from '../models';

import { appRequest } from '../../api/orval-mutator';
import type { BodyType } from '../../api/orval-mutator';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  export const getDataModel = () => {
/**
 * @summary 更新模型字段顺序接口
 */
const updateDataModelColumnIndex = (
    updateDataModelColumnIndexReq: BodyType<UpdateDataModelColumnIndexReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/api/workspace/vip/model/updateDataModelColumnIndex`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: updateDataModelColumnIndexReq
    },
      options);
    }
  /**
 * @summary 更新模型字段顺序接口
 */
const updateDataModelColumnIndex1 = (
    updateDataModelColumnIndexReq: BodyType<UpdateDataModelColumnIndexReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/vip/model/updateDataModelColumnIndex`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: updateDataModelColumnIndexReq
    },
      options);
    }
  /**
 * @summary 更新模型字段接口
 */
const updateDataModelColumn = (
    updateDataModelColumnReq: BodyType<UpdateDataModelColumnReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/vip/model/updateDataModelColumn`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: updateDataModelColumnReq
    },
      options);
    }
  /**
 * @summary 更新模型字段接口
 */
const updateDataModelColumn1 = (
    updateDataModelColumnReq: BodyType<UpdateDataModelColumnReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/api/workspace/vip/model/updateDataModelColumn`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: updateDataModelColumnReq
    },
      options);
    }
  /**
 * @summary 更新数据模型接口
 */
const updateDataModel = (
    updateDataModelReq: BodyType<UpdateDataModelReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/api/workspace/vip/model/updateDataModel`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: updateDataModelReq
    },
      options);
    }
  /**
 * @summary 更新数据模型接口
 */
const updateDataModel1 = (
    updateDataModelReq: BodyType<UpdateDataModelReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/vip/model/updateDataModel`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: updateDataModelReq
    },
      options);
    }
  /**
 * @summary 更新字段标准接口
 */
const updateColumnFormat = (
    updateColumnFormatReq: BodyType<UpdateColumnFormatReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/vip/model/updateColumnFormat`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: updateColumnFormatReq
    },
      options);
    }
  /**
 * @summary 更新字段标准接口
 */
const updateColumnFormat1 = (
    updateColumnFormatReq: BodyType<UpdateColumnFormatReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/api/workspace/vip/model/updateColumnFormat`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: updateColumnFormatReq
    },
      options);
    }
  /**
 * @summary 重置数据模型接口
 */
const resetDataModel = (
    resetDataModelReq: BodyType<ResetDataModelReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/api/workspace/vip/model/resetDataModel`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: resetDataModelReq
    },
      options);
    }
  /**
 * @summary 重置数据模型接口
 */
const resetDataModel1 = (
    resetDataModelReq: BodyType<ResetDataModelReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/vip/model/resetDataModel`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: resetDataModelReq
    },
      options);
    }
  /**
 * @summary 分页查询模型字段接口
 */
const pageDataModelColumn = (
    pageDataModelColumnReq: BodyType<PageDataModelColumnReq>,
 options?: SecondParameter<typeof appRequest<PagedModelDataModelColumnPageRes>>,) => {
      return appRequest<PagedModelDataModelColumnPageRes>(
      {url: `/vip/model/pageDataModelColumn`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: pageDataModelColumnReq
    },
      options);
    }
  /**
 * @summary 分页查询模型字段接口
 */
const pageDataModelColumn1 = (
    pageDataModelColumnReq: BodyType<PageDataModelColumnReq>,
 options?: SecondParameter<typeof appRequest<PagedModelDataModelColumnPageRes>>,) => {
      return appRequest<PagedModelDataModelColumnPageRes>(
      {url: `/api/workspace/vip/model/pageDataModelColumn`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: pageDataModelColumnReq
    },
      options);
    }
  /**
 * @summary 分页查询分层下的数据模型接口
 */
const pageDataModelByLayer = (
    pageDataModelByLayerReq: BodyType<PageDataModelByLayerReq>,
 options?: SecondParameter<typeof appRequest<PagedModelDataModelPageRes>>,) => {
      return appRequest<PagedModelDataModelPageRes>(
      {url: `/vip/model/pageDataModelByLayer`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: pageDataModelByLayerReq
    },
      options);
    }
  /**
 * @summary 分页查询分层下的数据模型接口
 */
const pageDataModelByLayer1 = (
    pageDataModelByLayerReq: BodyType<PageDataModelByLayerReq>,
 options?: SecondParameter<typeof appRequest<PagedModelDataModelPageRes>>,) => {
      return appRequest<PagedModelDataModelPageRes>(
      {url: `/api/workspace/vip/model/pageDataModelByLayer`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: pageDataModelByLayerReq
    },
      options);
    }
  /**
 * @summary 分页查询数据模型接口
 */
const pageDataModel = (
    pageDataModelReq: BodyType<PageDataModelReq>,
 options?: SecondParameter<typeof appRequest<PagedModelDataModelPageRes>>,) => {
      return appRequest<PagedModelDataModelPageRes>(
      {url: `/api/workspace/vip/model/pageDataModel`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: pageDataModelReq
    },
      options);
    }
  /**
 * @summary 分页查询数据模型接口
 */
const pageDataModel1 = (
    pageDataModelReq: BodyType<PageDataModelReq>,
 options?: SecondParameter<typeof appRequest<PagedModelDataModelPageRes>>,) => {
      return appRequest<PagedModelDataModelPageRes>(
      {url: `/vip/model/pageDataModel`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: pageDataModelReq
    },
      options);
    }
  /**
 * @summary 分页查询字段标准接口
 */
const pageColumnFormat = (
    pageColumnFormatReq: BodyType<PageColumnFormatReq>,
 options?: SecondParameter<typeof appRequest<PagedModelColumnFormatPageRes>>,) => {
      return appRequest<PagedModelColumnFormatPageRes>(
      {url: `/api/workspace/vip/model/pageColumnFormat`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: pageColumnFormatReq
    },
      options);
    }
  /**
 * @summary 分页查询字段标准接口
 */
const pageColumnFormat1 = (
    pageColumnFormatReq: BodyType<PageColumnFormatReq>,
 options?: SecondParameter<typeof appRequest<PagedModelColumnFormatPageRes>>,) => {
      return appRequest<PagedModelColumnFormatPageRes>(
      {url: `/vip/model/pageColumnFormat`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: pageColumnFormatReq
    },
      options);
    }
  /**
 * @summary 删除字段标准接口
 */
const enableColumnFormat = (
    enableColumnFormatReq: BodyType<EnableColumnFormatReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/vip/model/enableColumnFormat`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: enableColumnFormatReq
    },
      options);
    }
  /**
 * @summary 删除字段标准接口
 */
const enableColumnFormat1 = (
    enableColumnFormatReq: BodyType<EnableColumnFormatReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/api/workspace/vip/model/enableColumnFormat`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: enableColumnFormatReq
    },
      options);
    }
  /**
 * @summary 删除字段标准接口
 */
const disableColumnFormat = (
    disableColumnFormatReq: BodyType<DisableColumnFormatReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/api/workspace/vip/model/disableColumnFormat`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: disableColumnFormatReq
    },
      options);
    }
  /**
 * @summary 删除字段标准接口
 */
const disableColumnFormat1 = (
    disableColumnFormatReq: BodyType<DisableColumnFormatReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/vip/model/disableColumnFormat`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: disableColumnFormatReq
    },
      options);
    }
  /**
 * @summary 删除模型字段接口
 */
const deleteDataModelColumn = (
    deleteColumnFormatReq: BodyType<DeleteColumnFormatReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/vip/model/deleteDataModelColumn`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: deleteColumnFormatReq
    },
      options);
    }
  /**
 * @summary 删除模型字段接口
 */
const deleteDataModelColumn1 = (
    deleteColumnFormatReq: BodyType<DeleteColumnFormatReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/api/workspace/vip/model/deleteDataModelColumn`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: deleteColumnFormatReq
    },
      options);
    }
  /**
 * @summary 删除数据模型接口
 */
const deleteDataModel = (
    deleteDataModelReq: BodyType<DeleteDataModelReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/vip/model/deleteDataModel`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: deleteDataModelReq
    },
      options);
    }
  /**
 * @summary 删除数据模型接口
 */
const deleteDataModel1 = (
    deleteDataModelReq: BodyType<DeleteDataModelReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/api/workspace/vip/model/deleteDataModel`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: deleteDataModelReq
    },
      options);
    }
  /**
 * @summary 删除字段标准接口
 */
const deleteColumnFormat = (
    deleteColumnFormatReq: BodyType<DeleteColumnFormatReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/vip/model/deleteColumnFormat`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: deleteColumnFormatReq
    },
      options);
    }
  /**
 * @summary 删除字段标准接口
 */
const deleteColumnFormat1 = (
    deleteColumnFormatReq: BodyType<DeleteColumnFormatReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/api/workspace/vip/model/deleteColumnFormat`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: deleteColumnFormatReq
    },
      options);
    }
  /**
 * @summary 一键复制数据模型接口
 */
const copyDataModel = (
    copyDataModelReq: BodyType<CopyDataModelReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/api/workspace/vip/model/copyDataModel`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: copyDataModelReq
    },
      options);
    }
  /**
 * @summary 一键复制数据模型接口
 */
const copyDataModel1 = (
    copyDataModelReq: BodyType<CopyDataModelReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/vip/model/copyDataModel`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: copyDataModelReq
    },
      options);
    }
  /**
 * @summary 构建数据模型接口
 */
const buildDataModel = (
    buildDataModelReq: BodyType<BuildDataModelReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/vip/model/buildDataModel`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: buildDataModelReq
    },
      options);
    }
  /**
 * @summary 构建数据模型接口
 */
const buildDataModel1 = (
    buildDataModelReq: BodyType<BuildDataModelReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/api/workspace/vip/model/buildDataModel`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: buildDataModelReq
    },
      options);
    }
  /**
 * @summary 新建模型字段接口
 */
const addDataModelColumn = (
    addDataModelColumnReq: BodyType<AddDataModelColumnReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/vip/model/addDataModelColumn`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: addDataModelColumnReq
    },
      options);
    }
  /**
 * @summary 新建模型字段接口
 */
const addDataModelColumn1 = (
    addDataModelColumnReq: BodyType<AddDataModelColumnReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/api/workspace/vip/model/addDataModelColumn`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: addDataModelColumnReq
    },
      options);
    }
  /**
 * @summary 新建数据模型接口
 */
const addDataModel = (
    addDataModelReq: BodyType<AddDataModelReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/api/workspace/vip/model/addDataModel`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: addDataModelReq
    },
      options);
    }
  /**
 * @summary 新建数据模型接口
 */
const addDataModel1 = (
    addDataModelReq: BodyType<AddDataModelReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/vip/model/addDataModel`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: addDataModelReq
    },
      options);
    }
  /**
 * @summary 新建字段标准接口
 */
const addColumnFormat = (
    addColumnFormatReq: BodyType<AddColumnFormatReq>,
 options?: SecondParameter<typeof appRequest<AddColumnFormatRes>>,) => {
      return appRequest<AddColumnFormatRes>(
      {url: `/api/workspace/vip/model/addColumnFormat`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: addColumnFormatReq
    },
      options);
    }
  /**
 * @summary 新建字段标准接口
 */
const addColumnFormat1 = (
    addColumnFormatReq: BodyType<AddColumnFormatReq>,
 options?: SecondParameter<typeof appRequest<AddColumnFormatRes>>,) => {
      return appRequest<AddColumnFormatRes>(
      {url: `/vip/model/addColumnFormat`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: addColumnFormatReq
    },
      options);
    }
  return {updateDataModelColumnIndex,updateDataModelColumnIndex1,updateDataModelColumn,updateDataModelColumn1,updateDataModel,updateDataModel1,updateColumnFormat,updateColumnFormat1,resetDataModel,resetDataModel1,pageDataModelColumn,pageDataModelColumn1,pageDataModelByLayer,pageDataModelByLayer1,pageDataModel,pageDataModel1,pageColumnFormat,pageColumnFormat1,enableColumnFormat,enableColumnFormat1,disableColumnFormat,disableColumnFormat1,deleteDataModelColumn,deleteDataModelColumn1,deleteDataModel,deleteDataModel1,deleteColumnFormat,deleteColumnFormat1,copyDataModel,copyDataModel1,buildDataModel,buildDataModel1,addDataModelColumn,addDataModelColumn1,addDataModel,addDataModel1,addColumnFormat,addColumnFormat1}};
export type UpdateDataModelColumnIndexResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getDataModel>['updateDataModelColumnIndex']>>>
export type UpdateDataModelColumnIndex1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getDataModel>['updateDataModelColumnIndex1']>>>
export type UpdateDataModelColumnResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getDataModel>['updateDataModelColumn']>>>
export type UpdateDataModelColumn1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getDataModel>['updateDataModelColumn1']>>>
export type UpdateDataModelResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getDataModel>['updateDataModel']>>>
export type UpdateDataModel1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getDataModel>['updateDataModel1']>>>
export type UpdateColumnFormatResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getDataModel>['updateColumnFormat']>>>
export type UpdateColumnFormat1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getDataModel>['updateColumnFormat1']>>>
export type ResetDataModelResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getDataModel>['resetDataModel']>>>
export type ResetDataModel1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getDataModel>['resetDataModel1']>>>
export type PageDataModelColumnResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getDataModel>['pageDataModelColumn']>>>
export type PageDataModelColumn1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getDataModel>['pageDataModelColumn1']>>>
export type PageDataModelByLayerResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getDataModel>['pageDataModelByLayer']>>>
export type PageDataModelByLayer1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getDataModel>['pageDataModelByLayer1']>>>
export type PageDataModelResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getDataModel>['pageDataModel']>>>
export type PageDataModel1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getDataModel>['pageDataModel1']>>>
export type PageColumnFormatResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getDataModel>['pageColumnFormat']>>>
export type PageColumnFormat1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getDataModel>['pageColumnFormat1']>>>
export type EnableColumnFormatResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getDataModel>['enableColumnFormat']>>>
export type EnableColumnFormat1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getDataModel>['enableColumnFormat1']>>>
export type DisableColumnFormatResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getDataModel>['disableColumnFormat']>>>
export type DisableColumnFormat1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getDataModel>['disableColumnFormat1']>>>
export type DeleteDataModelColumnResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getDataModel>['deleteDataModelColumn']>>>
export type DeleteDataModelColumn1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getDataModel>['deleteDataModelColumn1']>>>
export type DeleteDataModelResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getDataModel>['deleteDataModel']>>>
export type DeleteDataModel1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getDataModel>['deleteDataModel1']>>>
export type DeleteColumnFormatResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getDataModel>['deleteColumnFormat']>>>
export type DeleteColumnFormat1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getDataModel>['deleteColumnFormat1']>>>
export type CopyDataModelResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getDataModel>['copyDataModel']>>>
export type CopyDataModel1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getDataModel>['copyDataModel1']>>>
export type BuildDataModelResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getDataModel>['buildDataModel']>>>
export type BuildDataModel1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getDataModel>['buildDataModel1']>>>
export type AddDataModelColumnResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getDataModel>['addDataModelColumn']>>>
export type AddDataModelColumn1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getDataModel>['addDataModelColumn1']>>>
export type AddDataModelResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getDataModel>['addDataModel']>>>
export type AddDataModel1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getDataModel>['addDataModel1']>>>
export type AddColumnFormatResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getDataModel>['addColumnFormat']>>>
export type AddColumnFormat1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getDataModel>['addColumnFormat1']>>>
