/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * 至轻云
 * 超轻量级智能化大数据中心
 * OpenAPI spec version: 0.0.1
 */
import type {
  AddLayerReq,
  DeleteLayerReq,
  GetParentParentLayerReq,
  GetParentParentLayerRes,
  PageLayerReq,
  PagedModelLayerPageRes,
  RecursiveLayerReq,
  RecursiveLayerRes,
  SearchLayerReq,
  UpdateLayerReq
} from '../models';

import { appRequest } from '../../api/orval-mutator';
import type { BodyType } from '../../api/orval-mutator';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  export const getDataLayer = () => {
/**
 * @summary 更新分层接口
 */
const updateLayer = (
    updateLayerReq: BodyType<UpdateLayerReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/vip/layer/updateLayer`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: updateLayerReq
    },
      options);
    }
  /**
 * @summary 更新分层接口
 */
const updateLayer1 = (
    updateLayerReq: BodyType<UpdateLayerReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/api/workspace/vip/layer/updateLayer`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: updateLayerReq
    },
      options);
    }
  /**
 * @summary 分页搜索数据分层接口
 */
const searchLayer = (
    searchLayerReq: BodyType<SearchLayerReq>,
 options?: SecondParameter<typeof appRequest<PagedModelLayerPageRes>>,) => {
      return appRequest<PagedModelLayerPageRes>(
      {url: `/api/workspace/vip/layer/searchLayer`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: searchLayerReq
    },
      options);
    }
  /**
 * @summary 分页搜索数据分层接口
 */
const searchLayer1 = (
    searchLayerReq: BodyType<SearchLayerReq>,
 options?: SecondParameter<typeof appRequest<PagedModelLayerPageRes>>,) => {
      return appRequest<PagedModelLayerPageRes>(
      {url: `/vip/layer/searchLayer`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: searchLayerReq
    },
      options);
    }
  /**
 * @summary 递归查询分层信息接口
 */
const recursiveLayer = (
    recursiveLayerReq: BodyType<RecursiveLayerReq>,
 options?: SecondParameter<typeof appRequest<RecursiveLayerRes>>,) => {
      return appRequest<RecursiveLayerRes>(
      {url: `/api/workspace/vip/layer/recursiveLayer`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: recursiveLayerReq
    },
      options);
    }
  /**
 * @summary 递归查询分层信息接口
 */
const recursiveLayer1 = (
    recursiveLayerReq: BodyType<RecursiveLayerReq>,
 options?: SecondParameter<typeof appRequest<RecursiveLayerRes>>,) => {
      return appRequest<RecursiveLayerRes>(
      {url: `/vip/layer/recursiveLayer`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: recursiveLayerReq
    },
      options);
    }
  /**
 * @summary 分页查询数据分层接口
 */
const pageLayer = (
    pageLayerReq: BodyType<PageLayerReq>,
 options?: SecondParameter<typeof appRequest<PagedModelLayerPageRes>>,) => {
      return appRequest<PagedModelLayerPageRes>(
      {url: `/vip/layer/pageLayer`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: pageLayerReq
    },
      options);
    }
  /**
 * @summary 分页查询数据分层接口
 */
const pageLayer1 = (
    pageLayerReq: BodyType<PageLayerReq>,
 options?: SecondParameter<typeof appRequest<PagedModelLayerPageRes>>,) => {
      return appRequest<PagedModelLayerPageRes>(
      {url: `/api/workspace/vip/layer/pageLayer`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: pageLayerReq
    },
      options);
    }
  /**
 * @summary 获取父父级分层信息
 */
const getParentParentLayer = (
    getParentParentLayerReq: BodyType<GetParentParentLayerReq>,
 options?: SecondParameter<typeof appRequest<GetParentParentLayerRes>>,) => {
      return appRequest<GetParentParentLayerRes>(
      {url: `/api/workspace/vip/layer/getParentParentLayer`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: getParentParentLayerReq
    },
      options);
    }
  /**
 * @summary 获取父父级分层信息
 */
const getParentParentLayer1 = (
    getParentParentLayerReq: BodyType<GetParentParentLayerReq>,
 options?: SecondParameter<typeof appRequest<GetParentParentLayerRes>>,) => {
      return appRequest<GetParentParentLayerRes>(
      {url: `/vip/layer/getParentParentLayer`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: getParentParentLayerReq
    },
      options);
    }
  /**
 * @summary 删除数据分层接口
 */
const deleteLayer = (
    deleteLayerReq: BodyType<DeleteLayerReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/api/workspace/vip/layer/deleteLayer`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: deleteLayerReq
    },
      options);
    }
  /**
 * @summary 删除数据分层接口
 */
const deleteLayer1 = (
    deleteLayerReq: BodyType<DeleteLayerReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/vip/layer/deleteLayer`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: deleteLayerReq
    },
      options);
    }
  /**
 * @summary 新建数据分层接口
 */
const addForm = (
    addLayerReq: BodyType<AddLayerReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/api/workspace/vip/layer/addLayer`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: addLayerReq
    },
      options);
    }
  /**
 * @summary 新建数据分层接口
 */
const addForm1 = (
    addLayerReq: BodyType<AddLayerReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/vip/layer/addLayer`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: addLayerReq
    },
      options);
    }
  return {updateLayer,updateLayer1,searchLayer,searchLayer1,recursiveLayer,recursiveLayer1,pageLayer,pageLayer1,getParentParentLayer,getParentParentLayer1,deleteLayer,deleteLayer1,addForm,addForm1}};
export type UpdateLayerResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getDataLayer>['updateLayer']>>>
export type UpdateLayer1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getDataLayer>['updateLayer1']>>>
export type SearchLayerResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getDataLayer>['searchLayer']>>>
export type SearchLayer1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getDataLayer>['searchLayer1']>>>
export type RecursiveLayerResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getDataLayer>['recursiveLayer']>>>
export type RecursiveLayer1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getDataLayer>['recursiveLayer1']>>>
export type PageLayerResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getDataLayer>['pageLayer']>>>
export type PageLayer1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getDataLayer>['pageLayer1']>>>
export type GetParentParentLayerResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getDataLayer>['getParentParentLayer']>>>
export type GetParentParentLayer1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getDataLayer>['getParentParentLayer1']>>>
export type DeleteLayerResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getDataLayer>['deleteLayer']>>>
export type DeleteLayer1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getDataLayer>['deleteLayer1']>>>
export type AddFormResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getDataLayer>['addForm']>>>
export type AddForm1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getDataLayer>['addForm1']>>>
