// 安装前端依赖
tasks.register('pnpmInstall', Exec) {

    // 检测文件是否变化
    inputs.files(
        layout.projectDirectory.file('package.json'),
        layout.projectDirectory.file('pnpm-lock.yaml')
    )

    // 没有变化则直接输出
    outputs.dir(layout.projectDirectory.dir('node_modules'))

    // 制定工作空间
    workingDir projectDir

    // 执行安装依赖命令
    commandLine 'sh', '-c', 'pnpm install --frozen-lockfile --prefer-offline'
}

// 先构建前端
tasks.register('make', Exec) {

    // 先安装
    dependsOn('pnpmInstall')

    // 查看文件是否变化，变化则重新执行
    inputs.files(
        fileTree('src'),
        fileTree('public'),
        fileTree(projectDir) {
            include 'index.html'
            include '.env*'
            include 'env.d.ts'
            include 'package.json'
            include 'pnpm-lock.yaml'
            include 'tsconfig*.json'
            include 'vite.config.*'
        },
        rootProject.layout.projectDirectory.file('VERSION')
    )

    // 直接输出，之前打好的包
    outputs.dir(layout.projectDirectory.dir('dist'))

    // 制定当前工作目录
     workingDir projectDir

    // 前端打包
    commandLine 'sh', '-c', 'pnpm run build'
}
