onlyBuiltDependencies:
  - '@parcel/watcher'
  - vue-demi
overrides:
  brace-expansion@2: 2.0.3
  editorconfig>minimatch: 9.0.7
  flatted: 3.4.2
  glob: 10.5.0
  glob>minimatch: 9.0.7
  js-cookie: 3.0.7
  lodash: 4.18.1
  minimatch@3: 3.1.4
  minimatch@9: 9.0.7
  picomatch@2: 2.3.2
