/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * 至轻云
 * 超轻量级智能化大数据中心
 * OpenAPI spec version: 0.0.1
 */
import { appRequest } from '../../api/orval-mutator';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  export const getInternalException = () => {
/**
 * @summary token不存在异常
 */
const tokenIsNull = (

 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/exception/tokenIsNull`, method: 'GET'
    },
      options);
    }
  /**
 * @summary token不存在异常
 */
const tokenIsNull1 = (

 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/exception/tokenIsNull`, method: 'POST'
    },
      options);
    }
  /**
 * @summary token不合法异常
 */
const tokenIsInvalid = (

 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/exception/tokenIsInvalid`, method: 'GET'
    },
      options);
    }
  /**
 * @summary token不合法异常
 */
const tokenIsInvalid1 = (

 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/exception/tokenIsInvalid`, method: 'POST'
    },
      options);
    }
  /**
 * @summary 许可证无效异常
 */
const licenseError = (

 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/exception/licenseError`, method: 'GET'
    },
      options);
    }
  /**
 * @summary 许可证无效异常
 */
const licenseError1 = (

 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/exception/licenseError`, method: 'POST'
    },
      options);
    }
  /**
 * @summary 暂无权限异常
 */
const exceptionAuthError = (

 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/exception/authError`, method: 'GET'
    },
      options);
    }
  /**
 * @summary 暂无权限异常
 */
const exceptionAuthError1 = (

 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/exception/authError`, method: 'POST'
    },
      options);
    }
  return {tokenIsNull,tokenIsNull1,tokenIsInvalid,tokenIsInvalid1,licenseError,licenseError1,exceptionAuthError,exceptionAuthError1}};
export type TokenIsNullResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getInternalException>['tokenIsNull']>>>
export type TokenIsNull1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getInternalException>['tokenIsNull1']>>>
export type TokenIsInvalidResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getInternalException>['tokenIsInvalid']>>>
export type TokenIsInvalid1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getInternalException>['tokenIsInvalid1']>>>
export type LicenseErrorResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getInternalException>['licenseError']>>>
export type LicenseError1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getInternalException>['licenseError1']>>>
export type ExceptionAuthErrorResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getInternalException>['exceptionAuthError']>>>
export type ExceptionAuthError1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getInternalException>['exceptionAuthError1']>>>
