/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * 至轻云
 * 超轻量级智能化大数据中心
 * OpenAPI spec version: 0.0.1
 */
import type {
  AddWorkReq,
  AgentLinkResponse,
  ConfigWorkReq,
  CopyWorkReq,
  DeleteWorkReq,
  GetApiDataReq,
  GetApiDataRes,
  GetCreateTableSqlReq,
  GetCreateTableSqlRes,
  GetDataReq,
  GetDataRes,
  GetDataSourceColumnsReq,
  GetDataSourceColumnsRes,
  GetDataSourceDataReq,
  GetDataSourceDataRes,
  GetDataSourceTablesReq,
  GetDataSourceTablesRes,
  GetExcelColumnsReq,
  GetExcelColumnsRes,
  GetExcelDataReq,
  GetExcelDataRes,
  GetStatusReq,
  GetStatusRes,
  GetSubmitLogReq,
  GetSubmitLogRes,
  GetWorkInstanceJsonPathReq,
  GetWorkInstanceRegexPathReq,
  GetWorkInstanceTablePathReq,
  GetWorkInstanceValuePathRes,
  GetWorkLogRes,
  GetWorkReq,
  GetWorkRes,
  GetWorkflowInstanceReq,
  GetWorkflowInstanceRes,
  GetYarnLogReq,
  PageWorkReq,
  PagedModelPageWorkRes,
  PagedModelQueryInstanceRes,
  ParseExcelNameReq,
  ParseExcelNameRes,
  QueryInstanceReq,
  RenameWorkReq,
  RunWorkReq,
  StopJobReq,
  TopWorkReq,
  UpdateWorkReq
} from '../models';

import { appRequest } from '../../api/orval-mutator';
import type { BodyType } from '../../api/orval-mutator';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  export const getWork = () => {
/**
 * @summary 更新作业接口
 */
const updateWork = (
    updateWorkReq: BodyType<UpdateWorkReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/work/updateWork`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: updateWorkReq
    },
      options);
    }
  /**
 * @summary 更新作业接口
 */
const updateWork1 = (
    updateWorkReq: BodyType<UpdateWorkReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/api/workspace/work/updateWork`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: updateWorkReq
    },
      options);
    }
  /**
 * @summary 作业置顶接口
 */
const topWork = (
    topWorkReq: BodyType<TopWorkReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/work/topWork`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: topWorkReq
    },
      options);
    }
  /**
 * @summary 作业置顶接口
 */
const topWork1 = (
    topWorkReq: BodyType<TopWorkReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/api/workspace/work/topWork`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: topWorkReq
    },
      options);
    }
  /**
 * @summary 中止作业接口
 */
const stopJob = (
    stopJobReq: BodyType<StopJobReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/api/workspace/work/stopJob`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: stopJobReq
    },
      options);
    }
  /**
 * @summary 中止作业接口
 */
const stopJob1 = (
    stopJobReq: BodyType<StopJobReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/work/stopJob`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: stopJobReq
    },
      options);
    }
  /**
 * @summary 运行作业接口
 */
const runWork = (
    runWorkReq: BodyType<RunWorkReq>,
 options?: SecondParameter<typeof appRequest<AgentLinkResponse>>,) => {
      return appRequest<AgentLinkResponse>(
      {url: `/api/workspace/work/runWork`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: runWorkReq
    },
      options);
    }
  /**
 * @summary 运行作业接口
 */
const runWork1 = (
    runWorkReq: BodyType<RunWorkReq>,
 options?: SecondParameter<typeof appRequest<AgentLinkResponse>>,) => {
      return appRequest<AgentLinkResponse>(
      {url: `/work/runWork`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: runWorkReq
    },
      options);
    }
  /**
 * @summary 作业重命名接口
 */
const renameWork = (
    renameWorkReq: BodyType<RenameWorkReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/api/workspace/work/renameWork`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: renameWorkReq
    },
      options);
    }
  /**
 * @summary 作业重命名接口
 */
const renameWork1 = (
    renameWorkReq: BodyType<RenameWorkReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/work/renameWork`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: renameWorkReq
    },
      options);
    }
  /**
 * @summary 查看作业实例接口
 */
const queryInstance = (
    queryInstanceReq: BodyType<QueryInstanceReq>,
 options?: SecondParameter<typeof appRequest<PagedModelQueryInstanceRes>>,) => {
      return appRequest<PagedModelQueryInstanceRes>(
      {url: `/api/workspace/work/queryInstance`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: queryInstanceReq
    },
      options);
    }
  /**
 * @summary 查看作业实例接口
 */
const queryInstance1 = (
    queryInstanceReq: BodyType<QueryInstanceReq>,
 options?: SecondParameter<typeof appRequest<PagedModelQueryInstanceRes>>,) => {
      return appRequest<PagedModelQueryInstanceRes>(
      {url: `/work/queryInstance`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: queryInstanceReq
    },
      options);
    }
  /**
 * @summary 预览excel文件名接口
 */
const parseExcelName = (
    parseExcelNameReq: BodyType<ParseExcelNameReq>,
 options?: SecondParameter<typeof appRequest<ParseExcelNameRes>>,) => {
      return appRequest<ParseExcelNameRes>(
      {url: `/work/parseExcelName`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: parseExcelNameReq
    },
      options);
    }
  /**
 * @summary 预览excel文件名接口
 */
const parseExcelName1 = (
    parseExcelNameReq: BodyType<ParseExcelNameReq>,
 options?: SecondParameter<typeof appRequest<ParseExcelNameRes>>,) => {
      return appRequest<ParseExcelNameRes>(
      {url: `/api/workspace/work/parseExcelName`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: parseExcelNameReq
    },
      options);
    }
  /**
 * @summary 查询作业列表接口
 */
const pageWork = (
    pageWorkReq: BodyType<PageWorkReq>,
 options?: SecondParameter<typeof appRequest<PagedModelPageWorkRes>>,) => {
      return appRequest<PagedModelPageWorkRes>(
      {url: `/api/workspace/work/pageWork`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: pageWorkReq
    },
      options);
    }
  /**
 * @summary 查询作业列表接口
 */
const pageWork1 = (
    pageWorkReq: BodyType<PageWorkReq>,
 options?: SecondParameter<typeof appRequest<PagedModelPageWorkRes>>,) => {
      return appRequest<PagedModelPageWorkRes>(
      {url: `/work/pageWork`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: pageWorkReq
    },
      options);
    }
  /**
 * @summary 查询作业运行日志接口
 */
const getYarnLog = (
    getYarnLogReq: BodyType<GetYarnLogReq>,
 options?: SecondParameter<typeof appRequest<GetWorkLogRes>>,) => {
      return appRequest<GetWorkLogRes>(
      {url: `/work/getYarnLog`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: getYarnLogReq
    },
      options);
    }
  /**
 * @summary 查询作业运行日志接口
 */
const getYarnLog1 = (
    getYarnLogReq: BodyType<GetYarnLogReq>,
 options?: SecondParameter<typeof appRequest<GetWorkLogRes>>,) => {
      return appRequest<GetWorkLogRes>(
      {url: `/api/workspace/work/getYarnLog`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: getYarnLogReq
    },
      options);
    }
  /**
 * @summary 查询单个作业流实例信息接口
 */
const getWorkflowInstance = (
    getWorkflowInstanceReq: BodyType<GetWorkflowInstanceReq>,
 options?: SecondParameter<typeof appRequest<GetWorkflowInstanceRes>>,) => {
      return appRequest<GetWorkflowInstanceRes>(
      {url: `/work/getWorkflowInstance`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: getWorkflowInstanceReq
    },
      options);
    }
  /**
 * @summary 查询单个作业流实例信息接口
 */
const getWorkflowInstance1 = (
    getWorkflowInstanceReq: BodyType<GetWorkflowInstanceReq>,
 options?: SecondParameter<typeof appRequest<GetWorkflowInstanceRes>>,) => {
      return appRequest<GetWorkflowInstanceRes>(
      {url: `/api/workspace/work/getWorkflowInstance`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: getWorkflowInstanceReq
    },
      options);
    }
  /**
 * @summary 获取作业返回的几行几列结果接口
 */
const getWorkInstanceTablePath = (
    getWorkInstanceTablePathReq: BodyType<GetWorkInstanceTablePathReq>,
 options?: SecondParameter<typeof appRequest<GetWorkInstanceValuePathRes>>,) => {
      return appRequest<GetWorkInstanceValuePathRes>(
      {url: `/api/workspace/work/getWorkInstanceTablePath`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: getWorkInstanceTablePathReq
    },
      options);
    }
  /**
 * @summary 获取作业返回的几行几列结果接口
 */
const getWorkInstanceTablePath1 = (
    getWorkInstanceTablePathReq: BodyType<GetWorkInstanceTablePathReq>,
 options?: SecondParameter<typeof appRequest<GetWorkInstanceValuePathRes>>,) => {
      return appRequest<GetWorkInstanceValuePathRes>(
      {url: `/work/getWorkInstanceTablePath`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: getWorkInstanceTablePathReq
    },
      options);
    }
  /**
 * @summary 获取作业返回的正则解析结果接口
 */
const getWorkInstanceRegexPath = (
    getWorkInstanceRegexPathReq: BodyType<GetWorkInstanceRegexPathReq>,
 options?: SecondParameter<typeof appRequest<GetWorkInstanceValuePathRes>>,) => {
      return appRequest<GetWorkInstanceValuePathRes>(
      {url: `/api/workspace/work/getWorkInstanceRegexPath`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: getWorkInstanceRegexPathReq
    },
      options);
    }
  /**
 * @summary 获取作业返回的正则解析结果接口
 */
const getWorkInstanceRegexPath1 = (
    getWorkInstanceRegexPathReq: BodyType<GetWorkInstanceRegexPathReq>,
 options?: SecondParameter<typeof appRequest<GetWorkInstanceValuePathRes>>,) => {
      return appRequest<GetWorkInstanceValuePathRes>(
      {url: `/work/getWorkInstanceRegexPath`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: getWorkInstanceRegexPathReq
    },
      options);
    }
  /**
 * @summary 获取作业返回的jsonPath接口
 */
const getWorkInstanceJsonPath = (
    getWorkInstanceJsonPathReq: BodyType<GetWorkInstanceJsonPathReq>,
 options?: SecondParameter<typeof appRequest<GetWorkInstanceValuePathRes[]>>,) => {
      return appRequest<GetWorkInstanceValuePathRes[]>(
      {url: `/api/workspace/work/getWorkInstanceJsonPath`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: getWorkInstanceJsonPathReq
    },
      options);
    }
  /**
 * @summary 获取作业返回的jsonPath接口
 */
const getWorkInstanceJsonPath1 = (
    getWorkInstanceJsonPathReq: BodyType<GetWorkInstanceJsonPathReq>,
 options?: SecondParameter<typeof appRequest<GetWorkInstanceValuePathRes[]>>,) => {
      return appRequest<GetWorkInstanceValuePathRes[]>(
      {url: `/work/getWorkInstanceJsonPath`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: getWorkInstanceJsonPathReq
    },
      options);
    }
  /**
 * @summary 获取作业信息接口
 */
const getWork = (
    getWorkReq: BodyType<GetWorkReq>,
 options?: SecondParameter<typeof appRequest<GetWorkRes>>,) => {
      return appRequest<GetWorkRes>(
      {url: `/work/getWork`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: getWorkReq
    },
      options);
    }
  /**
 * @summary 获取作业信息接口
 */
const getWork1 = (
    getWorkReq: BodyType<GetWorkReq>,
 options?: SecondParameter<typeof appRequest<GetWorkRes>>,) => {
      return appRequest<GetWorkRes>(
      {url: `/api/workspace/work/getWork`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: getWorkReq
    },
      options);
    }
  /**
 * @summary 查询作业提交日志接口
 */
const getSubmitLog = (
    getSubmitLogReq: BodyType<GetSubmitLogReq>,
 options?: SecondParameter<typeof appRequest<GetSubmitLogRes>>,) => {
      return appRequest<GetSubmitLogRes>(
      {url: `/work/getSubmitLog`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: getSubmitLogReq
    },
      options);
    }
  /**
 * @summary 查询作业提交日志接口
 */
const getSubmitLog1 = (
    getSubmitLogReq: BodyType<GetSubmitLogReq>,
 options?: SecondParameter<typeof appRequest<GetSubmitLogRes>>,) => {
      return appRequest<GetSubmitLogRes>(
      {url: `/api/workspace/work/getSubmitLog`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: getSubmitLogReq
    },
      options);
    }
  /**
 * @summary 获取作业当前运行状态接口
 */
const getStatus = (
    getStatusReq: BodyType<GetStatusReq>,
 options?: SecondParameter<typeof appRequest<GetStatusRes>>,) => {
      return appRequest<GetStatusRes>(
      {url: `/api/workspace/work/getStatus`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: getStatusReq
    },
      options);
    }
  /**
 * @summary 获取作业当前运行状态接口
 */
const getStatus1 = (
    getStatusReq: BodyType<GetStatusReq>,
 options?: SecondParameter<typeof appRequest<GetStatusRes>>,) => {
      return appRequest<GetStatusRes>(
      {url: `/work/getStatus`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: getStatusReq
    },
      options);
    }
  /**
 * @summary excel数据预览接口
 */
const getExcelData = (
    getExcelDataReq: BodyType<GetExcelDataReq>,
 options?: SecondParameter<typeof appRequest<GetExcelDataRes>>,) => {
      return appRequest<GetExcelDataRes>(
      {url: `/api/workspace/work/getExcelData`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: getExcelDataReq
    },
      options);
    }
  /**
 * @summary excel数据预览接口
 */
const getExcelData1 = (
    getExcelDataReq: BodyType<GetExcelDataReq>,
 options?: SecondParameter<typeof appRequest<GetExcelDataRes>>,) => {
      return appRequest<GetExcelDataRes>(
      {url: `/work/getExcelData`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: getExcelDataReq
    },
      options);
    }
  /**
 * @summary 获取Excel文件的字段信息接口
 */
const getExcelColumns = (
    getExcelColumnsReq: BodyType<GetExcelColumnsReq>,
 options?: SecondParameter<typeof appRequest<GetExcelColumnsRes>>,) => {
      return appRequest<GetExcelColumnsRes>(
      {url: `/api/workspace/work/getExcelColumns`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: getExcelColumnsReq
    },
      options);
    }
  /**
 * @summary 获取Excel文件的字段信息接口
 */
const getExcelColumns1 = (
    getExcelColumnsReq: BodyType<GetExcelColumnsReq>,
 options?: SecondParameter<typeof appRequest<GetExcelColumnsRes>>,) => {
      return appRequest<GetExcelColumnsRes>(
      {url: `/work/getExcelColumns`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: getExcelColumnsReq
    },
      options);
    }
  /**
 * @summary 获取数据源表信息接口
 */
const getDataSourceTables = (
    getDataSourceTablesReq: BodyType<GetDataSourceTablesReq>,
 options?: SecondParameter<typeof appRequest<GetDataSourceTablesRes>>,) => {
      return appRequest<GetDataSourceTablesRes>(
      {url: `/work/getDataSourceTables`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: getDataSourceTablesReq
    },
      options);
    }
  /**
 * @summary 获取数据源表信息接口
 */
const getDataSourceTables1 = (
    getDataSourceTablesReq: BodyType<GetDataSourceTablesReq>,
 options?: SecondParameter<typeof appRequest<GetDataSourceTablesRes>>,) => {
      return appRequest<GetDataSourceTablesRes>(
      {url: `/api/workspace/work/getDataSourceTables`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: getDataSourceTablesReq
    },
      options);
    }
  /**
 * @summary 数据预览接口
 */
const getDataSourceData = (
    getDataSourceDataReq: BodyType<GetDataSourceDataReq>,
 options?: SecondParameter<typeof appRequest<GetDataSourceDataRes>>,) => {
      return appRequest<GetDataSourceDataRes>(
      {url: `/api/workspace/work/getDataSourceData`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: getDataSourceDataReq
    },
      options);
    }
  /**
 * @summary 数据预览接口
 */
const getDataSourceData1 = (
    getDataSourceDataReq: BodyType<GetDataSourceDataReq>,
 options?: SecondParameter<typeof appRequest<GetDataSourceDataRes>>,) => {
      return appRequest<GetDataSourceDataRes>(
      {url: `/work/getDataSourceData`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: getDataSourceDataReq
    },
      options);
    }
  /**
 * @summary 获取数据表字段信息接口
 */
const getDataSourceColumns = (
    getDataSourceColumnsReq: BodyType<GetDataSourceColumnsReq>,
 options?: SecondParameter<typeof appRequest<GetDataSourceColumnsRes>>,) => {
      return appRequest<GetDataSourceColumnsRes>(
      {url: `/api/workspace/work/getDataSourceColumns`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: getDataSourceColumnsReq
    },
      options);
    }
  /**
 * @summary 获取数据表字段信息接口
 */
const getDataSourceColumns1 = (
    getDataSourceColumnsReq: BodyType<GetDataSourceColumnsReq>,
 options?: SecondParameter<typeof appRequest<GetDataSourceColumnsRes>>,) => {
      return appRequest<GetDataSourceColumnsRes>(
      {url: `/work/getDataSourceColumns`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: getDataSourceColumnsReq
    },
      options);
    }
  /**
 * @summary 查询作业返回数据接口
 */
const getData = (
    getDataReq: BodyType<GetDataReq>,
 options?: SecondParameter<typeof appRequest<GetDataRes>>,) => {
      return appRequest<GetDataRes>(
      {url: `/api/workspace/work/getData`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: getDataReq
    },
      options);
    }
  /**
 * @summary 查询作业返回数据接口
 */
const getData1 = (
    getDataReq: BodyType<GetDataReq>,
 options?: SecondParameter<typeof appRequest<GetDataRes>>,) => {
      return appRequest<GetDataRes>(
      {url: `/work/getData`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: getDataReq
    },
      options);
    }
  /**
 * @summary DDL预生成接口
 */
const getCreateTableSql = (
    getCreateTableSqlReq: BodyType<GetCreateTableSqlReq>,
 options?: SecondParameter<typeof appRequest<GetCreateTableSqlRes>>,) => {
      return appRequest<GetCreateTableSqlRes>(
      {url: `/api/workspace/work/getCreateTableSql`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: getCreateTableSqlReq
    },
      options);
    }
  /**
 * @summary DDL预生成接口
 */
const getCreateTableSql1 = (
    getCreateTableSqlReq: BodyType<GetCreateTableSqlReq>,
 options?: SecondParameter<typeof appRequest<GetCreateTableSqlRes>>,) => {
      return appRequest<GetCreateTableSqlRes>(
      {url: `/work/getCreateTableSql`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: getCreateTableSqlReq
    },
      options);
    }
  /**
 * @summary api数据预览接口
 */
const getApiData = (
    getApiDataReq: BodyType<GetApiDataReq>,
 options?: SecondParameter<typeof appRequest<GetApiDataRes>>,) => {
      return appRequest<GetApiDataRes>(
      {url: `/api/workspace/work/getApiData`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: getApiDataReq
    },
      options);
    }
  /**
 * @summary api数据预览接口
 */
const getApiData1 = (
    getApiDataReq: BodyType<GetApiDataReq>,
 options?: SecondParameter<typeof appRequest<GetApiDataRes>>,) => {
      return appRequest<GetApiDataRes>(
      {url: `/work/getApiData`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: getApiDataReq
    },
      options);
    }
  /**
 * @summary 删除作业接口
 */
const deleteWork = (
    deleteWorkReq: BodyType<DeleteWorkReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/api/workspace/work/deleteWork`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: deleteWorkReq
    },
      options);
    }
  /**
 * @summary 删除作业接口
 */
const deleteWork1 = (
    deleteWorkReq: BodyType<DeleteWorkReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/work/deleteWork`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: deleteWorkReq
    },
      options);
    }
  /**
 * @summary 作业复制接口
 */
const copyWork = (
    copyWorkReq: BodyType<CopyWorkReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/api/workspace/work/copyWork`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: copyWorkReq
    },
      options);
    }
  /**
 * @summary 作业复制接口
 */
const copyWork1 = (
    copyWorkReq: BodyType<CopyWorkReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/work/copyWork`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: copyWorkReq
    },
      options);
    }
  /**
 * @summary 配置作业接口
 */
const configWork = (
    configWorkReq: BodyType<ConfigWorkReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/work/configWork`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: configWorkReq
    },
      options);
    }
  /**
 * @summary 配置作业接口
 */
const configWork1 = (
    configWorkReq: BodyType<ConfigWorkReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/api/workspace/work/configWork`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: configWorkReq
    },
      options);
    }
  /**
 * @summary 添加作业接口
 */
const addWork = (
    addWorkReq: BodyType<AddWorkReq>,
 options?: SecondParameter<typeof appRequest<GetWorkRes>>,) => {
      return appRequest<GetWorkRes>(
      {url: `/api/workspace/work/addWork`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: addWorkReq
    },
      options);
    }
  /**
 * @summary 添加作业接口
 */
const addWork1 = (
    addWorkReq: BodyType<AddWorkReq>,
 options?: SecondParameter<typeof appRequest<GetWorkRes>>,) => {
      return appRequest<GetWorkRes>(
      {url: `/work/addWork`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: addWorkReq
    },
      options);
    }
  return {updateWork,updateWork1,topWork,topWork1,stopJob,stopJob1,runWork,runWork1,renameWork,renameWork1,queryInstance,queryInstance1,parseExcelName,parseExcelName1,pageWork,pageWork1,getYarnLog,getYarnLog1,getWorkflowInstance,getWorkflowInstance1,getWorkInstanceTablePath,getWorkInstanceTablePath1,getWorkInstanceRegexPath,getWorkInstanceRegexPath1,getWorkInstanceJsonPath,getWorkInstanceJsonPath1,getWork,getWork1,getSubmitLog,getSubmitLog1,getStatus,getStatus1,getExcelData,getExcelData1,getExcelColumns,getExcelColumns1,getDataSourceTables,getDataSourceTables1,getDataSourceData,getDataSourceData1,getDataSourceColumns,getDataSourceColumns1,getData,getData1,getCreateTableSql,getCreateTableSql1,getApiData,getApiData1,deleteWork,deleteWork1,copyWork,copyWork1,configWork,configWork1,addWork,addWork1}};
export type UpdateWorkResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getWork>['updateWork']>>>
export type UpdateWork1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getWork>['updateWork1']>>>
export type TopWorkResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getWork>['topWork']>>>
export type TopWork1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getWork>['topWork1']>>>
export type StopJobResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getWork>['stopJob']>>>
export type StopJob1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getWork>['stopJob1']>>>
export type RunWorkResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getWork>['runWork']>>>
export type RunWork1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getWork>['runWork1']>>>
export type RenameWorkResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getWork>['renameWork']>>>
export type RenameWork1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getWork>['renameWork1']>>>
export type QueryInstanceResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getWork>['queryInstance']>>>
export type QueryInstance1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getWork>['queryInstance1']>>>
export type ParseExcelNameResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getWork>['parseExcelName']>>>
export type ParseExcelName1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getWork>['parseExcelName1']>>>
export type PageWorkResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getWork>['pageWork']>>>
export type PageWork1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getWork>['pageWork1']>>>
export type GetYarnLogResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getWork>['getYarnLog']>>>
export type GetYarnLog1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getWork>['getYarnLog1']>>>
export type GetWorkflowInstanceResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getWork>['getWorkflowInstance']>>>
export type GetWorkflowInstance1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getWork>['getWorkflowInstance1']>>>
export type GetWorkInstanceTablePathResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getWork>['getWorkInstanceTablePath']>>>
export type GetWorkInstanceTablePath1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getWork>['getWorkInstanceTablePath1']>>>
export type GetWorkInstanceRegexPathResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getWork>['getWorkInstanceRegexPath']>>>
export type GetWorkInstanceRegexPath1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getWork>['getWorkInstanceRegexPath1']>>>
export type GetWorkInstanceJsonPathResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getWork>['getWorkInstanceJsonPath']>>>
export type GetWorkInstanceJsonPath1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getWork>['getWorkInstanceJsonPath1']>>>
export type GetWorkResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getWork>['getWork']>>>
export type GetWork1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getWork>['getWork1']>>>
export type GetSubmitLogResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getWork>['getSubmitLog']>>>
export type GetSubmitLog1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getWork>['getSubmitLog1']>>>
export type GetStatusResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getWork>['getStatus']>>>
export type GetStatus1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getWork>['getStatus1']>>>
export type GetExcelDataResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getWork>['getExcelData']>>>
export type GetExcelData1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getWork>['getExcelData1']>>>
export type GetExcelColumnsResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getWork>['getExcelColumns']>>>
export type GetExcelColumns1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getWork>['getExcelColumns1']>>>
export type GetDataSourceTablesResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getWork>['getDataSourceTables']>>>
export type GetDataSourceTables1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getWork>['getDataSourceTables1']>>>
export type GetDataSourceDataResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getWork>['getDataSourceData']>>>
export type GetDataSourceData1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getWork>['getDataSourceData1']>>>
export type GetDataSourceColumnsResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getWork>['getDataSourceColumns']>>>
export type GetDataSourceColumns1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getWork>['getDataSourceColumns1']>>>
export type GetDataResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getWork>['getData']>>>
export type GetData1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getWork>['getData1']>>>
export type GetCreateTableSqlResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getWork>['getCreateTableSql']>>>
export type GetCreateTableSql1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getWork>['getCreateTableSql1']>>>
export type GetApiDataResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getWork>['getApiData']>>>
export type GetApiData1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getWork>['getApiData1']>>>
export type DeleteWorkResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getWork>['deleteWork']>>>
export type DeleteWork1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getWork>['deleteWork1']>>>
export type CopyWorkResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getWork>['copyWork']>>>
export type CopyWork1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getWork>['copyWork1']>>>
export type ConfigWorkResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getWork>['configWork']>>>
export type ConfigWork1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getWork>['configWork1']>>>
export type AddWorkResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getWork>['addWork']>>>
export type AddWork1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getWork>['addWork1']>>>
