/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * 至轻云
 * 超轻量级智能化大数据中心
 * OpenAPI spec version: 0.0.1
 */
import type {
  AddLibPackageReq,
  AddLibPackageRes,
  ConfigLibPackageReq,
  DeleteFileReq,
  DeleteLibPackageReq,
  DownloadFileReq,
  GetLibPackageReq,
  GetLibPackageRes,
  PageFileReq,
  PageLibPackageReq,
  PagedModelPageFileRes,
  PagedModelPageLibPackageRes,
  UpdateFile1Body,
  UpdateFile1Params,
  UpdateFileBody,
  UpdateFileParams,
  UpdateLibPackageReq,
  UpdateLibPackageRes,
  UploadDuplicateFile1Params,
  UploadDuplicateFileParams,
  UploadFile1Body,
  UploadFile1Params,
  UploadFileBody,
  UploadFileParams
} from '../models';

import { appRequest } from '../../api/orval-mutator';
import type { BodyType } from '../../api/orval-mutator';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  export const getFile = () => {
/**
 * @summary 资源文件上传接口
 */
const uploadFile = (
    params: UploadFileParams,
    uploadFileBody?: BodyType<UploadFileBody>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/api/workspace/file/uploadFile`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: uploadFileBody,
        params
    },
      options);
    }
  /**
 * @summary 资源文件上传接口
 */
const uploadFile1 = (
    params: UploadFile1Params,
    uploadFile1Body?: BodyType<UploadFile1Body>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/file/uploadFile`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: uploadFile1Body,
        params
    },
      options);
    }
  /**
 * @summary 资源文件批量上传接口
 */
const uploadDuplicateFile = (
    params: UploadDuplicateFileParams,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/api/workspace/file/uploadDuplicateFile`, method: 'POST',
        params
    },
      options);
    }
  /**
 * @summary 资源文件批量上传接口
 */
const uploadDuplicateFile1 = (
    params: UploadDuplicateFile1Params,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/file/uploadDuplicateFile`, method: 'POST',
        params
    },
      options);
    }
  /**
 * @summary 编辑依赖包
 */
const updateLibPackage = (
    updateLibPackageReq: BodyType<UpdateLibPackageReq>,
 options?: SecondParameter<typeof appRequest<UpdateLibPackageRes>>,) => {
      return appRequest<UpdateLibPackageRes>(
      {url: `/file/updateLibPackage`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: updateLibPackageReq
    },
      options);
    }
  /**
 * @summary 编辑依赖包
 */
const updateLibPackage1 = (
    updateLibPackageReq: BodyType<UpdateLibPackageReq>,
 options?: SecondParameter<typeof appRequest<UpdateLibPackageRes>>,) => {
      return appRequest<UpdateLibPackageRes>(
      {url: `/api/workspace/file/updateLibPackage`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: updateLibPackageReq
    },
      options);
    }
  /**
 * @summary 资源文件更新接口
 */
const updateFile = (
    params: UpdateFileParams,
    updateFileBody?: BodyType<UpdateFileBody>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/file/updateFile`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: updateFileBody,
        params
    },
      options);
    }
  /**
 * @summary 资源文件更新接口
 */
const updateFile1 = (
    params: UpdateFile1Params,
    updateFile1Body?: BodyType<UpdateFile1Body>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/api/workspace/file/updateFile`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: updateFile1Body,
        params
    },
      options);
    }
  /**
 * @summary 分页查询依赖包
 */
const pageLibPackage = (
    pageLibPackageReq: BodyType<PageLibPackageReq>,
 options?: SecondParameter<typeof appRequest<PagedModelPageLibPackageRes>>,) => {
      return appRequest<PagedModelPageLibPackageRes>(
      {url: `/api/workspace/file/pageLibPackage`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: pageLibPackageReq
    },
      options);
    }
  /**
 * @summary 分页查询依赖包
 */
const pageLibPackage1 = (
    pageLibPackageReq: BodyType<PageLibPackageReq>,
 options?: SecondParameter<typeof appRequest<PagedModelPageLibPackageRes>>,) => {
      return appRequest<PagedModelPageLibPackageRes>(
      {url: `/file/pageLibPackage`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: pageLibPackageReq
    },
      options);
    }
  /**
 * @summary 资源文件查询接口
 */
const pageFile = (
    pageFileReq: BodyType<PageFileReq>,
 options?: SecondParameter<typeof appRequest<PagedModelPageFileRes>>,) => {
      return appRequest<PagedModelPageFileRes>(
      {url: `/api/workspace/file/pageFile`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: pageFileReq
    },
      options);
    }
  /**
 * @summary 资源文件查询接口
 */
const pageFile1 = (
    pageFileReq: BodyType<PageFileReq>,
 options?: SecondParameter<typeof appRequest<PagedModelPageFileRes>>,) => {
      return appRequest<PagedModelPageFileRes>(
      {url: `/file/pageFile`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: pageFileReq
    },
      options);
    }
  /**
 * @summary 获取依赖包信息
 */
const getLibPackage = (
    getLibPackageReq: BodyType<GetLibPackageReq>,
 options?: SecondParameter<typeof appRequest<GetLibPackageRes>>,) => {
      return appRequest<GetLibPackageRes>(
      {url: `/file/getLibPackage`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: getLibPackageReq
    },
      options);
    }
  /**
 * @summary 获取依赖包信息
 */
const getLibPackage1 = (
    getLibPackageReq: BodyType<GetLibPackageReq>,
 options?: SecondParameter<typeof appRequest<GetLibPackageRes>>,) => {
      return appRequest<GetLibPackageRes>(
      {url: `/api/workspace/file/getLibPackage`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: getLibPackageReq
    },
      options);
    }
  /**
 * @summary 资源文件下载接口
 */
const downloadFile = (
    downloadFileReq: BodyType<DownloadFileReq>,
 options?: SecondParameter<typeof appRequest<Blob>>,) => {
      return appRequest<Blob>(
      {url: `/api/workspace/file/downloadFile`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: downloadFileReq,
        responseType: 'blob'
    },
      options);
    }
  /**
 * @summary 资源文件下载接口
 */
const downloadFile1 = (
    downloadFileReq: BodyType<DownloadFileReq>,
 options?: SecondParameter<typeof appRequest<Blob>>,) => {
      return appRequest<Blob>(
      {url: `/file/downloadFile`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: downloadFileReq,
        responseType: 'blob'
    },
      options);
    }
  /**
 * @summary 删除依赖包
 */
const deleteLibPackage = (
    deleteLibPackageReq: BodyType<DeleteLibPackageReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/file/deleteLibPackage`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: deleteLibPackageReq
    },
      options);
    }
  /**
 * @summary 删除依赖包
 */
const deleteLibPackage1 = (
    deleteLibPackageReq: BodyType<DeleteLibPackageReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/api/workspace/file/deleteLibPackage`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: deleteLibPackageReq
    },
      options);
    }
  /**
 * @summary 资源文件删除接口
 */
const deleteFile = (
    deleteFileReq: BodyType<DeleteFileReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/api/workspace/file/deleteFile`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: deleteFileReq
    },
      options);
    }
  /**
 * @summary 资源文件删除接口
 */
const deleteFile1 = (
    deleteFileReq: BodyType<DeleteFileReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/file/deleteFile`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: deleteFileReq
    },
      options);
    }
  /**
 * @summary 配置依赖包
 */
const configLibPackage = (
    configLibPackageReq: BodyType<ConfigLibPackageReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/file/configLibPackage`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: configLibPackageReq
    },
      options);
    }
  /**
 * @summary 配置依赖包
 */
const configLibPackage1 = (
    configLibPackageReq: BodyType<ConfigLibPackageReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/api/workspace/file/configLibPackage`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: configLibPackageReq
    },
      options);
    }
  /**
 * @summary 添加依赖包
 */
const addLibPackage = (
    addLibPackageReq: BodyType<AddLibPackageReq>,
 options?: SecondParameter<typeof appRequest<AddLibPackageRes>>,) => {
      return appRequest<AddLibPackageRes>(
      {url: `/api/workspace/file/addLibPackage`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: addLibPackageReq
    },
      options);
    }
  /**
 * @summary 添加依赖包
 */
const addLibPackage1 = (
    addLibPackageReq: BodyType<AddLibPackageReq>,
 options?: SecondParameter<typeof appRequest<AddLibPackageRes>>,) => {
      return appRequest<AddLibPackageRes>(
      {url: `/file/addLibPackage`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: addLibPackageReq
    },
      options);
    }
  return {uploadFile,uploadFile1,uploadDuplicateFile,uploadDuplicateFile1,updateLibPackage,updateLibPackage1,updateFile,updateFile1,pageLibPackage,pageLibPackage1,pageFile,pageFile1,getLibPackage,getLibPackage1,downloadFile,downloadFile1,deleteLibPackage,deleteLibPackage1,deleteFile,deleteFile1,configLibPackage,configLibPackage1,addLibPackage,addLibPackage1}};
export type UploadFileResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getFile>['uploadFile']>>>
export type UploadFile1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getFile>['uploadFile1']>>>
export type UploadDuplicateFileResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getFile>['uploadDuplicateFile']>>>
export type UploadDuplicateFile1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getFile>['uploadDuplicateFile1']>>>
export type UpdateLibPackageResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getFile>['updateLibPackage']>>>
export type UpdateLibPackage1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getFile>['updateLibPackage1']>>>
export type UpdateFileResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getFile>['updateFile']>>>
export type UpdateFile1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getFile>['updateFile1']>>>
export type PageLibPackageResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getFile>['pageLibPackage']>>>
export type PageLibPackage1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getFile>['pageLibPackage1']>>>
export type PageFileResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getFile>['pageFile']>>>
export type PageFile1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getFile>['pageFile1']>>>
export type GetLibPackageResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getFile>['getLibPackage']>>>
export type GetLibPackage1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getFile>['getLibPackage1']>>>
export type DownloadFileResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getFile>['downloadFile']>>>
export type DownloadFile1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getFile>['downloadFile1']>>>
export type DeleteLibPackageResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getFile>['deleteLibPackage']>>>
export type DeleteLibPackage1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getFile>['deleteLibPackage1']>>>
export type DeleteFileResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getFile>['deleteFile']>>>
export type DeleteFile1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getFile>['deleteFile1']>>>
export type ConfigLibPackageResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getFile>['configLibPackage']>>>
export type ConfigLibPackage1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getFile>['configLibPackage1']>>>
export type AddLibPackageResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getFile>['addLibPackage']>>>
export type AddLibPackage1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getFile>['addLibPackage1']>>>
