/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * 至轻云
 * 超轻量级智能化大数据中心
 * OpenAPI spec version: 0.0.1
 */
import type {
  AddViewCardReq,
  AddViewReq,
  AddViewRes,
  ConfigViewCardReq,
  ConfigViewReq,
  DeleteViewCardReq,
  DeleteViewReq,
  EditViewCardReq,
  EditViewReq,
  GetSqlDataReq,
  GetSqlDataRes,
  GetViewCardDataByIdReq,
  GetViewCardDataByIdRes,
  GetViewCardDataReq,
  GetViewCardDataRes,
  GetViewCardReq,
  GetViewCardRes,
  GetViewLinkInfoReq,
  GetViewLinkInfoRes,
  GetViewLinkReq,
  GetViewLinkRes,
  GetViewReq,
  GetViewRes,
  OfflineViewCardReq,
  OfflineViewReq,
  PageViewCardReq,
  PageViewReq,
  PagedModelPageViewCardRes,
  PagedModelPageViewRes,
  PublishViewCardReq,
  PublishViewReq
} from '../models';

import { appRequest } from '../../api/orval-mutator';
import type { BodyType } from '../../api/orval-mutator';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  export const getDataView = () => {
/**
 * @summary 发布卡片接口
 */
const publishViewCard = (
    publishViewCardReq: BodyType<PublishViewCardReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/api/workspace/vip/view/publishViewCard`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: publishViewCardReq
    },
      options);
    }
  /**
 * @summary 发布卡片接口
 */
const publishViewCard1 = (
    publishViewCardReq: BodyType<PublishViewCardReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/vip/view/publishViewCard`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: publishViewCardReq
    },
      options);
    }
  /**
 * @summary 发布大屏接口
 */
const publishView = (
    publishViewReq: BodyType<PublishViewReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/api/workspace/vip/view/publishView`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: publishViewReq
    },
      options);
    }
  /**
 * @summary 发布大屏接口
 */
const publishView1 = (
    publishViewReq: BodyType<PublishViewReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/vip/view/publishView`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: publishViewReq
    },
      options);
    }
  /**
 * @summary 分页查询卡片接口
 */
const pageViewCard = (
    pageViewCardReq: BodyType<PageViewCardReq>,
 options?: SecondParameter<typeof appRequest<PagedModelPageViewCardRes>>,) => {
      return appRequest<PagedModelPageViewCardRes>(
      {url: `/api/workspace/vip/view/pageViewCard`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: pageViewCardReq
    },
      options);
    }
  /**
 * @summary 分页查询卡片接口
 */
const pageViewCard1 = (
    pageViewCardReq: BodyType<PageViewCardReq>,
 options?: SecondParameter<typeof appRequest<PagedModelPageViewCardRes>>,) => {
      return appRequest<PagedModelPageViewCardRes>(
      {url: `/vip/view/pageViewCard`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: pageViewCardReq
    },
      options);
    }
  /**
 * @summary 分页查询大屏接口
 */
const pageView = (
    pageViewReq: BodyType<PageViewReq>,
 options?: SecondParameter<typeof appRequest<PagedModelPageViewRes>>,) => {
      return appRequest<PagedModelPageViewRes>(
      {url: `/api/workspace/vip/view/pageView`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: pageViewReq
    },
      options);
    }
  /**
 * @summary 分页查询大屏接口
 */
const pageView1 = (
    pageViewReq: BodyType<PageViewReq>,
 options?: SecondParameter<typeof appRequest<PagedModelPageViewRes>>,) => {
      return appRequest<PagedModelPageViewRes>(
      {url: `/vip/view/pageView`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: pageViewReq
    },
      options);
    }
  /**
 * @summary 获取分享大屏链接的id接口
 */
const getViewLinkInfo = (
    getViewLinkInfoReq: BodyType<GetViewLinkInfoReq>,
 options?: SecondParameter<typeof appRequest<GetViewLinkInfoRes>>,) => {
      return appRequest<GetViewLinkInfoRes>(
      {url: `/api/workspace/vip/view/open/getViewLinkInfo`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: getViewLinkInfoReq
    },
      options);
    }
  /**
 * @summary 获取分享大屏链接的id接口
 */
const getViewLinkInfo1 = (
    getViewLinkInfoReq: BodyType<GetViewLinkInfoReq>,
 options?: SecondParameter<typeof appRequest<GetViewLinkInfoRes>>,) => {
      return appRequest<GetViewLinkInfoRes>(
      {url: `/vip/view/open/getViewLinkInfo`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: getViewLinkInfoReq
    },
      options);
    }
  /**
 * @summary 下线卡片接口
 */
const offlineViewCard = (
    offlineViewCardReq: BodyType<OfflineViewCardReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/vip/view/offlineViewCard`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: offlineViewCardReq
    },
      options);
    }
  /**
 * @summary 下线卡片接口
 */
const offlineViewCard1 = (
    offlineViewCardReq: BodyType<OfflineViewCardReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/api/workspace/vip/view/offlineViewCard`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: offlineViewCardReq
    },
      options);
    }
  /**
 * @summary 下线大屏接口
 */
const offlineView = (
    offlineViewReq: BodyType<OfflineViewReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/vip/view/offlineView`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: offlineViewReq
    },
      options);
    }
  /**
 * @summary 下线大屏接口
 */
const offlineView1 = (
    offlineViewReq: BodyType<OfflineViewReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/api/workspace/vip/view/offlineView`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: offlineViewReq
    },
      options);
    }
  /**
 * @summary 获取分享大屏链接的id接口
 */
const getViewLink = (
    getViewLinkReq: BodyType<GetViewLinkReq>,
 options?: SecondParameter<typeof appRequest<GetViewLinkRes>>,) => {
      return appRequest<GetViewLinkRes>(
      {url: `/api/workspace/vip/view/getViewLink`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: getViewLinkReq
    },
      options);
    }
  /**
 * @summary 获取分享大屏链接的id接口
 */
const getViewLink1 = (
    getViewLinkReq: BodyType<GetViewLinkReq>,
 options?: SecondParameter<typeof appRequest<GetViewLinkRes>>,) => {
      return appRequest<GetViewLinkRes>(
      {url: `/vip/view/getViewLink`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: getViewLinkReq
    },
      options);
    }
  /**
 * @summary 查询卡片id查询卡片数据接口
 */
const getViewCardDataById = (
    getViewCardDataByIdReq: BodyType<GetViewCardDataByIdReq>,
 options?: SecondParameter<typeof appRequest<GetViewCardDataByIdRes>>,) => {
      return appRequest<GetViewCardDataByIdRes>(
      {url: `/api/workspace/vip/view/getViewCardDataById`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: getViewCardDataByIdReq
    },
      options);
    }
  /**
 * @summary 查询卡片id查询卡片数据接口
 */
const getViewCardDataById1 = (
    getViewCardDataByIdReq: BodyType<GetViewCardDataByIdReq>,
 options?: SecondParameter<typeof appRequest<GetViewCardDataByIdRes>>,) => {
      return appRequest<GetViewCardDataByIdRes>(
      {url: `/vip/view/getViewCardDataById`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: getViewCardDataByIdReq
    },
      options);
    }
  /**
 * @summary 刷新卡片数据接口
 */
const getViewCardData = (
    getViewCardDataReq: BodyType<GetViewCardDataReq>,
 options?: SecondParameter<typeof appRequest<GetViewCardDataRes>>,) => {
      return appRequest<GetViewCardDataRes>(
      {url: `/vip/view/getViewCardData`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: getViewCardDataReq
    },
      options);
    }
  /**
 * @summary 刷新卡片数据接口
 */
const getViewCardData1 = (
    getViewCardDataReq: BodyType<GetViewCardDataReq>,
 options?: SecondParameter<typeof appRequest<GetViewCardDataRes>>,) => {
      return appRequest<GetViewCardDataRes>(
      {url: `/api/workspace/vip/view/getViewCardData`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: getViewCardDataReq
    },
      options);
    }
  /**
 * @summary 查询卡片接口
 */
const getViewCard = (
    getViewCardReq: BodyType<GetViewCardReq>,
 options?: SecondParameter<typeof appRequest<GetViewCardRes>>,) => {
      return appRequest<GetViewCardRes>(
      {url: `/api/workspace/vip/view/getViewCard`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: getViewCardReq
    },
      options);
    }
  /**
 * @summary 查询卡片接口
 */
const getViewCard1 = (
    getViewCardReq: BodyType<GetViewCardReq>,
 options?: SecondParameter<typeof appRequest<GetViewCardRes>>,) => {
      return appRequest<GetViewCardRes>(
      {url: `/vip/view/getViewCard`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: getViewCardReq
    },
      options);
    }
  /**
 * @summary 查询大屏信息接口
 */
const getView = (
    getViewReq: BodyType<GetViewReq>,
 options?: SecondParameter<typeof appRequest<GetViewRes>>,) => {
      return appRequest<GetViewRes>(
      {url: `/vip/view/getView`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: getViewReq
    },
      options);
    }
  /**
 * @summary 查询大屏信息接口
 */
const getView1 = (
    getViewReq: BodyType<GetViewReq>,
 options?: SecondParameter<typeof appRequest<GetViewRes>>,) => {
      return appRequest<GetViewRes>(
      {url: `/api/workspace/vip/view/getView`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: getViewReq
    },
      options);
    }
  /**
 * @summary sql预览接口
 */
const getSqlData = (
    getSqlDataReq: BodyType<GetSqlDataReq>,
 options?: SecondParameter<typeof appRequest<GetSqlDataRes>>,) => {
      return appRequest<GetSqlDataRes>(
      {url: `/vip/view/getSqlData`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: getSqlDataReq
    },
      options);
    }
  /**
 * @summary sql预览接口
 */
const getSqlData1 = (
    getSqlDataReq: BodyType<GetSqlDataReq>,
 options?: SecondParameter<typeof appRequest<GetSqlDataRes>>,) => {
      return appRequest<GetSqlDataRes>(
      {url: `/api/workspace/vip/view/getSqlData`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: getSqlDataReq
    },
      options);
    }
  /**
 * @summary 编辑卡片信息接口
 */
const editViewCard = (
    editViewCardReq: BodyType<EditViewCardReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/api/workspace/vip/view/editViewCard`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: editViewCardReq
    },
      options);
    }
  /**
 * @summary 编辑卡片信息接口
 */
const editViewCard1 = (
    editViewCardReq: BodyType<EditViewCardReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/vip/view/editViewCard`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: editViewCardReq
    },
      options);
    }
  /**
 * @summary 编辑大屏接口
 */
const editView = (
    editViewReq: BodyType<EditViewReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/api/workspace/vip/view/editView`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: editViewReq
    },
      options);
    }
  /**
 * @summary 编辑大屏接口
 */
const editView1 = (
    editViewReq: BodyType<EditViewReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/vip/view/editView`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: editViewReq
    },
      options);
    }
  /**
 * @summary 删除卡片接口
 */
const deleteViewCard = (
    deleteViewCardReq: BodyType<DeleteViewCardReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/vip/view/deleteViewCard`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: deleteViewCardReq
    },
      options);
    }
  /**
 * @summary 删除卡片接口
 */
const deleteViewCard1 = (
    deleteViewCardReq: BodyType<DeleteViewCardReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/api/workspace/vip/view/deleteViewCard`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: deleteViewCardReq
    },
      options);
    }
  /**
 * @summary 删除大屏接口
 */
const deleteView = (
    deleteViewReq: BodyType<DeleteViewReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/vip/view/deleteView`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: deleteViewReq
    },
      options);
    }
  /**
 * @summary 删除大屏接口
 */
const deleteView1 = (
    deleteViewReq: BodyType<DeleteViewReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/api/workspace/vip/view/deleteView`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: deleteViewReq
    },
      options);
    }
  /**
 * @summary 配置卡片接口
 */
const configViewCard = (
    configViewCardReq: BodyType<ConfigViewCardReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/vip/view/configViewCard`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: configViewCardReq
    },
      options);
    }
  /**
 * @summary 配置卡片接口
 */
const configViewCard1 = (
    configViewCardReq: BodyType<ConfigViewCardReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/api/workspace/vip/view/configViewCard`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: configViewCardReq
    },
      options);
    }
  /**
 * @summary 配置大屏接口
 */
const configView = (
    configViewReq: BodyType<ConfigViewReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/api/workspace/vip/view/configView`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: configViewReq
    },
      options);
    }
  /**
 * @summary 配置大屏接口
 */
const configView1 = (
    configViewReq: BodyType<ConfigViewReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/vip/view/configView`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: configViewReq
    },
      options);
    }
  /**
 * @summary 创建卡片接口
 */
const addViewCard = (
    addViewCardReq: BodyType<AddViewCardReq>,
 options?: SecondParameter<typeof appRequest<GetViewCardRes>>,) => {
      return appRequest<GetViewCardRes>(
      {url: `/api/workspace/vip/view/addViewCard`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: addViewCardReq
    },
      options);
    }
  /**
 * @summary 创建卡片接口
 */
const addViewCard1 = (
    addViewCardReq: BodyType<AddViewCardReq>,
 options?: SecondParameter<typeof appRequest<GetViewCardRes>>,) => {
      return appRequest<GetViewCardRes>(
      {url: `/vip/view/addViewCard`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: addViewCardReq
    },
      options);
    }
  /**
 * @summary 创建大屏接口
 */
const addView = (
    addViewReq: BodyType<AddViewReq>,
 options?: SecondParameter<typeof appRequest<AddViewRes>>,) => {
      return appRequest<AddViewRes>(
      {url: `/api/workspace/vip/view/addView`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: addViewReq
    },
      options);
    }
  /**
 * @summary 创建大屏接口
 */
const addView1 = (
    addViewReq: BodyType<AddViewReq>,
 options?: SecondParameter<typeof appRequest<AddViewRes>>,) => {
      return appRequest<AddViewRes>(
      {url: `/vip/view/addView`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: addViewReq
    },
      options);
    }
  return {publishViewCard,publishViewCard1,publishView,publishView1,pageViewCard,pageViewCard1,pageView,pageView1,getViewLinkInfo,getViewLinkInfo1,offlineViewCard,offlineViewCard1,offlineView,offlineView1,getViewLink,getViewLink1,getViewCardDataById,getViewCardDataById1,getViewCardData,getViewCardData1,getViewCard,getViewCard1,getView,getView1,getSqlData,getSqlData1,editViewCard,editViewCard1,editView,editView1,deleteViewCard,deleteViewCard1,deleteView,deleteView1,configViewCard,configViewCard1,configView,configView1,addViewCard,addViewCard1,addView,addView1}};
export type PublishViewCardResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getDataView>['publishViewCard']>>>
export type PublishViewCard1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getDataView>['publishViewCard1']>>>
export type PublishViewResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getDataView>['publishView']>>>
export type PublishView1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getDataView>['publishView1']>>>
export type PageViewCardResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getDataView>['pageViewCard']>>>
export type PageViewCard1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getDataView>['pageViewCard1']>>>
export type PageViewResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getDataView>['pageView']>>>
export type PageView1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getDataView>['pageView1']>>>
export type GetViewLinkInfoResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getDataView>['getViewLinkInfo']>>>
export type GetViewLinkInfo1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getDataView>['getViewLinkInfo1']>>>
export type OfflineViewCardResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getDataView>['offlineViewCard']>>>
export type OfflineViewCard1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getDataView>['offlineViewCard1']>>>
export type OfflineViewResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getDataView>['offlineView']>>>
export type OfflineView1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getDataView>['offlineView1']>>>
export type GetViewLinkResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getDataView>['getViewLink']>>>
export type GetViewLink1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getDataView>['getViewLink1']>>>
export type GetViewCardDataByIdResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getDataView>['getViewCardDataById']>>>
export type GetViewCardDataById1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getDataView>['getViewCardDataById1']>>>
export type GetViewCardDataResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getDataView>['getViewCardData']>>>
export type GetViewCardData1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getDataView>['getViewCardData1']>>>
export type GetViewCardResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getDataView>['getViewCard']>>>
export type GetViewCard1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getDataView>['getViewCard1']>>>
export type GetViewResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getDataView>['getView']>>>
export type GetView1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getDataView>['getView1']>>>
export type GetSqlDataResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getDataView>['getSqlData']>>>
export type GetSqlData1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getDataView>['getSqlData1']>>>
export type EditViewCardResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getDataView>['editViewCard']>>>
export type EditViewCard1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getDataView>['editViewCard1']>>>
export type EditViewResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getDataView>['editView']>>>
export type EditView1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getDataView>['editView1']>>>
export type DeleteViewCardResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getDataView>['deleteViewCard']>>>
export type DeleteViewCard1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getDataView>['deleteViewCard1']>>>
export type DeleteViewResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getDataView>['deleteView']>>>
export type DeleteView1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getDataView>['deleteView1']>>>
export type ConfigViewCardResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getDataView>['configViewCard']>>>
export type ConfigViewCard1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getDataView>['configViewCard1']>>>
export type ConfigViewResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getDataView>['configView']>>>
export type ConfigView1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getDataView>['configView1']>>>
export type AddViewCardResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getDataView>['addViewCard']>>>
export type AddViewCard1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getDataView>['addViewCard1']>>>
export type AddViewResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getDataView>['addView']>>>
export type AddView1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getDataView>['addView1']>>>
