/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * 至轻云
 * 超轻量级智能化大数据中心
 * OpenAPI spec version: 0.0.1
 */
import type {
  AbortMetaWokInstanceReq,
  AddMetaWokReq,
  AddMetaWokRes,
  DeleteColumnLinageReq,
  DeleteMetaWokInstanceReq,
  DeleteMetaWokReq,
  DisableMetaWokReq,
  EditColumnLinageReq,
  EnableMetaWokReq,
  ExportTableExcelReq,
  GetColumnLinageReq,
  GetColumnLinageRes,
  GetDataSourceDataRes,
  GetDbLinageReq,
  GetDbLinageRes,
  GetMetaTableColumnReq,
  GetMetaTableDataReq,
  GetMetaTableInfoReq,
  GetMetaTableInfoRes,
  GetTableLinageReq,
  GetTableLinageRes,
  PageMetaColumnReq,
  PageMetaDatabaseReq,
  PageMetaTableReq,
  PageMetaWorkInstanceReq,
  PageMetaWorkReq,
  PagedModelPageMetaColumnRes,
  PagedModelPageMetaDatabaseRes,
  PagedModelPageMetaTableRes,
  PagedModelPageMetaWorkInstanceRes,
  PagedModelPageMetaWorkRes,
  QueryColumnDto,
  RefreshMetaTableInfoReq,
  TriggerMetaWokReq,
  UpdateColumnCommentReq,
  UpdateDatabaseCommentReq,
  UpdateMetaWokReq,
  UpdateTableCommentReq
} from '../models';

import { appRequest } from '../../api/orval-mutator';
import type { BodyType } from '../../api/orval-mutator';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  export const getMetadata = () => {
/**
 * @summary 修改元数据表的备注
 */
const updateTableComment = (
    updateTableCommentReq: BodyType<UpdateTableCommentReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/vip/meta/updateTableComment`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: updateTableCommentReq
    },
      options);
    }
  /**
 * @summary 修改元数据表的备注
 */
const updateTableComment1 = (
    updateTableCommentReq: BodyType<UpdateTableCommentReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/api/workspace/vip/meta/updateTableComment`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: updateTableCommentReq
    },
      options);
    }
  /**
 * @summary 更新采集任务接口
 */
const updateMetaWork = (
    updateMetaWokReq: BodyType<UpdateMetaWokReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/api/workspace/vip/meta/updateMetaWork`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: updateMetaWokReq
    },
      options);
    }
  /**
 * @summary 更新采集任务接口
 */
const updateMetaWork1 = (
    updateMetaWokReq: BodyType<UpdateMetaWokReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/vip/meta/updateMetaWork`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: updateMetaWokReq
    },
      options);
    }
  /**
 * @summary 修改元数据db的备注
 */
const updateDatabaseComment = (
    updateDatabaseCommentReq: BodyType<UpdateDatabaseCommentReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/api/workspace/vip/meta/updateDatabaseComment`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: updateDatabaseCommentReq
    },
      options);
    }
  /**
 * @summary 修改元数据db的备注
 */
const updateDatabaseComment1 = (
    updateDatabaseCommentReq: BodyType<UpdateDatabaseCommentReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/vip/meta/updateDatabaseComment`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: updateDatabaseCommentReq
    },
      options);
    }
  /**
 * @summary 修改元数据字段的备注
 */
const updateColumnComment = (
    updateColumnCommentReq: BodyType<UpdateColumnCommentReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/vip/meta/updateColumnComment`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: updateColumnCommentReq
    },
      options);
    }
  /**
 * @summary 修改元数据字段的备注
 */
const updateColumnComment1 = (
    updateColumnCommentReq: BodyType<UpdateColumnCommentReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/api/workspace/vip/meta/updateColumnComment`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: updateColumnCommentReq
    },
      options);
    }
  /**
 * @summary 执行采集接口
 */
const triggerMetaWork = (
    triggerMetaWokReq: BodyType<TriggerMetaWokReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/vip/meta/triggerMetaWork`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: triggerMetaWokReq
    },
      options);
    }
  /**
 * @summary 执行采集接口
 */
const triggerMetaWork1 = (
    triggerMetaWokReq: BodyType<TriggerMetaWokReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/api/workspace/vip/meta/triggerMetaWork`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: triggerMetaWokReq
    },
      options);
    }
  /**
 * @summary 刷新表基础信息接口
 */
const refreshMetaTableInfo = (
    refreshMetaTableInfoReq: BodyType<RefreshMetaTableInfoReq>,
 options?: SecondParameter<typeof appRequest<GetMetaTableInfoRes>>,) => {
      return appRequest<GetMetaTableInfoRes>(
      {url: `/api/workspace/vip/meta/refreshMetaTableInfo`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: refreshMetaTableInfoReq
    },
      options);
    }
  /**
 * @summary 刷新表基础信息接口
 */
const refreshMetaTableInfo1 = (
    refreshMetaTableInfoReq: BodyType<RefreshMetaTableInfoReq>,
 options?: SecondParameter<typeof appRequest<GetMetaTableInfoRes>>,) => {
      return appRequest<GetMetaTableInfoRes>(
      {url: `/vip/meta/refreshMetaTableInfo`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: refreshMetaTableInfoReq
    },
      options);
    }
  /**
 * @summary 刷新元数据数据源接口
 */
const refreshMetaDatabase = (

 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/vip/meta/refreshMetaDatabase`, method: 'POST'
    },
      options);
    }
  /**
 * @summary 刷新元数据数据源接口
 */
const refreshMetaDatabase1 = (

 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/api/workspace/vip/meta/refreshMetaDatabase`, method: 'POST'
    },
      options);
    }
  /**
 * @summary 分页查询采集实例接口
 */
const pageMetaWorkInstance = (
    pageMetaWorkInstanceReq: BodyType<PageMetaWorkInstanceReq>,
 options?: SecondParameter<typeof appRequest<PagedModelPageMetaWorkInstanceRes>>,) => {
      return appRequest<PagedModelPageMetaWorkInstanceRes>(
      {url: `/api/workspace/vip/meta/pageMetaWorkInstance`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: pageMetaWorkInstanceReq
    },
      options);
    }
  /**
 * @summary 分页查询采集实例接口
 */
const pageMetaWorkInstance1 = (
    pageMetaWorkInstanceReq: BodyType<PageMetaWorkInstanceReq>,
 options?: SecondParameter<typeof appRequest<PagedModelPageMetaWorkInstanceRes>>,) => {
      return appRequest<PagedModelPageMetaWorkInstanceRes>(
      {url: `/vip/meta/pageMetaWorkInstance`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: pageMetaWorkInstanceReq
    },
      options);
    }
  /**
 * @summary 分页查询采集任务接口
 */
const pageMetaWork = (
    pageMetaWorkReq: BodyType<PageMetaWorkReq>,
 options?: SecondParameter<typeof appRequest<PagedModelPageMetaWorkRes>>,) => {
      return appRequest<PagedModelPageMetaWorkRes>(
      {url: `/api/workspace/vip/meta/pageMetaWork`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: pageMetaWorkReq
    },
      options);
    }
  /**
 * @summary 分页查询采集任务接口
 */
const pageMetaWork1 = (
    pageMetaWorkReq: BodyType<PageMetaWorkReq>,
 options?: SecondParameter<typeof appRequest<PagedModelPageMetaWorkRes>>,) => {
      return appRequest<PagedModelPageMetaWorkRes>(
      {url: `/vip/meta/pageMetaWork`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: pageMetaWorkReq
    },
      options);
    }
  /**
 * @summary 查询元数据表接口
 */
const pageMetaTable = (
    pageMetaTableReq: BodyType<PageMetaTableReq>,
 options?: SecondParameter<typeof appRequest<PagedModelPageMetaTableRes>>,) => {
      return appRequest<PagedModelPageMetaTableRes>(
      {url: `/vip/meta/pageMetaTable`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: pageMetaTableReq
    },
      options);
    }
  /**
 * @summary 查询元数据表接口
 */
const pageMetaTable1 = (
    pageMetaTableReq: BodyType<PageMetaTableReq>,
 options?: SecondParameter<typeof appRequest<PagedModelPageMetaTableRes>>,) => {
      return appRequest<PagedModelPageMetaTableRes>(
      {url: `/api/workspace/vip/meta/pageMetaTable`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: pageMetaTableReq
    },
      options);
    }
  /**
 * @summary 查询元数据数据源接口
 */
const pageMetaDatabase = (
    pageMetaDatabaseReq: BodyType<PageMetaDatabaseReq>,
 options?: SecondParameter<typeof appRequest<PagedModelPageMetaDatabaseRes>>,) => {
      return appRequest<PagedModelPageMetaDatabaseRes>(
      {url: `/api/workspace/vip/meta/pageMetaDatabase`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: pageMetaDatabaseReq
    },
      options);
    }
  /**
 * @summary 查询元数据数据源接口
 */
const pageMetaDatabase1 = (
    pageMetaDatabaseReq: BodyType<PageMetaDatabaseReq>,
 options?: SecondParameter<typeof appRequest<PagedModelPageMetaDatabaseRes>>,) => {
      return appRequest<PagedModelPageMetaDatabaseRes>(
      {url: `/vip/meta/pageMetaDatabase`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: pageMetaDatabaseReq
    },
      options);
    }
  /**
 * @summary 分页查询字段接口
 */
const pageMetaColumn = (
    pageMetaColumnReq: BodyType<PageMetaColumnReq>,
 options?: SecondParameter<typeof appRequest<PagedModelPageMetaColumnRes>>,) => {
      return appRequest<PagedModelPageMetaColumnRes>(
      {url: `/vip/meta/pageMetaColumn`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: pageMetaColumnReq
    },
      options);
    }
  /**
 * @summary 分页查询字段接口
 */
const pageMetaColumn1 = (
    pageMetaColumnReq: BodyType<PageMetaColumnReq>,
 options?: SecondParameter<typeof appRequest<PagedModelPageMetaColumnRes>>,) => {
      return appRequest<PagedModelPageMetaColumnRes>(
      {url: `/api/workspace/vip/meta/pageMetaColumn`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: pageMetaColumnReq
    },
      options);
    }
  /**
 * @summary 获取表的血缘关系
 */
const getTableLinage = (
    getTableLinageReq: BodyType<GetTableLinageReq>,
 options?: SecondParameter<typeof appRequest<GetTableLinageRes>>,) => {
      return appRequest<GetTableLinageRes>(
      {url: `/vip/meta/getTableLinage`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: getTableLinageReq
    },
      options);
    }
  /**
 * @summary 获取表的血缘关系
 */
const getTableLinage1 = (
    getTableLinageReq: BodyType<GetTableLinageReq>,
 options?: SecondParameter<typeof appRequest<GetTableLinageRes>>,) => {
      return appRequest<GetTableLinageRes>(
      {url: `/api/workspace/vip/meta/getTableLinage`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: getTableLinageReq
    },
      options);
    }
  /**
 * @summary 查询表基础信息接口
 */
const getMetaTableInfo = (
    getMetaTableInfoReq: BodyType<GetMetaTableInfoReq>,
 options?: SecondParameter<typeof appRequest<GetMetaTableInfoRes>>,) => {
      return appRequest<GetMetaTableInfoRes>(
      {url: `/vip/meta/getMetaTableInfo`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: getMetaTableInfoReq
    },
      options);
    }
  /**
 * @summary 查询表基础信息接口
 */
const getMetaTableInfo1 = (
    getMetaTableInfoReq: BodyType<GetMetaTableInfoReq>,
 options?: SecondParameter<typeof appRequest<GetMetaTableInfoRes>>,) => {
      return appRequest<GetMetaTableInfoRes>(
      {url: `/api/workspace/vip/meta/getMetaTableInfo`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: getMetaTableInfoReq
    },
      options);
    }
  /**
 * @summary 查看表预览数据接口
 */
const getMetaTableData = (
    getMetaTableDataReq: BodyType<GetMetaTableDataReq>,
 options?: SecondParameter<typeof appRequest<GetDataSourceDataRes>>,) => {
      return appRequest<GetDataSourceDataRes>(
      {url: `/api/workspace/vip/meta/getMetaTableData`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: getMetaTableDataReq
    },
      options);
    }
  /**
 * @summary 查看表预览数据接口
 */
const getMetaTableData1 = (
    getMetaTableDataReq: BodyType<GetMetaTableDataReq>,
 options?: SecondParameter<typeof appRequest<GetDataSourceDataRes>>,) => {
      return appRequest<GetDataSourceDataRes>(
      {url: `/vip/meta/getMetaTableData`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: getMetaTableDataReq
    },
      options);
    }
  /**
 * @summary 查看表字段列表接口
 */
const getMetaTableColumn = (
    getMetaTableColumnReq: BodyType<GetMetaTableColumnReq>,
 options?: SecondParameter<typeof appRequest<QueryColumnDto[]>>,) => {
      return appRequest<QueryColumnDto[]>(
      {url: `/api/workspace/vip/meta/getMetaTableColumn`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: getMetaTableColumnReq
    },
      options);
    }
  /**
 * @summary 查看表字段列表接口
 */
const getMetaTableColumn1 = (
    getMetaTableColumnReq: BodyType<GetMetaTableColumnReq>,
 options?: SecondParameter<typeof appRequest<QueryColumnDto[]>>,) => {
      return appRequest<QueryColumnDto[]>(
      {url: `/vip/meta/getMetaTableColumn`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: getMetaTableColumnReq
    },
      options);
    }
  /**
 * @summary 获取数据源的血缘关系
 */
const getDbLinage = (
    getDbLinageReq: BodyType<GetDbLinageReq>,
 options?: SecondParameter<typeof appRequest<GetDbLinageRes>>,) => {
      return appRequest<GetDbLinageRes>(
      {url: `/vip/meta/getDbLinage`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: getDbLinageReq
    },
      options);
    }
  /**
 * @summary 获取数据源的血缘关系
 */
const getDbLinage1 = (
    getDbLinageReq: BodyType<GetDbLinageReq>,
 options?: SecondParameter<typeof appRequest<GetDbLinageRes>>,) => {
      return appRequest<GetDbLinageRes>(
      {url: `/api/workspace/vip/meta/getDbLinage`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: getDbLinageReq
    },
      options);
    }
  /**
 * @summary 获取字段的血缘关系
 */
const getColumnLinage = (
    getColumnLinageReq: BodyType<GetColumnLinageReq>,
 options?: SecondParameter<typeof appRequest<GetColumnLinageRes>>,) => {
      return appRequest<GetColumnLinageRes>(
      {url: `/api/workspace/vip/meta/getColumnLinage`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: getColumnLinageReq
    },
      options);
    }
  /**
 * @summary 获取字段的血缘关系
 */
const getColumnLinage1 = (
    getColumnLinageReq: BodyType<GetColumnLinageReq>,
 options?: SecondParameter<typeof appRequest<GetColumnLinageRes>>,) => {
      return appRequest<GetColumnLinageRes>(
      {url: `/vip/meta/getColumnLinage`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: getColumnLinageReq
    },
      options);
    }
  /**
 * @summary 立即执行采集接口
 */
const fastTriggerMetaWork = (
    triggerMetaWokReq: BodyType<TriggerMetaWokReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/vip/meta/fastTriggerMetaWork`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: triggerMetaWokReq
    },
      options);
    }
  /**
 * @summary 立即执行采集接口
 */
const fastTriggerMetaWork1 = (
    triggerMetaWokReq: BodyType<TriggerMetaWokReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/api/workspace/vip/meta/fastTriggerMetaWork`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: triggerMetaWokReq
    },
      options);
    }
  /**
 * @summary 导出表excel接口
 */
const exportTableExcel = (
    exportTableExcelReq: BodyType<ExportTableExcelReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/vip/meta/exportTableExcel`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: exportTableExcelReq
    },
      options);
    }
  /**
 * @summary 导出表excel接口
 */
const exportTableExcel1 = (
    exportTableExcelReq: BodyType<ExportTableExcelReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/api/workspace/vip/meta/exportTableExcel`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: exportTableExcelReq
    },
      options);
    }
  /**
 * @summary 开启采集任务接口
 */
const enableMetaWork = (
    enableMetaWokReq: BodyType<EnableMetaWokReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/vip/meta/enableMetaWork`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: enableMetaWokReq
    },
      options);
    }
  /**
 * @summary 开启采集任务接口
 */
const enableMetaWork1 = (
    enableMetaWokReq: BodyType<EnableMetaWokReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/api/workspace/vip/meta/enableMetaWork`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: enableMetaWokReq
    },
      options);
    }
  /**
 * @summary 编辑字段血缘关系
 */
const editColumnLinage = (
    editColumnLinageReq: BodyType<EditColumnLinageReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/api/workspace/vip/meta/editColumnLinage`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: editColumnLinageReq
    },
      options);
    }
  /**
 * @summary 编辑字段血缘关系
 */
const editColumnLinage1 = (
    editColumnLinageReq: BodyType<EditColumnLinageReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/vip/meta/editColumnLinage`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: editColumnLinageReq
    },
      options);
    }
  /**
 * @summary 关闭采集任务接口
 */
const disableMetaWork = (
    disableMetaWokReq: BodyType<DisableMetaWokReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/vip/meta/disableMetaWork`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: disableMetaWokReq
    },
      options);
    }
  /**
 * @summary 关闭采集任务接口
 */
const disableMetaWork1 = (
    disableMetaWokReq: BodyType<DisableMetaWokReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/api/workspace/vip/meta/disableMetaWork`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: disableMetaWokReq
    },
      options);
    }
  /**
 * @summary 删除采集实例接口
 */
const deleteMetaWorkInstance = (
    deleteMetaWokInstanceReq: BodyType<DeleteMetaWokInstanceReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/api/workspace/vip/meta/deleteMetaWorkInstance`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: deleteMetaWokInstanceReq
    },
      options);
    }
  /**
 * @summary 删除采集实例接口
 */
const deleteMetaWorkInstance1 = (
    deleteMetaWokInstanceReq: BodyType<DeleteMetaWokInstanceReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/vip/meta/deleteMetaWorkInstance`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: deleteMetaWokInstanceReq
    },
      options);
    }
  /**
 * @summary 删除元数据采集任务接口
 */
const deleteMetaWork = (
    deleteMetaWokReq: BodyType<DeleteMetaWokReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/vip/meta/deleteMetaWork`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: deleteMetaWokReq
    },
      options);
    }
  /**
 * @summary 删除元数据采集任务接口
 */
const deleteMetaWork1 = (
    deleteMetaWokReq: BodyType<DeleteMetaWokReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/api/workspace/vip/meta/deleteMetaWork`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: deleteMetaWokReq
    },
      options);
    }
  /**
 * @summary 删除字段血缘关系
 */
const deleteColumnLinage = (
    deleteColumnLinageReq: BodyType<DeleteColumnLinageReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/api/workspace/vip/meta/deleteColumnLinage`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: deleteColumnLinageReq
    },
      options);
    }
  /**
 * @summary 删除字段血缘关系
 */
const deleteColumnLinage1 = (
    deleteColumnLinageReq: BodyType<DeleteColumnLinageReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/vip/meta/deleteColumnLinage`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: deleteColumnLinageReq
    },
      options);
    }
  /**
 * @summary 创建元数据采集任务接口
 */
const addMetaWork = (
    addMetaWokReq: BodyType<AddMetaWokReq>,
 options?: SecondParameter<typeof appRequest<AddMetaWokRes>>,) => {
      return appRequest<AddMetaWokRes>(
      {url: `/api/workspace/vip/meta/addMetaWork`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: addMetaWokReq
    },
      options);
    }
  /**
 * @summary 创建元数据采集任务接口
 */
const addMetaWork1 = (
    addMetaWokReq: BodyType<AddMetaWokReq>,
 options?: SecondParameter<typeof appRequest<AddMetaWokRes>>,) => {
      return appRequest<AddMetaWokRes>(
      {url: `/vip/meta/addMetaWork`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: addMetaWokReq
    },
      options);
    }
  /**
 * @summary 中止采集实例接口
 */
const abortMetaWorkInstance = (
    abortMetaWokInstanceReq: BodyType<AbortMetaWokInstanceReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/vip/meta/abortMetaWorkInstance`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: abortMetaWokInstanceReq
    },
      options);
    }
  /**
 * @summary 中止采集实例接口
 */
const abortMetaWorkInstance1 = (
    abortMetaWokInstanceReq: BodyType<AbortMetaWokInstanceReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/api/workspace/vip/meta/abortMetaWorkInstance`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: abortMetaWokInstanceReq
    },
      options);
    }
  return {updateTableComment,updateTableComment1,updateMetaWork,updateMetaWork1,updateDatabaseComment,updateDatabaseComment1,updateColumnComment,updateColumnComment1,triggerMetaWork,triggerMetaWork1,refreshMetaTableInfo,refreshMetaTableInfo1,refreshMetaDatabase,refreshMetaDatabase1,pageMetaWorkInstance,pageMetaWorkInstance1,pageMetaWork,pageMetaWork1,pageMetaTable,pageMetaTable1,pageMetaDatabase,pageMetaDatabase1,pageMetaColumn,pageMetaColumn1,getTableLinage,getTableLinage1,getMetaTableInfo,getMetaTableInfo1,getMetaTableData,getMetaTableData1,getMetaTableColumn,getMetaTableColumn1,getDbLinage,getDbLinage1,getColumnLinage,getColumnLinage1,fastTriggerMetaWork,fastTriggerMetaWork1,exportTableExcel,exportTableExcel1,enableMetaWork,enableMetaWork1,editColumnLinage,editColumnLinage1,disableMetaWork,disableMetaWork1,deleteMetaWorkInstance,deleteMetaWorkInstance1,deleteMetaWork,deleteMetaWork1,deleteColumnLinage,deleteColumnLinage1,addMetaWork,addMetaWork1,abortMetaWorkInstance,abortMetaWorkInstance1}};
export type UpdateTableCommentResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getMetadata>['updateTableComment']>>>
export type UpdateTableComment1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getMetadata>['updateTableComment1']>>>
export type UpdateMetaWorkResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getMetadata>['updateMetaWork']>>>
export type UpdateMetaWork1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getMetadata>['updateMetaWork1']>>>
export type UpdateDatabaseCommentResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getMetadata>['updateDatabaseComment']>>>
export type UpdateDatabaseComment1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getMetadata>['updateDatabaseComment1']>>>
export type UpdateColumnCommentResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getMetadata>['updateColumnComment']>>>
export type UpdateColumnComment1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getMetadata>['updateColumnComment1']>>>
export type TriggerMetaWorkResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getMetadata>['triggerMetaWork']>>>
export type TriggerMetaWork1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getMetadata>['triggerMetaWork1']>>>
export type RefreshMetaTableInfoResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getMetadata>['refreshMetaTableInfo']>>>
export type RefreshMetaTableInfo1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getMetadata>['refreshMetaTableInfo1']>>>
export type RefreshMetaDatabaseResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getMetadata>['refreshMetaDatabase']>>>
export type RefreshMetaDatabase1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getMetadata>['refreshMetaDatabase1']>>>
export type PageMetaWorkInstanceResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getMetadata>['pageMetaWorkInstance']>>>
export type PageMetaWorkInstance1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getMetadata>['pageMetaWorkInstance1']>>>
export type PageMetaWorkResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getMetadata>['pageMetaWork']>>>
export type PageMetaWork1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getMetadata>['pageMetaWork1']>>>
export type PageMetaTableResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getMetadata>['pageMetaTable']>>>
export type PageMetaTable1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getMetadata>['pageMetaTable1']>>>
export type PageMetaDatabaseResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getMetadata>['pageMetaDatabase']>>>
export type PageMetaDatabase1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getMetadata>['pageMetaDatabase1']>>>
export type PageMetaColumnResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getMetadata>['pageMetaColumn']>>>
export type PageMetaColumn1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getMetadata>['pageMetaColumn1']>>>
export type GetTableLinageResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getMetadata>['getTableLinage']>>>
export type GetTableLinage1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getMetadata>['getTableLinage1']>>>
export type GetMetaTableInfoResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getMetadata>['getMetaTableInfo']>>>
export type GetMetaTableInfo1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getMetadata>['getMetaTableInfo1']>>>
export type GetMetaTableDataResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getMetadata>['getMetaTableData']>>>
export type GetMetaTableData1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getMetadata>['getMetaTableData1']>>>
export type GetMetaTableColumnResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getMetadata>['getMetaTableColumn']>>>
export type GetMetaTableColumn1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getMetadata>['getMetaTableColumn1']>>>
export type GetDbLinageResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getMetadata>['getDbLinage']>>>
export type GetDbLinage1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getMetadata>['getDbLinage1']>>>
export type GetColumnLinageResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getMetadata>['getColumnLinage']>>>
export type GetColumnLinage1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getMetadata>['getColumnLinage1']>>>
export type FastTriggerMetaWorkResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getMetadata>['fastTriggerMetaWork']>>>
export type FastTriggerMetaWork1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getMetadata>['fastTriggerMetaWork1']>>>
export type ExportTableExcelResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getMetadata>['exportTableExcel']>>>
export type ExportTableExcel1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getMetadata>['exportTableExcel1']>>>
export type EnableMetaWorkResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getMetadata>['enableMetaWork']>>>
export type EnableMetaWork1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getMetadata>['enableMetaWork1']>>>
export type EditColumnLinageResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getMetadata>['editColumnLinage']>>>
export type EditColumnLinage1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getMetadata>['editColumnLinage1']>>>
export type DisableMetaWorkResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getMetadata>['disableMetaWork']>>>
export type DisableMetaWork1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getMetadata>['disableMetaWork1']>>>
export type DeleteMetaWorkInstanceResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getMetadata>['deleteMetaWorkInstance']>>>
export type DeleteMetaWorkInstance1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getMetadata>['deleteMetaWorkInstance1']>>>
export type DeleteMetaWorkResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getMetadata>['deleteMetaWork']>>>
export type DeleteMetaWork1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getMetadata>['deleteMetaWork1']>>>
export type DeleteColumnLinageResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getMetadata>['deleteColumnLinage']>>>
export type DeleteColumnLinage1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getMetadata>['deleteColumnLinage1']>>>
export type AddMetaWorkResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getMetadata>['addMetaWork']>>>
export type AddMetaWork1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getMetadata>['addMetaWork1']>>>
export type AbortMetaWorkInstanceResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getMetadata>['abortMetaWorkInstance']>>>
export type AbortMetaWorkInstance1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getMetadata>['abortMetaWorkInstance1']>>>
