/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * 至轻云
 * 超轻量级智能化大数据中心
 * OpenAPI spec version: 0.0.1
 */
import type {
  AddClusterNodeReq,
  CheckAgentReq,
  CleanAgentReq,
  DeleteClusterNodeReq,
  GetClusterNodeReq,
  GetClusterNodeRes,
  InstallAgentReq,
  PageClusterNodeReq,
  PagedModelQueryNodeRes,
  RemoveAgentReq,
  StartAgentReq,
  StopAgentReq,
  TestAgentReq,
  TestAgentRes,
  UpdateClusterNodeReq
} from '../models';

import { appRequest } from '../../api/orval-mutator';
import type { BodyType } from '../../api/orval-mutator';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  export const getClusterNode = () => {
/**
 * @summary 更新引擎节点接口
 */
const updateClusterNode = (
    updateClusterNodeReq: BodyType<UpdateClusterNodeReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/api/workspace/cluster-node/updateClusterNode`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: updateClusterNodeReq
    },
      options);
    }
  /**
 * @summary 更新引擎节点接口
 */
const updateClusterNode1 = (
    updateClusterNodeReq: BodyType<UpdateClusterNodeReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/cluster-node/updateClusterNode`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: updateClusterNodeReq
    },
      options);
    }
  /**
 * @summary 节点链接测试接口
 */
const testAgent = (
    testAgentReq: BodyType<TestAgentReq>,
 options?: SecondParameter<typeof appRequest<TestAgentRes>>,) => {
      return appRequest<TestAgentRes>(
      {url: `/api/workspace/cluster-node/testAgent`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: testAgentReq
    },
      options);
    }
  /**
 * @summary 节点链接测试接口
 */
const testAgent1 = (
    testAgentReq: BodyType<TestAgentReq>,
 options?: SecondParameter<typeof appRequest<TestAgentRes>>,) => {
      return appRequest<TestAgentRes>(
      {url: `/cluster-node/testAgent`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: testAgentReq
    },
      options);
    }
  /**
 * @summary 停止节点接口
 */
const stopAgent = (
    stopAgentReq: BodyType<StopAgentReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/api/workspace/cluster-node/stopAgent`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: stopAgentReq
    },
      options);
    }
  /**
 * @summary 停止节点接口
 */
const stopAgent1 = (
    stopAgentReq: BodyType<StopAgentReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/cluster-node/stopAgent`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: stopAgentReq
    },
      options);
    }
  /**
 * @summary 激活节点接口
 */
const startAgent = (
    startAgentReq: BodyType<StartAgentReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/cluster-node/startAgent`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: startAgentReq
    },
      options);
    }
  /**
 * @summary 激活节点接口
 */
const startAgent1 = (
    startAgentReq: BodyType<StartAgentReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/api/workspace/cluster-node/startAgent`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: startAgentReq
    },
      options);
    }
  /**
 * @summary 卸载代理接口
 */
const removeAgent = (
    removeAgentReq: BodyType<RemoveAgentReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/api/workspace/cluster-node/removeAgent`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: removeAgentReq
    },
      options);
    }
  /**
 * @summary 卸载代理接口
 */
const removeAgent1 = (
    removeAgentReq: BodyType<RemoveAgentReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/cluster-node/removeAgent`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: removeAgentReq
    },
      options);
    }
  /**
 * @summary 查询节点列表接口
 */
const pageClusterNode = (
    pageClusterNodeReq: BodyType<PageClusterNodeReq>,
 options?: SecondParameter<typeof appRequest<PagedModelQueryNodeRes>>,) => {
      return appRequest<PagedModelQueryNodeRes>(
      {url: `/cluster-node/pageClusterNode`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: pageClusterNodeReq
    },
      options);
    }
  /**
 * @summary 查询节点列表接口
 */
const pageClusterNode1 = (
    pageClusterNodeReq: BodyType<PageClusterNodeReq>,
 options?: SecondParameter<typeof appRequest<PagedModelQueryNodeRes>>,) => {
      return appRequest<PagedModelQueryNodeRes>(
      {url: `/api/workspace/cluster-node/pageClusterNode`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: pageClusterNodeReq
    },
      options);
    }
  /**
 * @summary 安装节点接口
 */
const installAgent = (
    installAgentReq: BodyType<InstallAgentReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/api/workspace/cluster-node/installAgent`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: installAgentReq
    },
      options);
    }
  /**
 * @summary 安装节点接口
 */
const installAgent1 = (
    installAgentReq: BodyType<InstallAgentReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/cluster-node/installAgent`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: installAgentReq
    },
      options);
    }
  /**
 * @summary 获取当前集群节点信息接口
 */
const getClusterNode = (
    getClusterNodeReq: BodyType<GetClusterNodeReq>,
 options?: SecondParameter<typeof appRequest<GetClusterNodeRes>>,) => {
      return appRequest<GetClusterNodeRes>(
      {url: `/api/workspace/cluster-node/getClusterNode`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: getClusterNodeReq
    },
      options);
    }
  /**
 * @summary 获取当前集群节点信息接口
 */
const getClusterNode1 = (
    getClusterNodeReq: BodyType<GetClusterNodeReq>,
 options?: SecondParameter<typeof appRequest<GetClusterNodeRes>>,) => {
      return appRequest<GetClusterNodeRes>(
      {url: `/cluster-node/getClusterNode`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: getClusterNodeReq
    },
      options);
    }
  /**
 * @summary 删除节点接口
 */
const deleteClusterNode = (
    deleteClusterNodeReq: BodyType<DeleteClusterNodeReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/cluster-node/deleteClusterNode`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: deleteClusterNodeReq
    },
      options);
    }
  /**
 * @summary 删除节点接口
 */
const deleteClusterNode1 = (
    deleteClusterNodeReq: BodyType<DeleteClusterNodeReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/api/workspace/cluster-node/deleteClusterNode`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: deleteClusterNodeReq
    },
      options);
    }
  /**
 * @summary 清理代理接口
 */
const cleanAgent = (
    cleanAgentReq: BodyType<CleanAgentReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/cluster-node/cleanAgent`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: cleanAgentReq
    },
      options);
    }
  /**
 * @summary 清理代理接口
 */
const cleanAgent1 = (
    cleanAgentReq: BodyType<CleanAgentReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/api/workspace/cluster-node/cleanAgent`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: cleanAgentReq
    },
      options);
    }
  /**
 * @summary 检测节点接口
 */
const checkAgent = (
    checkAgentReq: BodyType<CheckAgentReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/cluster-node/checkAgent`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: checkAgentReq
    },
      options);
    }
  /**
 * @summary 检测节点接口
 */
const checkAgent1 = (
    checkAgentReq: BodyType<CheckAgentReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/api/workspace/cluster-node/checkAgent`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: checkAgentReq
    },
      options);
    }
  /**
 * @summary 添加引擎节点接口
 */
const addClusterNode = (
    addClusterNodeReq: BodyType<AddClusterNodeReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/api/workspace/cluster-node/addClusterNode`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: addClusterNodeReq
    },
      options);
    }
  /**
 * @summary 添加引擎节点接口
 */
const addClusterNode1 = (
    addClusterNodeReq: BodyType<AddClusterNodeReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/cluster-node/addClusterNode`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: addClusterNodeReq
    },
      options);
    }
  return {updateClusterNode,updateClusterNode1,testAgent,testAgent1,stopAgent,stopAgent1,startAgent,startAgent1,removeAgent,removeAgent1,pageClusterNode,pageClusterNode1,installAgent,installAgent1,getClusterNode,getClusterNode1,deleteClusterNode,deleteClusterNode1,cleanAgent,cleanAgent1,checkAgent,checkAgent1,addClusterNode,addClusterNode1}};
export type UpdateClusterNodeResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getClusterNode>['updateClusterNode']>>>
export type UpdateClusterNode1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getClusterNode>['updateClusterNode1']>>>
export type TestAgentResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getClusterNode>['testAgent']>>>
export type TestAgent1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getClusterNode>['testAgent1']>>>
export type StopAgentResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getClusterNode>['stopAgent']>>>
export type StopAgent1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getClusterNode>['stopAgent1']>>>
export type StartAgentResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getClusterNode>['startAgent']>>>
export type StartAgent1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getClusterNode>['startAgent1']>>>
export type RemoveAgentResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getClusterNode>['removeAgent']>>>
export type RemoveAgent1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getClusterNode>['removeAgent1']>>>
export type PageClusterNodeResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getClusterNode>['pageClusterNode']>>>
export type PageClusterNode1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getClusterNode>['pageClusterNode1']>>>
export type InstallAgentResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getClusterNode>['installAgent']>>>
export type InstallAgent1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getClusterNode>['installAgent1']>>>
export type GetClusterNodeResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getClusterNode>['getClusterNode']>>>
export type GetClusterNode1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getClusterNode>['getClusterNode1']>>>
export type DeleteClusterNodeResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getClusterNode>['deleteClusterNode']>>>
export type DeleteClusterNode1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getClusterNode>['deleteClusterNode1']>>>
export type CleanAgentResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getClusterNode>['cleanAgent']>>>
export type CleanAgent1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getClusterNode>['cleanAgent1']>>>
export type CheckAgentResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getClusterNode>['checkAgent']>>>
export type CheckAgent1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getClusterNode>['checkAgent1']>>>
export type AddClusterNodeResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getClusterNode>['addClusterNode']>>>
export type AddClusterNode1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getClusterNode>['addClusterNode1']>>>
