/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * 至轻云
 * 超轻量级智能化大数据中心
 * OpenAPI spec version: 0.0.1
 */
import type {
  AddFuncReq,
  DeleteFuncReq,
  PageFuncReq,
  PagedModelPageFuncRes,
  UpdateFuncReq
} from '../models';

import { appRequest } from '../../api/orval-mutator';
import type { BodyType } from '../../api/orval-mutator';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  export const getFunc = () => {
/**
 * @summary 更新自定义函数接口
 */
const updateFunc = (
    updateFuncReq: BodyType<UpdateFuncReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/func/updateFunc`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: updateFuncReq
    },
      options);
    }
  /**
 * @summary 更新自定义函数接口
 */
const updateFunc1 = (
    updateFuncReq: BodyType<UpdateFuncReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/api/workspace/func/updateFunc`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: updateFuncReq
    },
      options);
    }
  /**
 * @summary 查询自定义函数接口
 */
const pageFunc = (
    pageFuncReq: BodyType<PageFuncReq>,
 options?: SecondParameter<typeof appRequest<PagedModelPageFuncRes>>,) => {
      return appRequest<PagedModelPageFuncRes>(
      {url: `/api/workspace/func/pageFunc`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: pageFuncReq
    },
      options);
    }
  /**
 * @summary 查询自定义函数接口
 */
const pageFunc1 = (
    pageFuncReq: BodyType<PageFuncReq>,
 options?: SecondParameter<typeof appRequest<PagedModelPageFuncRes>>,) => {
      return appRequest<PagedModelPageFuncRes>(
      {url: `/func/pageFunc`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: pageFuncReq
    },
      options);
    }
  /**
 * @summary 删除自定义函数接口
 */
const deleteFunc = (
    deleteFuncReq: BodyType<DeleteFuncReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/api/workspace/func/deleteFunc`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: deleteFuncReq
    },
      options);
    }
  /**
 * @summary 删除自定义函数接口
 */
const deleteFunc1 = (
    deleteFuncReq: BodyType<DeleteFuncReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/func/deleteFunc`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: deleteFuncReq
    },
      options);
    }
  /**
 * @summary 添加自定义函数接口
 */
const addFunc = (
    addFuncReq: BodyType<AddFuncReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/func/addFunc`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: addFuncReq
    },
      options);
    }
  /**
 * @summary 添加自定义函数接口
 */
const addFunc1 = (
    addFuncReq: BodyType<AddFuncReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/api/workspace/func/addFunc`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: addFuncReq
    },
      options);
    }
  return {updateFunc,updateFunc1,pageFunc,pageFunc1,deleteFunc,deleteFunc1,addFunc,addFunc1}};
export type UpdateFuncResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getFunc>['updateFunc']>>>
export type UpdateFunc1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getFunc>['updateFunc1']>>>
export type PageFuncResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getFunc>['pageFunc']>>>
export type PageFunc1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getFunc>['pageFunc1']>>>
export type DeleteFuncResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getFunc>['deleteFunc']>>>
export type DeleteFunc1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getFunc>['deleteFunc1']>>>
export type AddFuncResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getFunc>['addFunc']>>>
export type AddFunc1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getFunc>['addFunc1']>>>
