/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * 至轻云
 * 超轻量级智能化大数据中心
 * OpenAPI spec version: 0.0.1
 */
import type {
  AddClusterReq,
  CheckClusterReq,
  DeleteClusterReq,
  PageClusterReq,
  PagedModelPageClusterRes,
  QueryAllClusterRes,
  SetDefaultClusterReq,
  UpdateClusterReq
} from '../models';

import { appRequest } from '../../api/orval-mutator';
import type { BodyType } from '../../api/orval-mutator';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  export const getCluster = () => {
/**
 * @summary 更新计算集群接口
 */
const updateCluster = (
    updateClusterReq: BodyType<UpdateClusterReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/api/workspace/cluster/updateCluster`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: updateClusterReq
    },
      options);
    }
  /**
 * @summary 更新计算集群接口
 */
const updateCluster1 = (
    updateClusterReq: BodyType<UpdateClusterReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/cluster/updateCluster`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: updateClusterReq
    },
      options);
    }
  /**
 * @summary 设置默认集群接口
 */
const setDefaultCluster = (
    setDefaultClusterReq: BodyType<SetDefaultClusterReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/api/workspace/cluster/setDefaultCluster`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: setDefaultClusterReq
    },
      options);
    }
  /**
 * @summary 设置默认集群接口
 */
const setDefaultCluster1 = (
    setDefaultClusterReq: BodyType<SetDefaultClusterReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/cluster/setDefaultCluster`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: setDefaultClusterReq
    },
      options);
    }
  /**
 * @summary 查询所有集群列表接口
 */
const queryAllCluster = (

 options?: SecondParameter<typeof appRequest<QueryAllClusterRes[]>>,) => {
      return appRequest<QueryAllClusterRes[]>(
      {url: `/api/workspace/cluster/queryAllCluster`, method: 'POST'
    },
      options);
    }
  /**
 * @summary 查询所有集群列表接口
 */
const queryAllCluster1 = (

 options?: SecondParameter<typeof appRequest<QueryAllClusterRes[]>>,) => {
      return appRequest<QueryAllClusterRes[]>(
      {url: `/cluster/queryAllCluster`, method: 'POST'
    },
      options);
    }
  /**
 * @summary 分页查询计算集群接口
 */
const pageCluster = (
    pageClusterReq: BodyType<PageClusterReq>,
 options?: SecondParameter<typeof appRequest<PagedModelPageClusterRes>>,) => {
      return appRequest<PagedModelPageClusterRes>(
      {url: `/cluster/pageCluster`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: pageClusterReq
    },
      options);
    }
  /**
 * @summary 分页查询计算集群接口
 */
const pageCluster1 = (
    pageClusterReq: BodyType<PageClusterReq>,
 options?: SecondParameter<typeof appRequest<PagedModelPageClusterRes>>,) => {
      return appRequest<PagedModelPageClusterRes>(
      {url: `/api/workspace/cluster/pageCluster`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: pageClusterReq
    },
      options);
    }
  /**
 * @summary 删除计算集群接口
 */
const deleteCluster = (
    deleteClusterReq: BodyType<DeleteClusterReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/cluster/deleteCluster`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: deleteClusterReq
    },
      options);
    }
  /**
 * @summary 删除计算集群接口
 */
const deleteCluster1 = (
    deleteClusterReq: BodyType<DeleteClusterReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/api/workspace/cluster/deleteCluster`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: deleteClusterReq
    },
      options);
    }
  /**
 * @summary 检测计算集群接口
 */
const checkCluster = (
    checkClusterReq: BodyType<CheckClusterReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/api/workspace/cluster/checkCluster`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: checkClusterReq
    },
      options);
    }
  /**
 * @summary 检测计算集群接口
 */
const checkCluster1 = (
    checkClusterReq: BodyType<CheckClusterReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/cluster/checkCluster`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: checkClusterReq
    },
      options);
    }
  /**
 * @summary 添加计算集群接口
 */
const addCluster = (
    addClusterReq: BodyType<AddClusterReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/api/workspace/cluster/addCluster`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: addClusterReq
    },
      options);
    }
  /**
 * @summary 添加计算集群接口
 */
const addCluster1 = (
    addClusterReq: BodyType<AddClusterReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/cluster/addCluster`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: addClusterReq
    },
      options);
    }
  return {updateCluster,updateCluster1,setDefaultCluster,setDefaultCluster1,queryAllCluster,queryAllCluster1,pageCluster,pageCluster1,deleteCluster,deleteCluster1,checkCluster,checkCluster1,addCluster,addCluster1}};
export type UpdateClusterResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getCluster>['updateCluster']>>>
export type UpdateCluster1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getCluster>['updateCluster1']>>>
export type SetDefaultClusterResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getCluster>['setDefaultCluster']>>>
export type SetDefaultCluster1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getCluster>['setDefaultCluster1']>>>
export type QueryAllClusterResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getCluster>['queryAllCluster']>>>
export type QueryAllCluster1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getCluster>['queryAllCluster1']>>>
export type PageClusterResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getCluster>['pageCluster']>>>
export type PageCluster1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getCluster>['pageCluster1']>>>
export type DeleteClusterResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getCluster>['deleteCluster']>>>
export type DeleteCluster1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getCluster>['deleteCluster1']>>>
export type CheckClusterResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getCluster>['checkCluster']>>>
export type CheckCluster1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getCluster>['checkCluster1']>>>
export type AddClusterResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getCluster>['addCluster']>>>
export type AddCluster1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getCluster>['addCluster1']>>>
