/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * 至轻云
 * 超轻量级智能化大数据中心
 * OpenAPI spec version: 0.0.1
 */
import type {
  AddAccessRuleReq,
  AddApiReq,
  AddApiRes,
  DeleteAccessRuleReq,
  DeleteApiReq,
  GetApiReq,
  GetApiRes,
  OfflineApiReq,
  PageAccessRuleReq,
  PageApiReq,
  PagedModelPageAccessRuleRes,
  PagedModelPageApiRes,
  PublishApiReq,
  TestApiReq,
  TestApiRes,
  UpdateAccessRuleReq,
  UpdateApiReq,
  UpdateApiRes
} from '../models';

import { appRequest } from '../../api/orval-mutator';
import type { BodyType } from '../../api/orval-mutator';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  export const getApiService = () => {
/**
 * @summary 更新自定义API接口
 */
const updateApi = (
    updateApiReq: BodyType<UpdateApiReq>,
 options?: SecondParameter<typeof appRequest<UpdateApiRes>>,) => {
      return appRequest<UpdateApiRes>(
      {url: `/api/workspace/vip/api-service/updateApi`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: updateApiReq
    },
      options);
    }
  /**
 * @summary 更新自定义API接口
 */
const updateApi1 = (
    updateApiReq: BodyType<UpdateApiReq>,
 options?: SecondParameter<typeof appRequest<UpdateApiRes>>,) => {
      return appRequest<UpdateApiRes>(
      {url: `/vip/api-service/updateApi`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: updateApiReq
    },
      options);
    }
  /**
 * @summary 更新黑白名单规则接口
 */
const updateAccessRule = (
    updateAccessRuleReq: BodyType<UpdateAccessRuleReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/vip/api-service/updateAccessRule`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: updateAccessRuleReq
    },
      options);
    }
  /**
 * @summary 更新黑白名单规则接口
 */
const updateAccessRule1 = (
    updateAccessRuleReq: BodyType<UpdateAccessRuleReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/api/workspace/vip/api-service/updateAccessRule`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: updateAccessRuleReq
    },
      options);
    }
  /**
 * @summary 测试api接口
 */
const testApi = (
    testApiReq: BodyType<TestApiReq>,
 options?: SecondParameter<typeof appRequest<TestApiRes>>,) => {
      return appRequest<TestApiRes>(
      {url: `/api/workspace/vip/api-service/testApi`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: testApiReq
    },
      options);
    }
  /**
 * @summary 测试api接口
 */
const testApi1 = (
    testApiReq: BodyType<TestApiReq>,
 options?: SecondParameter<typeof appRequest<TestApiRes>>,) => {
      return appRequest<TestApiRes>(
      {url: `/vip/api-service/testApi`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: testApiReq
    },
      options);
    }
  /**
 * @summary 发布API接口
 */
const publishApi = (
    publishApiReq: BodyType<PublishApiReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/api/workspace/vip/api-service/publishApi`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: publishApiReq
    },
      options);
    }
  /**
 * @summary 发布API接口
 */
const publishApi1 = (
    publishApiReq: BodyType<PublishApiReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/vip/api-service/publishApi`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: publishApiReq
    },
      options);
    }
  /**
 * @summary 分页api列表接口
 */
const pageApi = (
    pageApiReq: BodyType<PageApiReq>,
 options?: SecondParameter<typeof appRequest<PagedModelPageApiRes>>,) => {
      return appRequest<PagedModelPageApiRes>(
      {url: `/api/workspace/vip/api-service/pageApi`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: pageApiReq
    },
      options);
    }
  /**
 * @summary 分页api列表接口
 */
const pageApi1 = (
    pageApiReq: BodyType<PageApiReq>,
 options?: SecondParameter<typeof appRequest<PagedModelPageApiRes>>,) => {
      return appRequest<PagedModelPageApiRes>(
      {url: `/vip/api-service/pageApi`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: pageApiReq
    },
      options);
    }
  /**
 * @summary 分页查询黑白名单规则接口
 */
const pageAccessRule = (
    pageAccessRuleReq: BodyType<PageAccessRuleReq>,
 options?: SecondParameter<typeof appRequest<PagedModelPageAccessRuleRes>>,) => {
      return appRequest<PagedModelPageAccessRuleRes>(
      {url: `/api/workspace/vip/api-service/pageAccessRule`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: pageAccessRuleReq
    },
      options);
    }
  /**
 * @summary 分页查询黑白名单规则接口
 */
const pageAccessRule1 = (
    pageAccessRuleReq: BodyType<PageAccessRuleReq>,
 options?: SecondParameter<typeof appRequest<PagedModelPageAccessRuleRes>>,) => {
      return appRequest<PagedModelPageAccessRuleRes>(
      {url: `/vip/api-service/pageAccessRule`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: pageAccessRuleReq
    },
      options);
    }
  /**
 * @summary 下线API接口
 */
const offlineApi = (
    offlineApiReq: BodyType<OfflineApiReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/vip/api-service/offlineApi`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: offlineApiReq
    },
      options);
    }
  /**
 * @summary 下线API接口
 */
const offlineApi1 = (
    offlineApiReq: BodyType<OfflineApiReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/api/workspace/vip/api-service/offlineApi`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: offlineApiReq
    },
      options);
    }
  /**
 * @summary 查询单个API信息接口
 */
const getApi3 = (
    getApiReq: BodyType<GetApiReq>,
 options?: SecondParameter<typeof appRequest<GetApiRes>>,) => {
      return appRequest<GetApiRes>(
      {url: `/vip/api-service/getApi`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: getApiReq
    },
      options);
    }
  /**
 * @summary 查询单个API信息接口
 */
const getApi4 = (
    getApiReq: BodyType<GetApiReq>,
 options?: SecondParameter<typeof appRequest<GetApiRes>>,) => {
      return appRequest<GetApiRes>(
      {url: `/api/workspace/vip/api-service/getApi`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: getApiReq
    },
      options);
    }
  /**
 * @summary 删除API接口
 */
const deleteApi = (
    deleteApiReq: BodyType<DeleteApiReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/api/workspace/vip/api-service/deleteApi`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: deleteApiReq
    },
      options);
    }
  /**
 * @summary 删除API接口
 */
const deleteApi1 = (
    deleteApiReq: BodyType<DeleteApiReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/vip/api-service/deleteApi`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: deleteApiReq
    },
      options);
    }
  /**
 * @summary 删除黑白名单规则接口
 */
const deleteAccessRule = (
    deleteAccessRuleReq: BodyType<DeleteAccessRuleReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/api/workspace/vip/api-service/deleteAccessRule`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: deleteAccessRuleReq
    },
      options);
    }
  /**
 * @summary 删除黑白名单规则接口
 */
const deleteAccessRule1 = (
    deleteAccessRuleReq: BodyType<DeleteAccessRuleReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/vip/api-service/deleteAccessRule`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: deleteAccessRuleReq
    },
      options);
    }
  /**
 * @summary 创建自定义API接口
 */
const addApi = (
    addApiReq: BodyType<AddApiReq>,
 options?: SecondParameter<typeof appRequest<AddApiRes>>,) => {
      return appRequest<AddApiRes>(
      {url: `/api/workspace/vip/api-service/addApi`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: addApiReq
    },
      options);
    }
  /**
 * @summary 创建自定义API接口
 */
const addApi1 = (
    addApiReq: BodyType<AddApiReq>,
 options?: SecondParameter<typeof appRequest<AddApiRes>>,) => {
      return appRequest<AddApiRes>(
      {url: `/vip/api-service/addApi`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: addApiReq
    },
      options);
    }
  /**
 * @summary 添加黑白名单规则接口
 */
const addAccessRule = (
    addAccessRuleReq: BodyType<AddAccessRuleReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/vip/api-service/addAccessRule`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: addAccessRuleReq
    },
      options);
    }
  /**
 * @summary 添加黑白名单规则接口
 */
const addAccessRule1 = (
    addAccessRuleReq: BodyType<AddAccessRuleReq>,
 options?: SecondParameter<typeof appRequest<void>>,) => {
      return appRequest<void>(
      {url: `/api/workspace/vip/api-service/addAccessRule`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: addAccessRuleReq
    },
      options);
    }
  return {updateApi,updateApi1,updateAccessRule,updateAccessRule1,testApi,testApi1,publishApi,publishApi1,pageApi,pageApi1,pageAccessRule,pageAccessRule1,offlineApi,offlineApi1,getApi3,getApi4,deleteApi,deleteApi1,deleteAccessRule,deleteAccessRule1,addApi,addApi1,addAccessRule,addAccessRule1}};
export type UpdateApiResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getApiService>['updateApi']>>>
export type UpdateApi1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getApiService>['updateApi1']>>>
export type UpdateAccessRuleResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getApiService>['updateAccessRule']>>>
export type UpdateAccessRule1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getApiService>['updateAccessRule1']>>>
export type TestApiResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getApiService>['testApi']>>>
export type TestApi1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getApiService>['testApi1']>>>
export type PublishApiResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getApiService>['publishApi']>>>
export type PublishApi1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getApiService>['publishApi1']>>>
export type PageApiResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getApiService>['pageApi']>>>
export type PageApi1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getApiService>['pageApi1']>>>
export type PageAccessRuleResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getApiService>['pageAccessRule']>>>
export type PageAccessRule1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getApiService>['pageAccessRule1']>>>
export type OfflineApiResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getApiService>['offlineApi']>>>
export type OfflineApi1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getApiService>['offlineApi1']>>>
export type GetApi3Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getApiService>['getApi3']>>>
export type GetApi4Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getApiService>['getApi4']>>>
export type DeleteApiResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getApiService>['deleteApi']>>>
export type DeleteApi1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getApiService>['deleteApi1']>>>
export type DeleteAccessRuleResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getApiService>['deleteAccessRule']>>>
export type DeleteAccessRule1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getApiService>['deleteAccessRule1']>>>
export type AddApiResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getApiService>['addApi']>>>
export type AddApi1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getApiService>['addApi1']>>>
export type AddAccessRuleResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getApiService>['addAccessRule']>>>
export type AddAccessRule1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getApiService>['addAccessRule1']>>>
