name: pr代码检测
run-name: 【代码检测】${{ github.actor }} - ${{ github.workflow }}

on:
  pull_request:
    branches:
      - '**-#**'

jobs:
  check:

    runs-on: ubuntu-latest

    steps:

      - name: 拉取开源代码
        uses: actions/checkout@v4
        with:
          repository: ${{ github.actor }}/spark-yun
          path: spark-yun
          ref: ${{ github.head_ref }}

      - name: 获取isxcode组织token
        id: generate_token
        uses: actions/create-github-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: 拉取闭源代码
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
        run: |
          gh api octocat
          gh repo clone https://github.com/ispong/spark-yun-vip

      - name: 查看文件是否全了
        run: cd ${{ github.workspace }} && ls -la && pwd