name: pr代码检测
run-name: 【代码检测】${{ github.actor }} - ${{ github.workflow }}

on:
  pull_request:
    branches:
      - '**-#**'

jobs:
  check:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          owner: ${{ github.actor }}
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - uses: actions/checkout@v4
        with:
          repository: ispong/spark-yun-vip
          token: ${{ steps.app-token.outputs.token }}
          ref: ${{ github.head_ref }}
          persist-credentials: false

      - uses: creyD/prettier_action@v4.3
        with:
          github_token: ${{ steps.app-token.outputs.token }}